### ISSUE TITLE
Can't call method "remove" on an undefined value at Mojo/UserAgent.pm line 293

### ISSUE THREAD

**Issue by Corion** [mojolicious/mojo#1257]
* Mojolicious version: 7.94
* Perl version: 5.26
* Operating system: Windows 7

### Steps to reproduce the behavior

Running a screen scraper with a slow network connection, sometimes I get the error+crash `Can't call method remove on undefined value at ...`. I haven't been able to produce a test case for the issue, as it seems to be a tricky timeout/race condition somewhere with Mojo::Daemon::HTTP and/or Mojo::UserAgent in the mix.

The bandaid fix/workaround was very easy, checking that the ioloop is still present before calling functions on it:

```
sub _remove {
  my ($self, $id) = @_;
  my $c = delete $self->{connections}{$id};
  my $l = $c->{ioloop};
  if( $l ) {
      $self->_dequeue($l, $id);
      $l->remove($id);
  };
}
```

I assume the ioloop here becomes undefined because it is a weak reference, but I haven't been able to find the sequence of events that causes this unfortunately. I'll try to investigate this further, but unless in this code path the ioloop should never be undefined, this guard should make the code more robust.

### Expected behavior

No crash should happen.

### Actual behavior

The program crashes with

    Can't call method remove on undefined value at .../Mojo/UserAgent.pm line 293

**Comment by kraih** [comment]
Looks like this issue went stale, if there's no new information i'll close it for now. Unfortunately we've had very bad experiences with adding workarounds like that, and they ended up hiding very serious race conditions, making them even harder to track down. So that's not an option, we need more information.

**Comment by Corion** [comment]
Yeah, I understand that - I'll remove the workaround in my local copy and see if/how I can reproduce the problem in a better/more consistent way. I'll reopen once I get a solid test case, which is what we both want I guess :)

**Comment by bodo-hugo-barwich** [comment]
This behaviour can also be observed when testing invalid WebSocket Requests that cannot be routed to a Controler Module.
```
-- Client <<< Server (http://127.0.0.1:36649/websocket)
\x81~\x03\x16{"Body":{},"RequestID":3}\x81\x7f\x00\x00\x00\x00\x00\x04ÄE{"Body":"<!DOCTYPE html>\n<!-- Request ID: eAASCjKP8EMm -->\n<html>\n  <head>\n    <title>Page Not Found (development mode)<\/title>\n<!-- ... -></head></html>
```
The test app returns a HTML Page and becomes unresponsive and the `Mojo::UserAgent` exits without running the `finish()` method.
