### ISSUE TITLE
Transaction/Websocket.pm does not handle compressed messages with multiple frames correctly

### ISSUE THREAD

**Issue by mgruner** [mojolicious/mojo#1259]
* Mojolicious version: 7.93 (7.94 uses the same code and would also have the same problem)
* Perl version: v5.18.2
* Operating system: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

### Steps to reproduce the behavior

Send a compressed web socket message with multiple frames from Chrome to Mojolicious.

### Expected behavior

Messages are handled correctly.

### Actual behavior

Compressed web socket messages sent from Chrome (69) with more than one frame cause the connection to become corrupt. The client sees a 400 bad request.

It does seem to work with Firefox atm.

### Suggestion

According to https://tools.ietf.org/html/rfc7692, "the RSV1 bit is set only on the first frame."
Mojo's code accepts it on the final frame though. Therefore it works for one-frame sized messages, but not for messages with more than one frame.

This is how I see it also with some debug code that outputs the frame[0-4] fields:

```
parse_message frame 1 1 0 0 1     # one-frame compressed message, works fine

parse_message frame 0 1 0 0 1     # first frame of two-frame compressed message, RSV1 set
parse_message frame 1 0 0 0 0     # second and final frame, RSV1 not set, therefore not decompressed
```

It probably works in Firefox because it keeps sending RSV1, contrary to the specification.

If I change this in parse_message, it starts working correctly (obviously this cannot be a final fix):

``` 
  #if ($self->compressed && $frame->[1]) {
  if ($self->compressed) {
```

For a real solution, the RSV1 bit of the first frame probably needs to be remembered and used for determining the need to decompress the message.

Thanks for considering, and please let me know if I can provide any further information.

**Comment by kraih** [comment]
Something like this should fix the problem, but we'll need a test case before it can be applied.
```diff
diff --git a/lib/Mojo/Transaction/WebSocket.pm b/lib/Mojo/Transaction/WebSocket.pm
index f97d7c1bf..a2783dceb 100644
--- a/lib/Mojo/Transaction/WebSocket.pm
+++ b/lib/Mojo/Transaction/WebSocket.pm
@@ -84,7 +84,8 @@ sub parse_message {
   }

   # Append chunk and check message size
-  $self->{op} = $op unless exists $self->{op};
+  @{$self}{qw(op compressed)} = ($op, $self->compressed && $frame->[1])
+    unless exists $self->{op};
   $self->{message} .= $frame->[5];
   my $max = $self->max_websocket_size;
   return $self->finish(1009) if length $self->{message} > $max;
@@ -94,7 +95,7 @@ sub parse_message {

   # "permessage-deflate" extension (handshake and RSV1)
   my $msg = delete $self->{message};
-  if ($self->compressed && $frame->[1]) {
+  if ($self->{compressed}) {
     my $inflate = $self->{inflate} ||= Compress::Raw::Zlib::Inflate->new(
       Bufsize     => $max,
       LimitOutput => 1,
```

**Comment by kraih** [comment]
Thanks, this should be resolved now.

**Comment by mgruner** [comment]
Thanks a lot @kraih! 👍
