### ISSUE TITLE
Commands broken in Mojolicious 8 ?

### ISSUE THREAD

**Issue by reneeb** [mojolicious/mojo#1262]
```
$ mojo generate plugin Hallo
Can't use string ("Mojolicious::Plugin::Hallo") as a HASH ref while "strict refs" in use at /usr/local/share/perl/5.22.1/Mojo/Template.pm line 264.
$ mojo generate app Halloo
Can't use string ("Halloo") as a HASH ref while "strict refs" in use at /usr/local/share/perl/5.22.1/Mojo/Template.pm line 264.
$ mojo version
CORE
  Perl        (v5.22.1, linux)
  Mojolicious (8.0, Supervillain)

OPTIONAL
  Cpanel::JSON::XS 4.04+  (n/a)
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 2.009+  (2.024)
  Net::DNS::Native 0.15+  (n/a)
  Role::Tiny 2.000001+    (2.000001)

This version is up to date, have fun!
$ 
```

**Comment by kraih** [comment]
Works fine for me.
```
$ mojo generate plugin Test
  [mkdir] /Users/sri/Mojolicious-Plugin-Test/lib/Mojolicious/Plugin
  [write] /Users/sri/Mojolicious-Plugin-Test/lib/Mojolicious/Plugin/Test.pm
  [mkdir] /Users/sri/Mojolicious-Plugin-Test/t
  [write] /Users/sri/Mojolicious-Plugin-Test/t/basic.t
  [exist] /Users/sri/Mojolicious-Plugin-Test
  [write] /Users/sri/Mojolicious-Plugin-Test/Makefile.PL
$ mojo version
CORE
  Perl        (v5.28.0, darwin)
  Mojolicious (8.01, Supervillain)

OPTIONAL
  Cpanel::JSON::XS 4.04+  (4.06)
  EV 4.0+                 (4.22)
  IO::Socket::Socks 0.64+ (0.74)
  IO::Socket::SSL 2.009+  (2.060)
  Net::DNS::Native 0.15+  (0.18)
  Role::Tiny 2.000001+    (2.000006)

Thanks for testing a development release, you are awesome!
```

**Comment by kraih** [comment]
There's also tests. https://github.com/mojolicious/mojo/blob/master/t/mojolicious/commands.t#L301

**Comment by reneeb** [comment]
Ah, after the upgrade the Mojolicious::Command::generate::* plugins still exists (I do not know why...) So it loads the old modules, not the ones from Mojolicious::Command::Author:generate::*.

**Comment by kraih** [comment]
I see, this change should resolve the problem. https://github.com/mojolicious/mojo/commit/74ebae1da81c7f36daaa90fd6e70998994d34491

**Comment by reneeb** [comment]
thanks!

**Comment by kraih** [comment]
@reneeb It would be nice if you could test the change to make sure it actually works.

**Comment by reneeb** [comment]
It works!

**Comment by kberov** [comment]
May be outdated question but still I could not understand why I had to change namespace of the command?

**Comment by kraih** [comment]
The idea was to make it easy to disable author commands in your web apps.

**Comment by kberov** [comment]
By just re-setting commands with for example something like this?
```perl
$app->commands->namespaces(['MyApp','Mojolicious::Command']);
```
and thus removing all commands from the `Mojolicious::Command::Author` sub-namespace?

**Comment by jberger** [comment]
Exactly. It made no sense to distribute applications with all those authoring commands. Those who took the time to avoid it had to jump through hoops to do so. This change makes it easier to do it right, at an unfortunate-but-one-time cost to authors of generate commands. Sorry about that.

**Comment by kberov** [comment]
Ok, understand, thanks.

**Comment by kberov** [comment]
May be I am unfortunate because this command was intended to work with the specific application, to generate things for it specifically from its own, database. Anyway, thanks.

**Comment by jberger** [comment]
If it was/is intended to work with a specific application then it really ought to be in the command's namespace, though I can see why it was easy enough to put it in with the other one. Anyway, this is the wrong place for extended discussion. If there is any more to it, let's please move to IRC or the mailing list.
