### ISSUE TITLE
Different behavior of ->list_tree and ->list on symlink

### ISSUE THREAD

**Issue by Tekki** [mojolicious/mojo#1263]
* Mojolicious version: 8.0
* Perl version: 5.28.0 (perlbrew)
* Operating system: Debian 9.5 (WSL)

### Steps to reproduce the behavior

Create some files and folders:
```
mkdir -p temp1/temp2
touch temp1/file1
touch temp1/file2
touch temp1/temp2/file3
ln -s temp1 templink
```
Run the following script:
```
#! /usr/bin/env perl
use Mojo::Base -strict;

use Mojo::File 'path';

my $source = path 'temp1';

say $source->list->size;      # 2
say $source->list_tree->size; # 3

$source = path 'templink';

say $source->list->size;      # 2
say $source->list_tree->size; # 1

$source = path 'templink/';

say $source->list->size;      # 2
say $source->list_tree->size; # 3
```

### Expected behavior
list should count 2, list_tree should count 3.

### Actual behavior
list_tree only counts 1 on symlink path without trailing slash.

**Comment by kraih** [comment]
I'm not entirely sure if this is a bug or not. I guess it will depend on how ugly the fix would be.

**Comment by Tekki** [comment]
After looking at the Code for Mojo::File: The difference is between readdir and -d on the one and File::Find on the other hand. We could use the follow or follow_fast option for wanted, but not on Win32, and then we can't postprocess the result anymore. So from my point of view, it's getting ugly.

**Comment by Tekki** [comment]
Seems I'm the only one who complains (as always). Shall we close the issue?

**Comment by kraih** [comment]
Yea, we'll close it for now and reopen if new information pops up.
