### ISSUE TITLE
Memory leak when uploading files?

### ISSUE THREAD

**Issue by qyz** [mojolicious/mojo#1265]
* Mojolicious version: 8.01
* Perl version: 5.28.0
* Operating system: Debian 8

### Steps to reproduce the behavior

Step 1: Start a simple Mojo app that receives large file uploads.
```
$ cat memleak.pl 
#!/usr/bin/env perl

BEGIN {
  $ENV{MOJO_MAX_MESSAGE_SIZE}=2 * 1024 * 1024 * 1024; # 2 GB
}

package App;
use Mojo::Base 'Mojolicious';
sub startup {
  my $self = shift;
  $self->routes->post('/')->to('controller#hash');
}

package App::Controller;
use Mojo::Base 'Mojolicious::Controller';
use Digest::SHA qw(sha256_hex);
sub hash {
  my $c = shift;
  my $upload = $c->param('file');
  my $bytes = $upload->slurp;
  $c->render( json => sha256_hex( $bytes ) );
}

package main;
use Mojo::Server::Prefork;
my $server = Mojo::Server::Prefork->new;
$server->build_app('App')->start(@_);

$ ./memleak.pl prefork
[Mon Oct  1 17:58:41 2018] [info] Listening at "http://*:3000"
Server available at http://127.0.0.1:3000
[Mon Oct  1 17:58:41 2018] [info] Manager 23855 started
[Mon Oct  1 17:58:41 2018] [debug] Worker 23856 started
[Mon Oct  1 17:58:41 2018] [debug] Worker 23857 started
[Mon Oct  1 17:58:41 2018] [debug] Worker 23858 started
[Mon Oct  1 17:58:41 2018] [debug] Worker 23859 started
```

Step 2: Upload a 150 MB file repeatedly

```
$ dd if=/dev/urandom of=blob bs=1M count=150
$ for i in $(seq 1 20); do curl -F "file=@blob"  'http://localhost:3000/ ' ; done
```

Step 3: Observe that every one of the mojolicious app's processes keeps about twice the memory in ram.

```
$ ps fu | grep memleak
www      24498  0.1  0.2 106400 34020 pts/1    S+   18:00   0:00  \_ perl ./memleak.pl prefork
www      24536  0.9  2.7 431468 339988 pts/1   S+   18:00   0:01      \_ perl ./memleak.pl prefork
www      24537  1.8  2.7 434972 343364 pts/1   S+   18:00   0:03      \_ perl ./memleak.pl prefork
www      24538  1.8  2.7 434972 343364 pts/1   S+   18:00   0:03      \_ perl ./memleak.pl prefork
www      24539  0.1  0.3 106032 38280 pts/1    S+   18:00   0:00      \_ perl ./memleak.pl prefork
```

### Expected behavior

I'd expect that no one keeps any references to the uploaded file contents and the used memory gets freed by the garbage collector after the request has finished. I understand that two copies of the file's bytes need to be kept in RAM temporarily with this code.

### Actual behavior

The memory is not freed by the garbage collector. I'd expect the garbage collector to free my `$bytes` variable once it has gone out of scope and I'd expect the rendering engine not to keep any references to the rendered data after it has finished rendering.

I'm thankful for any tip on how to circumvent this behaviour.

**Comment by kraih** [comment]
If the memory usage is constant, then that's not a leak. A real leak would grow over time.

**Comment by Grinnz** [comment]
FYI: Perl often frees memory to reuse itself, but not to the operating system.

**Comment by qyz** [comment]
Hi,

> If the memory usage is constant, then that's not a leak. A real leak would grow over time.

Yes, following a sufficiently narrow definition of „leak“, this is undoubtedly correct. Nonetheless, the app requires significantly more memory than it needs to.  The wasted memory does not grow per request, but seems to be limited at about twice the size of the largest upload per process.

> Please elaborate on why you believe this is a problem we can fix in Mojolicious.

From my experience such a behaviour is often caused by a reference loop that cannot be broken by the garbage collector or by a reference that is beeing kept longer than it needs to be kept. I'm pretty new to Mojolicious. I'll try to find the time to hunt this down.

Cheers,
qyz

**Comment by kraih** [comment]
If there was a circular reference memory usage would keep growing though. I'm afraid without more information there is nothing we can do here. So this issue will be closed for now, and reopened later if new information is available. If you would like to discuss this issue further please feel free to join us on IRC or the mailing-list. https://mojolicious.org/perldoc/Mojolicious/Guides/Contributing#SUPPORT

**Comment by kraih** [comment]
And please open a pull request if you find a way to reduce memory usage, even it it isn't actually a bug.

**Comment by qyz** [comment]
Hi,

You are right. This does not look like a problem with Mojolicious. Perl itself does not return allocated memory to the operating system. This is easily demonstrated by these lines:

```
#!/usr/bin/env perl
use Mojo::File;
my $f = Mojo::File->new('large_file');
$content = $f->slurp;
say length($content);
$content = undef;
sleep 600;
```

The process grows when reading `large_file` but never shrinks after the single reference to the data has been cleared.

I'm trying to mitigate this behaviour in my Mojolicious app by exiting the worker immediately after handling a large blob:

```
if ( length($image_bytes) > $RESTART_THRESHOLD ) {
    $c->res->headers->connection('close');
    Mojo::IOLoop->singleton->stop_gracefully;
}
```

Seems to work so far. The real work in my route is much more expensive than the added overhead of restarting a worker anyway.

Thanks for your time,
qyz

**Comment by kraih** [comment]
If the file processing is that expensive it might be worth using [subprocesses](https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Subprocesses) or a job queue like Minion.

**Comment by lindleyw** [comment]
Try replacing "$content = undef;" with "undef $content;" as per [brian d foy's recent article](https://www.effectiveperlprogramming.com/2018/09/undef-a-scalar-to-release-its-memory/) and you should see the memory use decrease.  Perhaps there can be a workaround for folks who concerned about this issue?

**Comment by qyz** [comment]
@lindleyw You are right.

Explicitly setting a scalar to `undef` makes perl return the memory to the operating system. Simply letting the large scalar run out of scope does not.

Returning memory to the operating system works at least sometimes. Whether it actually succeeds seems to depend on the operating system and/or malloc implementation:

When I run the little program from my earlier post with `strace` on a freshly built perl-5.28.0 on Ubuntu 18.04 I can see a call to `munmap`. And that actually makes the process size shrink. And if I stop `Mojo::File::slurp` from storing the data in its own lexical variable by modifying it to read the data into a scalar ref passed by the caller, then the program can read and work on a large file and return all the memory to the os later.

Yesterday I tried this with perl-5.28.0 on a rather dated Debian 8. There, I see no call to `munmap` and the process size does not shrink.

Since both perls were built with the same default settings and use the os malloc, I blame the difference on the different versions of glibc for now.
