### ISSUE TITLE
Does Mojo::URL resolve `///g` as it should?

### ISSUE THREAD

**Issue by briandfoy** [mojolicious/mojo#1269]
* Mojolicious version: VERSION HERE

	CORE
	  Perl        (v5.28.0, darwin)
	  Mojolicious (8.02, Supervillain)

	OPTIONAL
	  Cpanel::JSON::XS 4.04+  (4.04)
	  EV 4.0+                 (n/a)
	  IO::Socket::Socks 0.64+ (n/a)
	  IO::Socket::SSL 2.009+  (2.056)
	  Net::DNS::Native 0.15+  (n/a)
	  Role::Tiny 2.000001+    (2.000006)

	This version is up to date, have fun!

### Steps to reproduce the behavior

In the Stackoverflow question [Resolve URI with multiple slashes in relative part](https://stackoverflow.com/q/52649532/2766176), the poster wonders what `///g` should turn into. Here's what Mojo::URL does:

    $ perl -MMojo::URL -E '$b = Mojo::URL->new( "http://www.example.com" ); say Mojo::URL->new( "///g" )->base( $b )->to_abs'
    http://www.example.com/g

The URI module does something different:

    $ perl-latest -MURI -E 'say URI->new( "///g" )->abs( "http://www.example.com" )'
    http:///g

### Expected behavior

ikegami contends that 5.2.2 of RFC 3986 mandates that we leave the authority blank to get `http:///g`. I did not expect that and from reading that section of the RFC, I still don't expect that. But, I could be wrong. But, ikegami is rarely incorrect (I can't recall that ever, actually), so here we are.

I think it hinges on the definition of `defined`. With a URI reference R, a target URI T, and a base uri Base, there's this decision in 5.2.2:

	if defined(R.authority) then
            T.authority = R.authority;
            T.path      = remove_dot_segments(R.path);
            T.query     = R.query;
         else
            if (R.path == "") then
               T.path = Base.path;
               if defined(R.query) then
                  T.query = R.query;
               else
                  T.query = Base.query;
               endif;
            else
               if (R.path starts-with "/") then
                  T.path = remove_dot_segments(R.path);
               else
                  T.path = merge(Base.path, R.path);
                  T.path = remove_dot_segments(T.path);
               endif;
               T.query = R.query;
            endif;
            T.authority = Base.authority;
         endif;
         T.scheme = Base.scheme;

The first `if` does its work if the authority is defined. Is it defined in `///g`? If so, T takes its authority from R, does a few other things, and that's it. If the authority is not defined, it takes the other branch and ultimately takes the authority from Base.

Certainly present are the delimiters for the authority: `//` and the leading slash for the path, `/`. Between that is nothing. Or, in an alternate reading, between that is the empty string. I'd say the first one is undefined and the second one is defined, but only in the Perl sense. If the second one is true, then Mojo::URL might not be in compliance with the RFC.

The quick way to resolve this is to figure out if you care about compliance at that level. I don't think you do:

> Mojo::URL implements a subset of ...

But let's assume that the subset you care about includes this. Is the authority defined? In 3.2 of the same spec there's this definition that requires at least the host:

    authority   = [ userinfo "@" ] host [ ":" port ]

In 3.2.2, the host must be one of these (so, not empty):

    host        = IP-literal / IPv4address / reg-name

From that I say that an authority of no characters (an empty string one) is no authority at all. Thus, it's undefined and the resolution should take the authority from Base. That's what Mojo::URL does.

I think this is actually a bug in [URI::_server::canonical](https://metacpan.org/source/ETHER/URI-1.74/lib/URI/_server.pm) (parent to URI::http) where it sets the host to the empty string if it is false (which I think is a different bug if `0` can be a host). This subtle change actually loses information I think:

	sub canonical
	{
		my $self = shift;
		my $other = $self->SUPER::canonical;
		my $host = $other->host || "";
		my $port = $other->_port;
		my $uc_host = $host =~ /[A-Z]/;
		my $def_port = defined($port) && ($port eq "" ||
										  $port == $self->default_port);
		if ($uc_host || $def_port) {
			$other = $other->clone if $other == $self;
			$other->host(lc $host) if $uc_host;
			$other->port(undef)    if $def_port;
		}
		$other;
	}

Mojo::URL doesn't do that. The host is the host (and this goes back to Mojo::Base's `attire` (that also doesn't change the value): 

	# Authority
	return $abs if $abs->host;
	$abs->userinfo($base->userinfo)->host($base->host)->port($base->port);

So, there it is.

**Comment by briandfoy** [comment]
I'm completely fine with someone closing this as "working as intended" (and I think it is). I've captured my research and the issue will be here if someone else comes asking for the same thing later.

**Comment by kraih** [comment]
Yes, the specs appear to be pretty vague, and it's unfortunate that this case is not covered by the examples in RFC 3986. From what i can see, any change in behaviour would require additional code. So, lets look at it from a different perspective, do we actually gain anything by changing the behaviour? Otherwise this discussion seems moot.

**Comment by briandfoy** [comment]
I think I have my answer. Mojolicious has made its decision about how to act in this case and it's doing exactly what you intend. I also think it's doing what I think it should do and what I'd want it to do.

I also think that Mojo::URL is compliant with RFC 3986 in this case (and that URI is not), but that the spec is deficient in defining `defined`.
