### ISSUE TITLE
Mojo::Promise->all crashes when called with empty list of promises

### ISSUE THREAD

**Issue by jkramer** [mojolicious/mojo#1275]
* Mojolicious version: 8.02
* Perl version: 5.26
* Operating system: arch linux 4.14.15

### Steps to reproduce the behavior
```
Mojo::Promise->all()

Can't call method "clone" on an undefined value at (...)/Mojo/Promise.pm line 12.
``` 

### Expected behavior
`Mojo::Promise->all()` should resolve instantly when called with an empty list of promises. For the record, this is a feature that was voted for and implemented in #1193. The reasoning for why it should work this way can be found there.

### Actual behavior
Crashes (see above).

**Comment by kraih** [comment]
This stuff is why i wanted to remove the `ioloop` attribute from `Mojo::Promise`. But unfortunately i was outvoted on that and now the code contains these workarounds. Fortunately this specific case was also never documented to work, so we don't really have to fix it.

**Comment by kraih** [comment]
Having had a very long discussion about this problem on IRC, i think we can conclude that throwing an exception in this case is actually the most user friendly solution. Supporting`Mojo::Promise->all()` in addition to `Mojo::Promise->all(@promises)` would introduce an inconsistency that could end up with very hard to debug bugs where your promises would silently use different event loops.
