### ISSUE TITLE
Advice on how to fix breaking dependency on Mojo::Message::Response < 7.12

### ISSUE THREAD

**Issue by pscott-au** [mojolicious/mojo#1282]
* Mojolicious version: .. perhaps this is what I'm looking for .. what version can I specify?
* Perl version: 5.22.2
* Operating system: 3.2.0-4-amd64 | x86_64-linux

### Steps to reproduce the behavior
EXPLAIN WHAT HAPPENED HERE, PREFERABLY WITH CODE EXAMPLES
I'm using Mojo::UserAgent as a dependency in my WebService::GoogleAPI::Client distribution and seeing errors that I trace back to older version of Mojo::Message::Response that doesn't include the is_success property. 
I am unable to specify minimum dependency version in my dist.ini as the version is not specified in the module.
Mojo::Message::Response = 7.12 ## can't do this - no version info available in meta ..
eg when I try to update in cpan I get

    cpan[7]> install Mojo::Message::Response
    Mojo::Message::Response is up to date (undef).

### Expected behavior
EXPLAIN WHAT SHOULD HAPPEN HERE

I should be able to specify minimum version that includes the is_success method ... am looking for advice on best way to do this or should I just refactor to use the code response and match the first character for a 2 instead .. seems unnecessarily messy 
I'm thinking that I should be able to provide a minimum Mojo version in my dependencies that will trigger an update

### Actual behavior
EXPLAIN WHAT HAPPENED INSTEAD HERE

I am unable to specify the min version of Mojo::Message::Response = 7.12 as it is not defined in the package.

**Comment by Grinnz** [comment]
To depend on any package in the Mojolicious distribution, you must depend on Mojolicious which is the only package with a version declared.

**Comment by pscott-au** [comment]
Apologies if this is a silyl question - is there an easy way to determine which version of Mojolicious aligns with Mojo::Message::Response v7.12 or should I just declare dependency on Mojolicious v7.12 .. sorry if this is simple .. I'm getting a little bleary eyed.

**Comment by Grinnz** [comment]
There is no such thing as Mojo::Message::Response 7.12, it does not have a version. It is just Mojolicious 7.12.

**Comment by pscott-au** [comment]
of course - obvious now - many thanks - happy to close.
