### ISSUE TITLE
IPC for subprocesses

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1285]
This comes up every now and then on IRC and i think it would make sense for `Mojo::IOLoop::Subprocess` to have basic support for progress updates. That means a second pipe connecting the two processes, a new method and a new event.
```perl
my $subprocess = Mojo::IOLoop->subprocess(sub {
  my $subprocess = shift;
  sleep 3;
  $subprocess->progress({percentage => 30});
  sleep 3;
  $subprocess->progress({percentage => 60, arbitrary => 'data'});
  sleep 3;
  $subprocess->progress({percentage => 90});
}, sub {
  my ($subprocess, @results) = @_;
  say 'Done!';
});
$subprocess->on(progress => sub {
  my ($subprocess, @data) = @_;
  say $data[0]->{percentage};
});
```
This is mostly rather trivial to implement, but one problem to consider is that progress update data structures might be bigger than the limit for atomic writes. Therefore it might be necessary to a) throw an error if the serialized data structure ends up being bigger, or b) support partial reads and therefore bigger data structures.

**Comment by akarelas** [comment]
What do you think on my take on this? (has test, but no docs)

https://github.com/akarelas/mojo/commit/3be18b8c41fd50698936e176f0eca071f3f31416
