### ISSUE TITLE
Provide subsecond resolution for Mojo::Log

### ISSUE THREAD

**Issue by StefanBruens** [mojolicious/mojo#1287]
* Mojolicious version: 8.01
* Perl version: 5.26.2

### Expected behavior
Mojo::Log should provide the option to use a hires timestamp in the log message.

### Actual behavior
the "time" parameter supplied in the formatting callback only has second resolution.

**Comment by kraih** [comment]
Which time format should we be using then instead? Right now we rely on `localtime(time)`, which is good for performance.

**Comment by kraih** [comment]
Using [Mojo::Date::to_datetime](https://mojolicious.org/perldoc/Mojo/Date#to_datetime) might seem like a nice idea in theory, but it's very much slower than `localtime()`.

**Comment by kraih** [comment]
Benchmarked the difference if we were to default to RFC 3339 format with `examples/hello.pl`. First with `localtime` and second with `Mojo::Date::to_datetime`.
```
Running 10s test @ http://127.0.0.1:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    75.92ms    7.08ms 160.11ms   91.93%
    Req/Sec   659.23    213.34     1.01k    73.00%
  13200 requests in 10.06s, 1.95MB read
Requests/sec:   1312.25
Transfer/sec:    198.82KB


Running 10s test @ http://127.0.0.1:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    83.21ms    7.83ms 171.92ms   94.54%
    Req/Sec   599.52    196.14     1.01k    80.50%
  12002 requests in 10.07s, 1.78MB read
Requests/sec:   1191.97
Transfer/sec:    180.61KB
```

**Comment by kraih** [comment]
If all you want is subsecond time passed to the formatter callback, why can't you just call `Time::HiRes::time` yourself from inside the callback?

**Comment by StefanBruens** [comment]
I use the following to benchmark `Time::HiRes::time` vs `CORE::time`, and although T::HR::time is ~3 times slower, it still runs at ~14e6/s ^= 70ns per call (vs ~25ns) on my computer.
```
#! /usr/bin/perl -w

use Benchmark qw(:all :hireswallclock);
use Time::HiRes;

print localtime(time) . " \t" . time . "\n";
print localtime(Time::HiRes::gettimeofday) . " \t" . Time::HiRes::gettimeofday . "\n";
print localtime(Time::HiRes::time) . " \t" . Time::HiRes::time . "\n";

my $count = 20000000;
cmpthese($count,
        {
          'CORE::time'                 => 'my $t = time',
          'HiRes::gettimeofday scalar' => 'my $t = Time::HiRes::gettimeofday()',
          # 'HiRes::gettimeofday list'   => 'my ($t, $ut) = Time::HiRes::gettimeofday()',
          'HiRes::time'                => 'my $t = Time::HiRes::time()'
        }
);
```

```
                                 Rate HiRes::gettimeofday scalar HiRes::time CORE::time
HiRes::gettimeofday scalar 10309278/s                         --        -27%       -74%
HiRes::time                14084507/s                        37%          --       -64%
CORE::time                 39215686/s                       280%        178%         --
```

**Comment by kraih** [comment]
I made a mistake with my benchmark, the difference is not noticeable. And we have a new timestamp format already.
![9gqxmec](https://user-images.githubusercontent.com/30094/48220383-6cccf500-e38f-11e8-8032-cd26bf47c25f.png)

**Comment by s1037989** [comment]
This is fantastic!!!  Seeing several entries each with the same second has often been pretty unhelpful.  This is going to be so helpful!!!

**Comment by StefanBruens** [comment]
For completeness:
https://github.com/mojolicious/mojo/commit/6f9876f3cbf1f20205e7aedcbbe2649e41a631a3#diff-c112bb3542e98308d12d5ecb10a67abc
Version 8.06
