### ISSUE TITLE
Better load balancing

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1290]
Every now and then this becomes a problem for Mojolicious applications that accept a lot of concurrent connections. The current strategy for the prefork web server is to let the manager pass the listen socket to all the workers, and they accept as many connections as they want. So it is up to the operating system how incoming connections get distributed. Unfortunately that often ends up with one or two workers handling the majority of connections, while the rest remains idle.

So i believe it would make sense to support a second strategy as well. We could use a module like [IO::FDPass](https://metacpan.org/pod/IO::FDPass) to let the manager process accept incoming connections and then send the accepted socket file descriptors round robin to the workers.

**Comment by kraih** [comment]
Node.js does this with the [cluster](https://nodejs.org/api/cluster.html#cluster_how_it_works) module. It's actually not very complicated.

**Comment by kraih** [comment]
It should be possible to implement this as an optimization with an optional dependency, without too much new code. A second code path in `Mojo::IOLoop::Server` that replaces the accept with `IO::FDPass` for all the workers, and a new acceptor in `Mojo::Server::Prefork` that replaces the `sleep` and sends accepted socket file descriptors to the workers round robin.

**Comment by nsnake** [comment]
great job！

**Comment by tomk3003** [comment]
The only platform I could reproduce this kind of behaviour on is Windows (I used Win7). Linux (Kernel 4.15.18) and Solaris seem to distribute the load evenly. And even Windows only shows this when the load on the server is relatively low (<200 rq/s with 10 workers). 
Is there a known OS and Version that `Mojo::Server::Prefork` runs on where one could test this?

**Comment by kraih** [comment]
I've just done some benchmarks on an 8 core/16 hyperthreads machine, and macOS seems to distribute load very evenly too. Maybe this is a non-issue after all.
