### ISSUE TITLE
Mojo::JSON::Pointer should return undef for all invalid paths

### ISSUE THREAD

**Issue by karenetheridge** [mojolicious/mojo#1296]
* Mojolicious version: 8.04

By my reading of https://tools.ietf.org/html/rfc6901, json pointers should always start with `/`. If they don't, the pointer is invalid, and data should not be returned.  However, Mojo::JSON::Pointer returns the entire document when provided a path that lacks a leading `/`, which is the same as if `''` had been passed, and causes operator confusion.

This patch demonstrates the issue; the first test fails (the entire document is returned), but it should behave the same as the second (passing) test, returning undef when an unresolvable pointer is passed:

```
diff --git a/t/mojo/json_pointer.t b/t/mojo/json_pointer.t
index 0a34579c5..503eea45a 100644
--- a/t/mojo/json_pointer.t
+++ b/t/mojo/json_pointer.t
@@ -90,6 +90,8 @@ my $hash = {
 };
 $pointer = Mojo::JSON::Pointer->new($hash);
 is_deeply $pointer->get(''), $hash, 'empty pointer is whole document';
+is_deeply $pointer->get('foo'), undef, 'pointer without leading slash is undef';
+is_deeply $pointer->get('/bar'), undef, 'pointer to non-existent path is undef';
 is_deeply $pointer->get('/foo'), ['bar', 'baz'], '"/foo" is "["bar", "baz"]"';
 is $pointer->get('/foo/0'), 'bar', '"/foo/0" is "bar"';
 is $pointer->get('/'),      0,     '"/" is 0';
```

```
ok 39 - empty pointer is whole document
not ok 40 - pointer without leading slash is undef
#   Failed test 'pointer without leading slash is undef'
#   at t/mojo/json_pointer.t line 93.
#     Structures begin differing at:
#          $got = HASH(0x7f81cba40670)
#     $expected = undef
ok 41 - pointer to non-existent path is undef
```

**Comment by kraih** [comment]
I'm afraid it looks like this issue went stale and handling of invalid pointers is not clearly defined in the RFC, so i'm closing it for now.

**Comment by kraih** [comment]
Suppose we can consider this a "wontfix", due to lack of community interest.

**Comment by karenetheridge** [comment]
would you merge a patch if I provided one?
