### ISSUE TITLE
Make the built-in templates responsive

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1307]
I think there is no reason for Mojolicious built-in templates to look bad on mobile devices. So lets just make them responsive. Some time ago @jhthorsen [already attempted this](https://github.com/mojolicious/mojo/pull/1304), but apparently didn't have time to finish the project. So maybe someone else would like to give it a try.

**Comment by kraih** [comment]
There have been no proposals for using Bootstrap so far.

**Comment by Grinnz** [comment]
Using Bootstrap is difficult because CSS scoping is not really supported by anything, so the rest of the page has to account for Bootstrap styles as I've had to do on perldoc.pl.

**Comment by Tekki** [comment]
It's exactly because of the CSS and JS stuff I'm asking. For example the innerWidth of 900 in the PR may be a big screen if we are on an Android device, but a small one if it's a retina display. And so on. I'm not sure if we come to an end if we try to solve all this in a Perl project.

**Comment by Grinnz** [comment]
It is not the pages that require it to be complex but the myriad of situations that it handles to be responsive.

**Comment by kraih** [comment]
I think it would make sense to stop reusing the `mojo/menubar` template in https://github.com/mojolicious/mojolicious.org and duplicate the parts both use. We just have to make sure to sync changes to the menubar in the future. So if someone wants to do a full cleanup of the built-in templates i'd be fine with that too.

**Comment by kraih** [comment]
In fact, i've already duplicated the `menubar` template in both repos, so no templates are shared anymore and we can focus on cleaning things up. https://github.com/mojolicious/mojolicious.org/commit/5185355bd8a66dd760724d2f5616b61dcb8eb57e

**Comment by kraih** [comment]
After thinking a bit more about it i'm in favour of using Bootstrap, consistent with `Mojolicious::Plugin::Minion::Admin` and `Mojolicious::Plugin::Status`.

**Comment by macsnowball** [comment]
I'd be up for taking a look at this

**Comment by kraih** [comment]
I guess it would make sense to make https://mojolicious.org also responsive. Could be part of this issue, or just a followup.

**Comment by kraih** [comment]
Our main site has already been converted, now we just need to do the same for the built-in templates.

**Comment by jhthorsen** [comment]
I don't agree that this this is done for https://mojolicious.org: The issue is that you have to zoom to make the text readable, and after zooming you have to pan around to see the full content.

See the screenshots below taken from browserstack.com

### Pixel 4, Chrome
<img width="397" alt="Screenshot 2020-10-07 at 11 17 33" src="https://user-images.githubusercontent.com/45729/95280042-0a3c4680-088f-11eb-89b9-a6e97f2916fc.png">

### iPhone 11, Safari
<img width="390" alt="Screenshot 2020-10-07 at 11 18 34" src="https://user-images.githubusercontent.com/45729/95280050-0f00fa80-088f-11eb-8406-573aa52d3221.png">

**Comment by smonff** [comment]
It's almost for sure you need a `<meta />` tag for the [`viewport`](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) in the `<head />` of your template.

Something like: 

        %= t 'meta', name => 'viewport', content => 'width=device-width, initial-scale=1'

...should do the trick. Note it will have some side effects like the fancy `#mojo-fun` header will be a bit broken, but overall, all the text will be much more readable on phones, plus the side-menu will stay on top.

![photo_2020-10-07_12-22-32](https://user-images.githubusercontent.com/1219097/95319208-e03b5200-0897-11eb-98fe-87358ef71805.jpg)

This was taken from a Samsung A6.

**Comment by kberov** [comment]
May be the Bulma CSS framework is suitable. It uses flexbox and does not require JS.
https://bulma.io/documentation/columns/
I would gladly use it in my apps together with jQuery

**Comment by kraih** [comment]
We already use Bootstrap for mojolicious.org, using something else for the built-in templates would be weird.

**Comment by kraih** [comment]
I believe this is finished.
