### ISSUE TITLE
Make under actions promise aware

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1309]
The [old way](https://github.com/mojolicious/mojo/blame/3123cf5fd4d8131ac9d157dddd847308bdf33861/lib/Mojolicious/Guides/Routing.pod#L617-L625) for making under actions async was really clunky and it's actually very easy to use promises instead. [Here](https://gist.github.com/kraih/6042f42817713c0dfe01a8adb86fd8ad) is a partial patch if someone wants to finish the feature. It needs full test coverage for resolve/reject cases, and the documentation in the routing guide needs to be updated. And there is still the open question of what to do with the promise value.

**Comment by kraih** [comment]
Possible complete solution as discussed on IRC. https://gist.github.com/kraih/3520041e06f8d26c1e25eef0c17a006d

**Comment by kraih** [comment]
Resolving to false to break the dispatch chain is super clunky though.

**Comment by pink-mist** [comment]
Yeah, I definitely think resolve should always continue, and you should need to reject to break

**Comment by kraih** [comment]
Closing this issue for now since no acceptable solution has been found.
