### ISSUE TITLE
Routes problem - (:id) placeholder

### ISSUE THREAD

**Issue by Mazian** [mojolicious/mojo#1312]
* Mojolicious version: 7.88 (and up - to current 8.11)
* Perl version: v5.26.1
* Operating system: Ubuntu 18.04

### Steps to reproduce the behavior
I used format for routes:
```
    $r->route('/award(:award_id)')->to('award#show');
```
Routes are in a separate file `lib/Routes.pm` and it contains 500 different routes.

_We are using a non-standard system (no is `/:object/:action/:id`)
There may be urls of type `/award64content` and other._

In new versions mojolicious these routes stopped working.
It turned out that the brackets around (:id) placeholder are no longer defined.

The [documentation](https://github.com/mojolicious/mojo/blob/master/lib/Mojolicious/Guides/Routing.pod) found examples of the format of recording routes without brackets:
```
/user/:action/:id
```

### Expected behavior
How can I get support for the format of the routes as it was - and with brackets?

### Actual behavior
In version 7.88 (and up) route work ONLY widthout brackets

```
    $r->route('/award:award_id')->to('award#show');     # worked 
    $r->route('/award:(award_id)')->to('award#show');   # worked up to version 7.87, not worked 7.88 (and up)
```

**Comment by frankiejol** [comment]
@Mazian I had this problem too, I worked it around changing the default patterns and reparsing the routes:

```
my $routes = app->routes->children;
for my $route (@$routes){
    $route->pattern->quote_start('(');
    $route->pattern->quote_end(')');
    $route->pattern->parse($route->pattern->unparsed);
}
```

**Comment by Mazian** [comment]
This is exactly what you need!
Thank you!
