### ISSUE TITLE
Feature Request: Mojo::Collection - shift, unshift, push, pop

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1320]
It could be nice to have these as methods on Mojo::Collection. I had an example recently where I had to break the nice flow of `->`:

```
my $array = $collection->arrays->flatten->to_array;
unshift @$array, 'item';
```

It would be great to be able to do something like:

`my $array = $collection->arrays->flatten->unshift('item')->to_array;`

**Comment by kiwiroy** [comment]
There is this pattern:
```perl
my $array = $collection->arrays->flatten->tap(sub { unshift @$_, 'item' })->to_array;
```

**Comment by srchulo** [comment]
ah, that is better than what I was doing before, thanks! I still think it would make sense to have common operations like `shift`, `unshift`, `push`, and `pop` be actual methods on the Collection.

**Comment by s1037989** [comment]
I've also had situations where I've needed to break the nice flow and have often wished for this.

**Comment by kiwiroy** [comment]
The current methods on `Mojo::Collection` all return copies of the collection with the transformation applied, whereas the request above appears like an **i**n place transformation is desired, though that might be side effect of the current situation.

For [example](https://github.com/kiwiroy/mojo/compare/collection-array-funcs) here is `unshift`/`unshift_i`, since the examples above use `unshift`.

**Comment by kraih** [comment]
I'm vetoing this feature for now, since the two proposed solutions had very substantial flaws. Please try thinking more about what the actual use cases are for each method you're adding before sending more pull requests. Maybe try having a discussion about it on IRC.

**Comment by kraih** [comment]
If you're sure you've found the right semantics, please provide two independent use cases for each method that you believe to be strong.

**Comment by kraih** [comment]
Does not look like there is much support for this feature.

**Comment by kraih** [comment]
Doesn't look like this proposal got any more support. Thanks everyone.
