### ISSUE TITLE
Mojo::DOM placing implied closing tag in wrong position

### ISSUE THREAD

**Issue by rohanc** [mojolicious/mojo#1322]
I think I've found a bug in the Mojo::DOM parser. In my test HTML below, Mojo::DOM seems to be inserting the implied `</option>` tag in the wrong location. It doesn't happen when I provide the closing tags myself.

To my knowledge, closing `</option>` tags are optional with `<select>` blocks, at least in HTML5, so I think my input code still counts as well-formed HTML.

Mojolicious version: 6.62
Perl version: 5.26.1
Operating system: Ubuntu 16.04 Linux

### Steps to reproduce the behavior

Code
```
use v5.24;
use lib::abs ("../lib","../local/lib/perl5");
use Mojo::DOM;

my $input = <<"END";
<!DOCTYPE html>
<html>
   <head>
      <title>test</title>
   </head>
   <body>
      <select>
         <option>apple
         <option>pear
      </select>
      <textarea></textarea>
   </body>
</html>
END

my $dom = Mojo::DOM->new->parse($input);
say $dom->to_string;
```

### Expected behavior

I expect to see the closing <textarea></textarea> section after the </select> tag, but it's being inserted before it.

### Actual behavior

Output is:

```
<!DOCTYPE html>
<html>
   <head>
      <title>test</title>
   </head>
   <body>
      <select>
         <option>apple
         </option><option>pear
      
      <textarea></textarea>
   </option></select></body>
</html>
```

**Comment by s1037989** [comment]
> Mojolicious version: 6.62

This version is two _major_ versions behind and this bug report is unlikely to be considered.  Can you run your test on the latest version of Mojolicious?  Your Perl and OS are ok.

**Comment by rohanc** [comment]
Thanks for the heads up. Tried again with Mojolicious 8.12, results unchanged.

**Comment by kraih** [comment]
The [HTML spec](https://html.spec.whatwg.org/) decides if this is a bug.

**Comment by rohanc** [comment]
Fair enough. The [option tag spec](https://html.spec.whatwg.org/#the-option-element) says:

> An option element's end tag can be omitted if the option element is immediately followed by another option element, or if it is immediately followed by an optgroup element, or if there is no more content in the parent element.

**Comment by kraih** [comment]
Ok, i think we can consider this a bug.

**Comment by marked** [comment]
I'm poking at this.  Question- is it undesirable to borrow a DOM parser from CPAN?  Presumably the current methods list would be kept the same.

**Comment by Grinnz** [comment]
Yes, that would be undesirable for a multitude of reasons.

**Comment by vyuh** [comment]
Commenting the line (https://github.com/mojolicious/mojo/blob/4b70da04b60073dc2a5293afabbba70cb85d6f14/lib/Mojo/DOM/HTML.pm#L190)
causes the DOM to be built correctly for this particular case, and `to_string` produces desired result.
But it Causes one test (https://github.com/mojolicious/mojo/blob/4b70da04b60073dc2a5293afabbba70cb85d6f14/t/mojo/dom.t#L1886)
in `t/mojo/dom.t` to fail.

The commented line earlier prevented the `select` tag from being closed when `</select>` is encountered.

There are elaborate rules to follow while building the DOM tree inside `select` element
(https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inselect).
Doing it properly might be a ton of work.

I tested on a recent fork of this repo.

    $ git clone $github_vyuh_mojo_repo
    $ cat mojo_issue_1322/mojo_issue_1322.pl 
    use v5.24;
    use Mojo::DOM;
    
    my $input = '<!DOCTYPE html><title>test</title><select><option>apple<option>pear</select><textarea></textarea>';
    
    my $dom = Mojo::DOM->new->parse($input);
    say $input;
    say $dom->to_string;

    $ PERL5LIB=mojo/lib perl mojo_issue_1322/mojo_issue_1322.pl
    <!DOCTYPE html><title>test</title><select><option>apple<option>pear</select><textarea></textarea>
    <!DOCTYPE html><title>test</title><select><option>apple</option><option>pear</option></select><textarea></textarea>

    $ PERL5LIB=mojo/lib prove mojo/t/mojo/dom.t
    mojo/t/mojo/dom.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 1/767 subtests 
    
    Test Summary Report
    -------------------
    mojo/t/mojo/dom.t (Wstat: 65280 Tests: 767 Failed: 1)
      Failed test:  672
      Non-zero exit status: 255
      Parse errors: No plan found in TAP output
    Files=1, Tests=767,  1 wallclock secs ( 0.11 usr  0.00 sys +  0.49 cusr  0.02 csys =  0.62 CPU)
    Result: FAIL
