### ISSUE TITLE
Use subroutine signatures in all documentation examples

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1324]
It's 2019 and that means it's time to take the next step. All our documentation examples need to be converted to using [subroutine signatures](https://mojolicious.org/perldoc/perlsub#Signatures), and a new signatures section needs to be added to our [documentation conventions](https://mojolicious.org/perldoc#CONVENTIONS).

**Comment by Tekki** [comment]
Is it correct like this?
```
#!/usr/bin/env perl
use Mojolicious::Lite -signatures;

get '/' => sub ($c) {
  $c->render(text => 'Hello World!');
};

app->start;
```

**Comment by s1037989** [comment]
Will `-signatures` become default in Mojo::Base?

**Comment by Grinnz** [comment]
It requires perl 5.20 and is not necessarily compatible with code written without them, so I doubt that will happen anytime soon.

**Comment by kraih** [comment]
It's been a year and not much happened, maybe this is not what the community wants after all.
