### ISSUE TITLE
Feature Request: Support gzipping static files in Mojolicious::Static

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1327]
It would be nice if Mojolicious::Static could gzip files, and allow support for a minimum/maximum file size to gzip. This plugin exists:

https://metacpan.org/pod/Mojolicious::Plugin::GzipStatic

But it gzips the file in the [after_static](https://metacpan.org/pod/Mojolicious#after_static) hook, meaning that the file is processed twice.

**Comment by kraih** [comment]
👎 That's very inefficient. Static files should be pre-processed only once.

**Comment by srchulo** [comment]
Do you mean the modules is inefficient, or gzipping static files at all would be inefficient?

**Comment by kraih** [comment]
I'm saying there is already [plugins](https://metacpan.org/pod/Mojolicious::Plugin::AssetPack) that do this much better than we could.

**Comment by srchulo** [comment]
But that's for pre-processing, such as minifying/combining assets. I'm talking about gzipping content for a client that supports it. 

It doesn't seem like Mojolicious::Plugin::AssetPack would help with gzipping content?

**Comment by kraih** [comment]
I don't see this happing as part of Mojolicious. Plugins already cover this very well.
