### ISSUE TITLE
Feature request: support min and maybe max size for compress in Mojolicious::Renderer

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1328]
In Molicious::Renderer there is support for compressing all dynamic content:

https://metacpan.org/pod/Mojolicious::Renderer#compress

It would be nice if compress supported a minimum size before compressing, and maybe a maximum.

**Comment by kraih** [comment]
You're not explaining why you want this feature. Perhaps with some data backing up the request?

**Comment by srchulo** [comment]
The reason is because compressing some smaller requests can actually make them larger, and also compressing requests below a certain size can be slower than not compressing at all. Here's a question on webmasters.stackexchange quoting some points from the Akamai CDN:

https://webmasters.stackexchange.com/questions/31750/what-is-recommended-minimum-object-size-for-gzip-performance-benefits

Here's a recommendation from Google mentioned there:

> Note that gzipping is only beneficial for larger resources. Due to the overhead and latency of compression and decompression, you should only gzip files above a certain size threshold; we recommend a minimum range between 150 and 1000 bytes. Gzipping files below 150 bytes can actually make them larger.

And here is why Akamai says that they only compress when a response is above 860 bytes:

> The reasons 860 bytes is the minimum size for compression is twofold: (1) The overhead of compressing an object under 860 bytes outweighs performance gain. (2) Objects under 860 bytes can be transmitted via a single packet anyway, so there isn't a compelling reason to compress them.

Nginx also supports a [minimum length before gzipping](https://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_min_length), as does [Apache](http://www.thern.org/projects/mod_gzip) (see mod_gzip_minimum_file_size ).

**Comment by kraih** [comment]
👍 Seems reasonable.

**Comment by kraih** [comment]
Thanks, resolved by #1331.
