### ISSUE TITLE
Mojo::Utils::decode inclusion in an apparently working Mojo::DOM-based script seems to result in run-time error and document loss

### ISSUE THREAD

**Issue by daveaiello** [mojolicious/mojo#1332]
* Mojolicious version: 8.12
* Perl version: 5.22.1
* Operating system: Ubuntu 16.04 (4.4.0-139-generic #165-Ubuntu SMP)

### Steps to reproduce the behavior

I am using Mojo::DOM and Mojo::Util::decode to identify and print out phrases in HTML documents (meaning strings of text between selected tags). Prior to including Mojo::Util::decode, I was using Mojo::DOM only, and what was happening was embedded HTML entities (such as `&trade;` and `&nbsp;`) were being converted into characters rather than passed along as written.

The current version of the code is as follows:

```
        $dom = Mojo::DOM->new(Mojo::Util::decode('UTF-8', $page->text));

    ##########
    #
    # Break down the Body into phrases. This is done by listing the tags and tag combinations that
    # surround each block of text that we're looking to capture.
    #
    ##########

        print FILE "\n\t### Body\n\n";        

        for my $phrase ( $dom->find('h1, h2, h2 b, h3, p, p strong, span, a, caption, th, li, li a')->map('text')->each ) {

            print_phrase($phrase); # utility function to write out the phrase to a file

        }
```

### Expected behavior

I expected the entities to be passed through as written.

### Actual behavior

Since the introduction of Mojo::Util::decode('UTF-8', $page->text), I am seeing the following error on standard error when the script is run:

`Use of uninitialized value $_[0] in string at /usr/local/share/perl/5.22.1/Mojo/DOM/HTML.pm line 102.`

This error is not occurring for every phrase. But it's occurring intermittently, with more of the same error being reported as a larger number of HTML pages are parsed by the code shown above.

In addition, I am seeing entire HTML documents omitted from the file being written by the print_phase subroutine. This renders the code as currently written useless for its purpose.

One thing I tried to do was correlate the number of "Use of uninitialized value $_[0] in string" errors to the number of HTML documents omitted from the file output. In one hand-count I did, the number of errors that appeared did not equal the number of HTML documents omitted.

**Comment by Tekki** [comment]
1/2 of an answer: You can only call `decode 'UTF-8'` on a string that contains valid UTF-8. If it doesn't, for example because it is already converted to Perl characters, it will return `undef`.

**Comment by Grinnz** [comment]
You cannot test the encoding of a string reliably. You must know what encoding your variables are in at each point. So it starts with where $page comes from.

**Comment by Grinnz** [comment]
I would also suggest that this discussion is better suited for the support channels.

**Comment by daveaiello** [comment]
Good idea @Grinnz. Thanks again for your feedback.

I don't think this is a bug in Mojolicious. I think this is a side-effect of the quality of the data I'm processing.
