### ISSUE TITLE
Bug in session handling when using additional signed_cookies?

### ISSUE THREAD

**Issue by wneessen** [mojolicious/mojo#1333]
* Mojolicious version: 8.12
* Perl version: 5.28.1 
* Operating system: MacOS X 10.14.3

### Steps to reproduce the behavior
Write a Mojo web application and use session cookies. I define the use of session cookies like this and it works fine:
```perl
## Session settings
$self->secrets([$secret->{sessionSecret}]);
$self->sessions->cookie_name($config->{productNameShort} . '_sess');
$self->sessions->secure($config->{sessionSecureFlag});
$self->sessions->default_expiration($config->{sessionExpiration});
```

At some other part in my code I also set a signed_cookie with no "HTTPonly" flag, so I can access it with JS code. 
```perl
$self->signed_cookie(
	'browserId' => $browserIdB64,
	{ secure => 1, httponly => 0, expires => time + $self->config->{browserIdExpiration} }
);
````

This also works fine in most cases. But a problem occurs when I go ahead an delete either of those cookies. For example the session cookie but I leave the signed "browserId" cookie in my browser active.

### Expected behavior
I would expect that the next call would reset the session cookie and issue a new one.

### Actual behavior
But this doesn't happen. No new session cookie is created which i. e. keeps the CSRF token from working, as the CSRF token, that is written into the form via the csrf_field helper, relies on the corresponding CSRF to also be in the session an be read from there. If I manually delete the session cookie, no new session cookie is created and therefore no CSRF token is ever written and any CSRF token validation fails.

**Comment by jhthorsen** [comment]
What do you mean about "deleting" the cookie? If you delete the data structure on the server, then nothing will happens, since the browser will just resend the cookie it has.

Maybe these resources can help you out:

- https://mojolicious.org/perldoc/Mojolicious/Controller#session
- https://stackoverflow.com/questions/5285940/correct-way-to-delete-cookies-server-side

This issue sounds like a question and not a bug report. Maybe you should use one of our support channels instead?

- https://mojolicious.org/perldoc/Mojolicious/Guides/FAQ#SUPPORT

**Comment by wneessen** [comment]
No, I delete the cookie in the browser (DevTools -> Application -> Cookies), but I was able to figure the error in the app. I have a API login route, in which I don't want to return a Set-Cookie header. This seems to interfere in this specific case.

```perl
$self->app->hook(
	before_render => sub {
		shift->res->on(
			progress => sub {shift->headers->remove('Set-Cookie')}
		)
	}
)
```

So it's not a Mojo issue, but an App issue. You can close this ticket, I will figure out a fix. Sorry for the inconvenience.
