### ISSUE TITLE
signed_cookie should sign cookie name

### ISSUE THREAD

**Issue by oschwald** [mojolicious/mojo#1335]
* Mojolicious version: 8.12
* Perl version: n/a
* Operating system: n/a

### Steps to reproduce the behavior

When using `signed_cookie`, only the cookie value is signed.

### Expected behavior

The HMAC should include both the cookie name and value. The reason for this is that it prevents the user from tampering with the cookies by using the value of one cookie for another cookie. For instance, some sites have multiple session-like cookies, one for keeping track of unauthenticated users and another for authenticated users. With the current signing, it may be possible to use the unauthenticated cookie as the authenticated cookie to gain access to the site.

### Actual behavior

Only the value is signed:

https://github.com/mojolicious/mojo/blob/0169b7d4f6a11223f3619043c7c824e49fb5984e/lib/Mojolicious/Controller.pm#L242

**Comment by Grinnz** [comment]
This doesn't really make sense to me. The cookie is found by its name. If another cookie's value is substituted it would only be valid if it was signed with the same secret by your application.

**Comment by oschwald** [comment]
Most HMAC cookie implementations I have seen sign both the cookie name and the value. The resulting cookie looks similar, e.g., `<name>=<value>--<signature>`. However the signature is the signature for both the name and the value, often for the string `<name>=<value>`.

My point about substituting cookies is not that you can inject a cookie that has not been signed, but rather than you can take another signed cookie for the same site but with a different name and use it. For instance, if you had `unauth_session` and `auth_session` cookies, you could take a value for `unauth_session` and use it for `auth_session`. With the current signing, the site implementor would need to make sure those two cookies never had overlapping values (say if it was encoded JSON) or they would need to sign them with two separate keys, ignoring Mojo's signing.

**Comment by oschwald** [comment]
The code change I am requesting is basically something like changing the line quoted above to:

```
  my $checksum = Mojo::Util::hmac_sha1_sum("$name=$value", $self->app->secrets->[0]);
```

or something similar.

This, of course, will have the effect of rendering cookies signed with the old version invalid.

**Comment by kraih** [comment]
Thanks, that does seem like a reasonable proposal.
