### ISSUE TITLE
added dependency on clone in Mojo::Promise 

### ISSUE THREAD

**Issue by greencoloured** [mojolicious/mojo#1337]
I just upgraded and ran into the issue: https://github.com/mojolicious/mojo/issues/1275 and was somewhat confused by the undocumented breaking change. 

But while looking at the commit: https://github.com/mojolicious/mojo/commit/5b440c453c44972d758492924074af0a34eff703#diff-27bd5e0ace07b04f2ba7f5e7ec0115c1

I also noticed that there was another change introduced. 

As per promises A+ `Mojo::Promise` supports thenable objects, however the above change means that if the first promise passed isn't a Mojo::Promise then `all` and `race` wont work.

Here is an example of a valid code in v7.94 that fails on 8.11

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use feature 'say';

use Mojo::IOLoop;
use Mojo::Promise;
use Promises "deferred", "backend" => ["Mojo"];

# thenable object
my $p = deferred;
$p->then(sub { say "resolved: p" });

# mojo promise
my $mp = Mojo::Promise->new;
$mp->then(sub { say "resolved: mp" });

Mojo::IOLoop->timer(2 => sub { $p->resolve });
Mojo::IOLoop->timer(1 => sub { $mp->resolve });

Mojo::Promise->all($p, $mp)->then(sub { say "done" });

Mojo::IOLoop->start;
```

**Comment by greencoloured** [comment]
I'm not sure what you mean. You should be fine having an `ioloop` attribute according to the [Promises A+ Specification](https://promisesaplus.com/), the `Mojo::IOLoop` object would just be combined in any resolution chain throught the `then` method, though obviously Mojo::IOLoop would have to be allowed to work to be compatible. 

The point of the A+ spec is to define interoperable promises. It should be possible to combine promises of one type with another, and it's up to them how ther are imlemented as long as they have somewhat compatible `then` functions.

As things stand `Mojo::Promise` does indeed work at least to some degree with other Promises and thenable objects. Here's an example:

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use feature 'say';

use Mojo::IOLoop;
use Mojo::Promise;
use Promises 'deferred'; #, 'backend' => ['Mojo'];

# some thenable package
package T {
	sub new { bless { then => [] }, shift }
	sub done { $_[0]{done}++; while (my $cb = shift @{$_[0]{then}}) { $cb->() } }
	sub then { push @{$_[0]{then}}, $_[1]; $_[0]->done if $_[0]{done}; $_[0] }
}

my ($p, $p2, $t, $mp, $mp2) = (deferred, deferred, T->new, Mojo::Promise->new, Mojo::Promise->new);

# Thenable
$t->then(sub { say "finish: t" });

# Mojo Promise
my $_mp2 = $mp2->then(sub { $t })->then(sub { say "finish: mp2" });

# A+ promise
my $_p2 = $p2->then(sub { $_mp2 })->then(sub { say "finish: p2" });

# Mojo Promise
my $_mp = $mp->then(sub { $_p2 })->then(sub { say "finish: mp" });

# A+ promise
my $_p = $p->then(sub { $_mp })->then(sub { say "finish: p" });

my @order = map { int(rand(5))+1 } 1..5;

Mojo::IOLoop->timer(shift @order => sub { say "resolve: p"; $p->resolve });
Mojo::IOLoop->timer(shift @order => sub { say "resolve: p2"; $p2->resolve });
Mojo::IOLoop->timer(shift @order => sub { say "resolve: t"; $t->done });
Mojo::IOLoop->timer(shift @order => sub { say "resolve: mp"; $mp->resolve });
Mojo::IOLoop->timer(shift @order => sub { say "resolve: mp2"; $mp2->resolve });

Mojo::IOLoop->start;
# Finish Order: $t, $mp2, $p2, $mp, $p
```

**Comment by kraih** [comment]
`all` and `race` are not actually part of the Promises/A+.

**Comment by kraih** [comment]
Think we can conclude that there are no bugs here.
