### ISSUE TITLE
Test::Mojo bug with emit_chain-type hooks

### ISSUE THREAD

**Issue by jrubinator** [mojolicious/mojo#1341]
* Mojolicious version: 8.13
* Perl version: 5.18.2 and 5.24.1
* Operating system: Centos 6.10

### Steps to reproduce the behavior
Something with `Test::Mojo` interfering with `emit_chain` type events registered through `Test::Mojo` after its first request, so that they are completely impossible to register. I verified `around_dispatch` and `around_action`, with the former demonstrated below.

```
use strict;
use warnings;
use feature 'say';

{
    package MyApp;
    use Mojolicious::Lite;

    hook before_routes   => sub { say "app before routes" };
    hook around_dispatch => sub { my ($next, $c) = @_; say "app around dispatch"; $next->(); };

    get '/'  => sub { shift->render(status => 200, text => 'called') };
    get '/a' => sub { shift->render(status => 200, text => 'called') };
}

use Test::Mojo;
my $t = Test::Mojo->new('MyApp');

# Output is (as expected):
# app around dispatch
# app before routes
# ok 1 - GET /
$t->get_ok('/');
# ^ If we don't make this call first, the output below would include "test around dispatch"

$t->app->hook( before_routes   => sub { say "test before routes" } );
# NEVER CALLED!
$t->app->hook( around_dispatch => sub { my ($next, $c) = @_; say "test around dispatch"; $next->(); });
# Output indicates around_dispatch is not correctly propagated
# for *all of the following*
# app around dispatch
# app before routes
# test before routes
# ok * - GET /
# ok * - exact match for content

# 1) using the same Test::Mojo instance
$t->get_ok('/')->content_is('called');

# 2) using a new Test::Mojo instance
Test::Mojo->new('MyApp')->get_ok('/')->content_is('called');

# 3) Explicitly creating a a new MyApp
Test::Mojo->new(MyApp->new)->get_ok('/')->content_is('called');

# 4) Hitting an entirely different endpoint
Test::Mojo->new(MyApp->new)->get_ok('/a')->content_is('called');
```

### Expected behavior
Each of cases 1 - 4 should output

> app around dispatch
> test before dispatch
> app before routes
> test before routes

### Actual behavior
When running the file above, each step only prints out

> app around dispatch
> app before routes
> test before routes

omitting the "test before dispatch line"

**Comment by jberger** [comment]
If I'm reading this correctly what you're saying is that you can't add hooks after the first dispatch? If that is the TL;DR then I'm not sure that that's a bug as I know lots of things in the router get finalized after the first dispatch. I couldn't tell you offhand if hooks are among them but I wouldn't be surprised.

**Comment by jberger** [comment]
Here's a note commenting on how the router can't be changed after the first request is dispatched. https://mojolicious.org/perldoc/Mojolicious/Guides/Routing#Rearranging-routes

**Comment by kraih** [comment]
Yea, you're not supposed to add hooks once the first request has arrived.

**Comment by jrubinator** [comment]
That's fair. Do you think it would be worthwhile to add a line somewhere near the hooks documentation indicating something similar?

I didn't find the note about not being able to modify routes after the first request, plus right now the guide says:

> Hooks operate outside the routing system
