### ISSUE TITLE
link to the blog from the wiki, main documentation

### ISSUE THREAD

**Issue by karenetheridge** [mojolicious/mojo#1346]
The wiki (https://github.com/mojolicious/mojo/wiki)
has no links to the blog (https://mojolicious.io/blog) where much additional documentation and help can be found.

It doesn't look like there are any links to the blog from the source (e.g. Mojolicious::Guides::FAQ, QuickStart etc) either.

**Comment by kraih** [comment]
That blog is not actually an official resource of the Mojolicious project. And everyone can edit the wiki, including you, so feel free.
