### ISSUE TITLE
Unregistered dependencies Digest::MD5 and IO::Compress::Gzip

### ISSUE THREAD

**Issue by Chaz6** [mojolicious/mojo#1349]
* Mojolicious version: 8.15
* Perl version: v5.16.3
* Operating system: CentOS 7.6

### Steps to reproduce the behavior
Attempt to install Mojolicious from cpan (using `cpanm`) without the Digest::MD5 and IO::Compress::Gzip modules installed.

### Expected behavior
Mojolicious installs successfully.

### Actual behavior
The installation fails because Digest::MD5 and IO::Compress::Gzip are not automatically installed.

```
$ cpanm Mojolicious
[..] Can't locate Digest/MD5.pm in @INC [..]
$ cpanm Digest::MD5 && cpanm Mojolicious
[..] Can't locate IO/Compress/Gzip.pm in @INC [..]
$ cpanm IO::Compress::Gzip && cpanm Mojolicious
[..] Successfully installed Mojolicious-8.15 [..]
```

**Comment by shadowcat-mst** [comment]
Those are supplied by perl5 core.

You're using an old RH derived distro where you need to install 'perl-core' rather than 'perl' to get a full perl install.

This is a bug in your distro, not in Mojolicious, and has since been corrected upstream by the RH perl maintainer.

**Comment by jberger** [comment]
Thanks mst.
