### ISSUE TITLE
Documentation bug: query method argument

### ISSUE THREAD

**Issue by yuki-kimoto** [mojolicious/mojo#1365]
Documentation bug: query method argument

https://github.com/mojolicious/mojo/blob/v8.17/lib/Mojolicious/Controller.pm#L813

```
# Current
# "/list?q=mojo&page=2" if current request was for "/list?q=mojo&page=1"

$c->url_with->query([page => 2]);
```

This is maybe

```
$c->url_with->query({page => 2});
```

because this is replace example.

**Comment by CandyAngel** [comment]
Thanks for reporting, this example was missed when the query behaviour was changed to be more intuitive in 8.0. Nice catch!
