### ISSUE TITLE
Feature Request: Support relative template paths for include and extends helpers

### ISSUE THREAD

**Issue by tim-2** [mojolicious/mojo#1367]
For example if you have the following templates:
```
templates/user/profile/edit.html.ep
templates/user/profile/_form.html.ep
```

It would be nice if you could do:
`%= include './_form'`
instead of
`%= include 'user/profile/_form'`
in _edit.html.ep_

Use case:
I have many small reusable include templates in my project and with this feature I could safely change a directory name without having to change the path of every include statement.

**Comment by Grinnz** [comment]
`.` implies the current working directory, which is not something that should be supported. For "current file's directory" it would be better to have a helper, so something like `%= include current_dir->child('_form')`

**Comment by kraih** [comment]
@Grinnz It's not really a directory at all though, just a name if the file is in the `DATA` section.

**Comment by kraih** [comment]
After two years without progress i believe this feature proposal failed. Thanks everyone.
