### ISSUE TITLE
Plugin generator missing name validator

### ISSUE THREAD

**Issue by hurricup** [mojolicious/mojo#1368]
* Mojolicious version: 8.17
* Perl version: 5.26.2
* Operating system: linux

It's possible to run
`mojo generate plugin "foo bar"`

Pretty artificial case, but app generator can handle this

**Comment by jhthorsen** [comment]
I’m not sure if this case is common enough to be fixed.

**Comment by hurricup** [comment]
true. Just pointing to inconsistency/unsafety

**Comment by kraih** [comment]
Resolved by removing the check form the app generator. 😉
