### ISSUE TITLE
Remove config default value

### ISSUE THREAD

**Issue by jberger** [mojolicious/mojo#1369]
Having a stash default "config" which pointed to the app's config was a backcompat measure ages ago. Most users use the config helper now. It is awkward that the default is only loaded by the config loader plugins and makes for unexpected action-at-a-distance since that default does not exist if you load configuration in other ways. It should be removed in favor of the config helper and/or app accessor.

Mitigations for affected users: 
Users are encouraged to switch to using `config` in templates rather than `$config`. Projects wishing to keep the existing behavior may implement the default in the project themselves by adding `$app->defaults(config => $app->config);` to the application startup after loading their configuration.

**Comment by kraih** [comment]
Deprecation is now in effect. https://github.com/mojolicious/mojo/compare/baf97a0576fa...917d61d8e558

**Comment by kraih** [comment]
This is a test comment to see if linking to a discussion like #1625 works.

**Comment by kraih** [comment]
Done, as part of the 9.0 branch.
