### ISSUE TITLE
The 'num' validator check not behaving according to documentation

### ISSUE THREAD

**Issue by akarelas** [mojolicious/mojo#1375]
* Mojolicious version: 8.18

### Steps to reproduce the behavior

Run this test:

```
use Test::More;
use Mojolicious::Validator;

my $validator = Mojolicious::Validator->new;
my $v = $validator->validation;

$v->input({pos => 5, neg => -5, zero => 0});
$v->required($_)->num(undef, undef) foreach (qw/ pos neg zero /);

ok $v->is_valid('pos'), 'positive non-fractional numbers pass';
ok $v->is_valid('zero'), 'non-fractional numbers equal to zero pass';
ok $v->is_valid('neg'), 'negative non-fractional numbers pass';

done_testing();
```

The third test (negative numbers) fails, even though the number (-5) conforms to the [spec of num](https://metacpan.org/pod/Mojolicious::Validator#num) as described in the documentation ("non-fractional number").

### Expected behavior

Either the documentation should state that omitting the min parameter makes min = 0, or the third test ('negative') should pass. Because if setting max to undef means no max limit is enforced (as is the case), one would automatically assume that setting min to undef would mean no min limit will be enforced either.

### Actual behavior

The third test failed (-5 didn't pass the `num` test)

**Comment by akarelas** [comment]
Related:

`num(-10, 10)` will not let `-5` pass either.

**Comment by sleaux-meaux** [comment]
num() doesn't appear to accept negative integer values for checking:

https://github.com/mojolicious/mojo/blob/7d8920fa46cc74c8740c402a3c871172cfecc019/lib/Mojolicious/Validator.pm#L50-L54

You use Mojolicious::Validator->add_check to employ a different method that does.

**Comment by akarelas** [comment]
I'm perfectly fine with that behaviour. In that case however, the [documentation of num](https://metacpan.org/pod/Mojolicious::Validator#num) needs to be modified. Now it says `String value needs to be a non-fractional number and if provided in the given range`, but -5 **is** a non-fractional number and in the given range (-10, 10).

Either the doc has omitted something and needs to be fixed, or the code does.

**Comment by akarelas** [comment]
Issue was fixed in a recent release.
