### ISSUE TITLE
Since 8.19 (a7019a0b), evaluating an Exception in string context gives message string with trailing newline

### ISSUE THREAD

**Issue by AdamWill** [mojolicious/mojo#1385]
* Mojolicious version: 8.20
* Perl version: 5.30.0
* Operating system: Fedora Rawhide

### Steps to reproduce the behavior
Run the openQA test suite with Mojolicious 8.19 or later.

### Expected behavior
The tests should pass.

### Actual behavior
The tests fail. Specifically this one:

    is(
        OpenQA::Files->verify_chunks($t_dir => $copied_file),
        'Can\'t verify written data from chunk',
        'Verify chunks fail'
    );

The return from that `verify_chunks` call, in this case, is an instance of `Mojo::Exception`, and this check is evaluating it in string context and expecting it to be 'Can\'t verify written data from chunk'. What it actually is, though, is that string but with a newline on the end.

That's because of a7019a0b53c04077b8535deb0383db6c61f31690 , which showed up in Mojo 8.19. Before that commit, `to_string` (which is the method that gets called when you evaluate an Exception in string context) had this at the start:

    my $str = $self->message;
    return $str unless $self->verbose;

    $str .= "\n" unless $str =~ /\n$/;
    [MORE STUFF MORE STUFF]
    return $str;

That commit, however, removed the second line, so currently the code just looks like this:

    my $str = $self->message;
    $str .= "\n" unless $str =~ /\n$/;
    [MORE STUFF MORE STUFF]
    return $str;

that is, it *always* adds a newline to the message unless it already ends with one, whereas before it didn't do that unless it was in 'verbose mode'.

As I read the code over time, the original intention was for the newline to be padding between the error message and any context or backtrace that is printed. But with the current code after all the verbose-related changes, even if there is no context (no `$self->line`) and no backtrace (no `$self->frames`), the newline *still* gets added, so you just get the message with an added newline and nothing else.

**Comment by kiwiroy** [comment]
Also jhthorsen/mojolicious-plugin-openapi#132

**Comment by kraih** [comment]
This is not a bug, this is a bug fix.

**Comment by kraih** [comment]
How would it make sense for newlines not to be normalized in the error message?

**Comment by AdamWill** [comment]
I mean, doesn't it depend what you mean by "normalized"? That's a bit of a subjective term. Normalized in terms of what? What's normal here?

If you think this is the right way for things to be, I guess that's fine? But it's a change from how things worked before, and it is not clear from the overall context of this commit that it was actually intended. The whole sequence of commits is a bit tricky to understand, since it seems to involve removing this "verbose mode" then putting it back again. So I figured I'd just file an issue so you can check whether it's intentional and desired or not.

**Comment by kraih** [comment]
When you `die 'foo';` then Perl appends a newline, when you `die "foo\n"` it does not. Newline at the end of a stringified exception is the normal case.

**Comment by kraih** [comment]
There is a problem with error messages ending in a newline though. We can't modify those without breaking common flow control patterns. So we'll have to change that at least. https://github.com/mojolicious/mojo/compare/d6eca913536e...256f313f5c2a

**Comment by kraih** [comment]
This should be resolved.
