### ISSUE TITLE
Feature Request: Add get_params to Mojo::Parameters

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1388]
I think it would be nice to be able to get multiple parameters at once from [Mojo::Parameters](https://mojolicious.org/perldoc/Mojo/Parameters). Currently to do this, I do:

```
my ($a, $b, $c) = @{$params->to_hash}{qw/a b c/};
```

I think it would be nice to be able to do:

```
my ($a, $b, $c) = $params->get_params(qw/a b c/);
```

**Comment by kraih** [comment]
This used to exist before the removal of `wantarray` from Mojolicious. Now we are very very cautious with new additions to the param APIs.

**Comment by srchulo** [comment]
Oh, I didn't know that existed before. I wonder if this would be clearer since it would be a method named `get_params` instead of implied by `wantarray`?

And by CVEs do you mean Common Vulnerabilities and Exposures? Has this happened before with the params API? I would think that this wouldn't cause any more CVEs than:

```
my ($a, $b, $c) = @{$params->to_hash}{qw/a b c/};
```

or

```
my ($a, $b, $c) = ($params->param('a'), $params->param('b'), $params->param('c'));
```

Does that seem correct? I'm sure I'm missing something if you're warning against CVEs.

**Comment by Tekki** [comment]
If you use [postfix deref](https://perldoc.pl/perlref#Postfix-Dereference-Syntax) it looks similar to what you asked for at the beginning and doesn't need a single change.
```
my ($a, $b, $c) = $params->to_hash->@{qw/a b c/};
```

**Comment by srchulo** [comment]
@Tekki That's a good point. I need to remember that postfix deref exists :) I think that's a good solution, although personally I would still prefer a `get_params` to that, and I think it's easier for those less familiar with Perl.

**Comment by kraih** [comment]
I don't think we'll ever do this again, after the security issues.
