### ISSUE TITLE
Logging with request id

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1400]
This has been a recurring topic for quite some time, and we've talked about this yesterday on IRC again. There are two logging scopes in Mojolicious, the first is operations that can be mapped to a request/response, and the second is everything outside the request/response cycle (such as a timer defined in the `startup` method).

For this feature we only care about the first case, any operation that can be mapped to the request/response cycle.
```perl
get '/' => sub ($c) {
  $c->log->debug('Some log message with request id!');
  $c->render(text => 'Hello Mojo!');
};
```
A log message created inside an action is the simplest case. In this context we want to get a log message that contains the request id (`$c->req->request_id`).
```
[2018-11-08 14:20:13.77168] [info] [1af234b] Some log message with request id!
```
But we also want to allow models to generate log messages with request id. One possible solution for that would be to make `$c->log` a secondary log object that contains the request id, and that can be passed to model objects/methods.
```perl
get '/' => sub ($c) {
  my $log = $c->log;
  my $foo = $c->param('foo');
  $c->some_model->create({foo => $foo}, $log);
  $c->render(text => 'Hello Mojo!');
};

...
package MyApp::Model::SomeModel;

sub create ($self, $values, $log) {
  $self->do_stuff($values);
  $log->debug('Another log message with request id!');
}
...
```
Of course this also means the secondary log object would work for non-blocking operations started inside the request/response cycle.
```perl
get '/' => sub ($c) {
  my $log = $c->log;
  Mojo::IOLoop->timer(1 => sub {
    $log->debug('Yet another log message with request id!');
  });
  $c->render(text => 'Hello Mojo!');
};
```
Logging in models is a problem that most of us are facing in web applications at some point. And i think the framework should provide at least one reasonable solution out of the box.

Thoughts?

**Comment by christopherraa** [comment]
Very well summarized! This _exact_ usecase (logging in models etc) is a recurring need. Currently all my implementations of logging with request id's involve some form of unattractive hack to get a request id tied to the model-operations. I do not have any implementations to propose, but I will be following this issue closely.

**Comment by s1037989** [comment]
This would be such a huge improvement!  Like @christopherraa, my implementations of logging are unattractive hacks.  It's the single most difficult part in regards to building a good model.

**Comment by kraih** [comment]
I thought @jberger was working on this, but i guess he might have given up.

**Comment by kraih** [comment]
Having thought about this feature some more, i believe the most important requirement is that the performance cost be as minimal as possible (methods like `$c->log->debug` need to short circuit just like `$app->log->debug` would). We already put a lot of effort into optimizing `Mojo::Log`.

**Comment by kraih** [comment]
I suppose we have agreement in the community that we want this feature, so i'll pre-approve it. Now we just need to find the best implementation.

**Comment by kraih** [comment]
Just thought of another special case to consider. Since the logger will most likely be cached somewhere (like in the stash as `mojo.log` or in a new controller attribute), we need to decide what the correct behaviour is for embedded applications, which usually have their own logger.

**Comment by karenetheridge** [comment]
something like this could be used for the logger used by helpers and controllers:

```
    $app->helper(log => sub ($c) {
        return $c->stash('mojo.log') if $c->stash('log');
        my $log = !length($c->req->url) ? $c->app->log : Mojo::Log->with_roles('Mojo::Role::LogWithRequestId)->new(
            request_id => $c->req->request_id,
            $c->app->log->%{qw(max_history_size history format handle path short)},  # share history buffers
        );
        $c->stash('mojo.log', $log);
        $log;
    });
```

**Comment by kraih** [comment]
To move this along i've made a minimalistic implementation that should perform very well (did not have time to add tests yet). https://github.com/mojolicious/mojo/compare/log_context

**Comment by karenetheridge** [comment]
Putting the context information into the message directly makes things very difficult for formatters that would want to put that data somewhere else.  Also, right now, nothing in Mojo::Log prevents the `$message` from being a ref (e.g. hashref or even a blessed object), which a custom formatter would know how to handle -- but appending to the message string directly in `_log` prevents this use.

**Comment by kraih** [comment]
Another topic that has come up on IRC is JSON logging, which would require much bigger changes to include context data in the formatters. That is not something i'm personally interested in (and it opens a huge can of worms). So, i'll step back from this problem for now and will let volunteers take over.

**Comment by karenetheridge** [comment]
@kraih the only changes I'd make to your branch is to remove the alteration of the message in `_log` and move it to `format` -- and changing all controller-context calls from `$c->app->log` to `$c->log` to make use of the new helper sub.  With that, both core behaviour will work the same, and it's still possible for users with other formatters to easily work with the new data.

**Comment by kraih** [comment]
@karenetheridge I don't see a simple way to do that, but feel free to modify my branch.

**Comment by kraih** [comment]
My earlier proposal is now up for a vote. We can revisit breaking changes for structured logging for the next major release. https://github.com/mojolicious/mojo/pull/1404

**Comment by willsheppard** [comment]
Regarding implementation: [Log::Any](https://metacpan.org/pod/Log::Any) is really nice because you don't have to pass in a log object to the model.

Would it be feasible to build an official [Log::Any::Adapter](https://metacpan.org/pod/Log::Any::Adapter) for Mojolicious to receive log events sent by models that are using `Log::Any`?

Looking on CPAN there are already:
- [MojoX::Log::Any](https://metacpan.org/pod/MojoX::Log::Any)
- [Log::Any::Adapter::MojoLog](https://metacpan.org/pod/Log::Any::Adapter::MojoLog)
- [Log::Any::Adapter::Mojo](https://metacpan.org/pod/Log::Any::Adapter::Mojo)

**Comment by kraih** [comment]
@willsheppard That seems completely unrelated to the problem we are trying to solve here.

**Comment by willsheppard** [comment]
@kraih Really? I was responding to your point and the following discussion, which started with:

> Logging in models is a problem that most of us are facing in web applications at some point.

Perhaps I misunderstood. My apologies.

**Comment by kraih** [comment]
@willsheppard Look at the title of this issue. The whole point is logging with request ids, that doesn't work with singletons.

**Comment by willsheppard** [comment]
I do understand that. However when a model is called by a controller as part of a request, it is still often desirable to log the request ID as part of the model's logs, so that the event can be traced back to the initial request. This is an issue we are currently facing.
