### ISSUE TITLE
Lite-applications and config override

### ISSUE THREAD

**Issue by christopherraa** [mojolicious/mojo#1406]
* Mojolicious version: 8.24
* Perl version: 5.26.0
* Operating system: Ubuntu 18.04

### Steps to reproduce the behavior
I've compiled a short demonstration that illustrates the issue.

**myapp**
```perl
#!/usr/bin/env perl
use Mojolicious::Lite;

my $config = plugin 'Config';
my $foo    = $config->{foo};

get '/config' => sub { shift->render(text => $foo) };

app->start;
```

**myapp.conf**
```
{
  foo => 'baz',
}
```

**t/myapp.t**
```perl
use Mojo::Base -strict;
use Test::Mojo;
use Test::More;
use Mojo::File qw/path/;

my $t = Test::Mojo->new(path(__FILE__)->dirname->sibling('myapp'), { foo => 'bar' });

is($t->app->config->{foo}, 'bar');
$t->get_ok('/config')->content_is('bar');

done_testing;
```
### Expected behavior
The documentation for `Test::Mojo->new()` has the following example:
```perl
my $t = Test::Mojo->new(Mojo::File->new('/path/to/myapp.pl'), {foo => 'bar'});
```
It was then my expectation that the overridden configuration would be present immediately when loading the Config-plugin so that any code run during startup would use the correct configuration parameters.

### Actual behavior
Insted the overridden configuration is available only after the app has started, as demonstrated by the tests.

**Comment by dotandimet** [comment]
@christopherraa - the difference between a Lite app and a full app here is that without a startup() method to wrap your code, it doesn't run when the app "starts", it run when the app is **loaded** (at compile time). So you are defining a route based on the value of 'foo' when the file was first parsed and compiled, before either `new` or `startup` methods get called.

You can use config overriding when testing a lite app, but only if you make sure that config lookup happens after the app is started, not when it is loaded. So the example above can be re-written like this:

```perl
get '/config' => sub { my $c = shift; $c->render(text => $c->config('foo')) };
```

**Comment by kraih** [comment]
I welcome proposals for improving the config override feature to work better with lite apps.

**Comment by kraih** [comment]
Sadly, still no proposals.

**Comment by kraih** [comment]
Fixed. 😀

**Comment by christopherraa** [comment]
Awesome! This is great. :smiley:
