### ISSUE TITLE
Feature Request: cur_file_path and bin_path

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1410]
I don't know if this is common for others, but I often want to get a path relative from either the directory of the current file or the directory of the currently executing script (`$0`) instead of the cwd (`path` default).

In the IRC, @Grinnz suggested this to get a file in the same directory as the current file:

```
path(__FILE__)->sibling('file.txt');
```

Which works well if the file is in the same directory as the current file, but not as well if the file/dir is in a child directory:

```
# the best I've been able to come up with
path(path(__FILE__)->dirname, 'path', 'to', 'file.txt)
```

Which is a little verbose. I'm wondering if something like `cur_file_path` (probably not the best name) would be useful:

```
sub cur_file_path {
    # __FILE__ should really be for calling file
    return path(path(__FILE__)->dirname, @_);
}
```

The other one I think may be useful is something like `bin_path`:

```
sub bin_path {
    return path(path($0)->dirname, @_);
}
```

Similar to something like `path($FindBin::Bin, @_)`, although I found on the IRC that [FindBin](https://metacpan.org/pod/FindBin) is definitely discouraged :)

**Comment by Grinnz** [comment]
FWIW, your second example can be written as: `path(__FILE__)->sibling('path', 'to', 'file.txt');`

**Comment by Grinnz** [comment]
Also, `$0` is less reliable than FindBin IMO. If you really want the original "script" for FindBin's definition of that, use FindBin (but I posit that most people don't actually want this).

**Comment by srchulo** [comment]
@Grinnz ah, my mistake. I thought sibling was for immediate siblings. That does help.

Do you have any references you could point to for why `$0` is less reliable? I assumed that was set at startup and then unchanged. That's unfortunate because I use that and `FindBin` a lot. 

It's also surprising to me that it would be so uncommon to want to access things from the "bin" path. I normally structure related files/dirs inside of a directory that contains the initial executing script, so that a script that is one concept can have its `cpanfile` and all related files under one directory, but maybe I'm doing it wrong and there's a better way?

That said, if it is uncommon to want FindBin's definition of a bin path, and if it's unreliable, it probably doesn't make sense to add to `Mojo::File`.

**Comment by Grinnz** [comment]
`$0` can be changed by anything by assigning to it and in fact mojolicious does this. It's mostly done to set how it appears in process lists.

The reason I say most people actually don't want this is they usually want to access something relative to a file they have control over, which means they already can get the path to that file without all this complication.

**Comment by srchulo** [comment]
@Grinnz I see. And in my situation I do have control, so maybe I just need to change how I access it.

I do think that a meaningful, short name for a subroutine that did the path from the current file would still be useful, but that may be less necessary when `path(__FILE__)->sibling('path', 'to', 'file.txt')` works.

**Comment by Grinnz** [comment]
#1408 is a proposal for such a function.

**Comment by srchulo** [comment]
Oh, great! I'll go ahead and close this, since the other half of my issue was `bin_path`, which sounds unreliable and maybe not a common need.
