### ISSUE TITLE
Feature Request: optionally pass whitespace replace character to slugify

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1415]
I think it would be nice if [slugify](https://metacpan.org/pod/Mojo::Util#slugify) allowed you to choose the character that would replace whitespace characters. Currently I wrap it:

```
sub my_slugify {
    my $slug = slugify @_;
    $slug =~ tr/-/_/;

    return $slug;
}
```

I can continue doing this if it doesn't make sense to add to slugify, but I thought it might be a nice option to have to make it more general. Of course, a good reason to not add this ability may be because of `slugify`'s current signature:

```
slugify($string, $bool);
```

Which makes it a little harder to insert a new optional argument.

**Comment by jhthorsen** [comment]
This does not make much sense to me, since it seems like the convention is to use "-" and not "_" in URLs. What is the usecase for this?

**Comment by srchulo** [comment]
Yeah, if the convention is to use "-" and not "_", then I agree that it doesn't make sense. I tried to find if there was a standard/consistent way via googling, but I didn't find a consensus.

I have two use cases I've done this for now. One was using "_" in urls for a site where that was already the delimiter and I wanted to keep the URLs the same. The other was to create a valid  subroutine name from a string for a Mojolicious helper, which to be fair isn't really 'slugify'-ing since it's not meant for a url.

**Comment by kraih** [comment]
Have to agree that we should follow conventions here, so there are no changes necessary.
