### ISSUE TITLE
Feature Suggestion: parent method for Mojo::File

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1418]
I thought it may be nice to have a corresponding `parent` method as the opposite of `child` for `Mojo::File`:

```
sub parent { $_[0]->sibling('..')->realpath }
```

I'm wondering if others thing this may be useful?

**Comment by jhthorsen** [comment]
What would be the difference between `parent()` and `dirname()`?

**Comment by srchulo** [comment]
Ha, you're right. That's my mistake. It looks like those would be the same. I'll go ahead and close. Thanks!
