### ISSUE TITLE
Suggestion: Improve Error Message 

### ISSUE THREAD

**Issue by iwelch** [mojolicious/mojo#1426]
```
Can't create listen socket: Cannot assign requested address at /usr/local/share/perl/5.26.1/Mojo/IOLoop.pm line 124.
```

It would be more user-friendly if there was a little more feedback and advice here.  Like `$_->{address}:$_->{port} is already occupied by `...find out what. with netstat..` "

**Comment by pink-mist** [comment]
That error message doesn't necessarily mean the port is already occupied though, so if you changed it to that, you'd be lying.

Also, that error message comes from the OS, not from Mojolicious.

**Comment by kraih** [comment]
Yes, this looks impossible.

**Comment by kraih** [comment]
Closing as impossible.
