### ISSUE TITLE
Mojo::Asset::File::move_to can't move file for successful requests

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1428]
* Mojolicious version: 8.25
* Perl version: 5.30
* Operating system: CentOS Linux release 7.6.1810 (Core)

I'm not sure if this is actually a Mojolicious issue, or a memory issue. Feel free to close if this is related to my app/hardware and not Mojolicious itself!

I have a [Mojolicious::Lite](https://metacpan.org/pod/Mojolicious::Lite) app that accepts requests to download images and save them to disk, and then resizes them in a subprocess. I make about 10 requests at a time, and I am seeing this intermittent error (about a few out of every 100 requests):

```
Can't move file "/tmp/mojo.tmp.mQfXSsZHXkaHtSmT" to "/tmp/vM1f6_VXjM/original/4112782": No such file or directory at /home/user/perl5/perlbrew/perls/perl-5.30.0/lib/site_perl/5.30.0/Mojo/Asset/File.pm line 109.
```

Here is my app:

```
use Mojolicious::Lite -signatures;
use Mojo::File 'tempdir';

helper ua => sub { state $ua = Mojo::UserAgent->new };

get '/download_image' => sub ($c) {
    my ($url, $id) = map $c->param($_), 'url', 'id';

    $c->ua->get_p($url)->then(sub {
        my ($tx) = @_;

        if (not $tx->res->is_success) {
            die {reason => $tx->error->{message}};
        }

        my $tempdir = tempdir();
        my $original_dir = $tempdir->child('original')->make_path;
        my $image = $original_dir->child($id);

        # ERROR THROWN HERE
        $tx->result->save_to($image);

        # resize into multiple images in subprocess and render from there
        # ...
    })->catch(sub {
        my $err = shift;
        $c->render(json => { success => 0, %$err });
    });

    $c->render_later;
};

app->start;
```

The image urls that give this error are valid and usually work when tried again (and they load in my browser fine). Also, `$tx` says that the request was successful, which makes me think that the image should have been downloaded successfully.

At first I thought that this may be a memory issue (maybe Mojo::Asset::Memory wasn't working because I was using a lot of the memory resizing?), but I saw this line [here](https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Large-file-downloads):

> When downloading large files with Mojo::UserAgent you don't have to worry about memory usage at all, because it will automatically stream everything above 250KiB into a temporary file, which can then be moved into a permanent file with "save_to" in Mojo::Message.

I also created a server with more than enough ram and CPUs to test the hardware theory (4 CPU and 16 GB of ram), and I continued to experience this issue even with tons of free memory and a very low CPU load.

### Expected behavior
Temporary mojo file should be saved to the location it is passed.

### Actual behavior
Error is thrown saying that the temporary mojo file doesn't exist.

**Comment by srchulo** [comment]
After looking into this more, I think this is not a Mojo issue, but rather me using a tempdir created in the parent process (vs my subprocess) as stated [here](https://metacpan.org/pod/File::Temp#DESTROY):

> If the object has been passed to a child process during a fork, the file will be deleted when the object goes out of scope in the parent.

I'm going to go ahead and close this since it seems like [Mojo::Asset::File](https://metacpan.org/pod/Mojo::Asset::File) isn't actually the problem.

**Comment by srchulo** [comment]
In case anyone else stumbles onto this issue, now I've solved this by using the [finally](https://metacpan.org/pod/Mojo::Promise#finally) handler on my promise and passing `CLEANUP => 0` to my tempdir:

```
my $tempdir = tempdir(CLEANUP => 0); 
$c->ua->get_p($url)->then(sub {
    ...
})->catch(sub {
    ...
})->finally(sub {
    $tempdir->remove;
});
```

**Comment by Grinnz** [comment]
For the record, the usual way to avoid this problem is to have subprocesses exit using POSIX::_exit(0) so they don't run object destructors.

**Comment by Grinnz** [comment]
Oh actually I misinterpreted it, it's because you just need to keep a reference to the $tempdir object in the parent until the end of the promise chain.

**Comment by srchulo** [comment]
@Grinnz actually, even with `CLEANUP => 0` and removing in the `finally` handler, I just saw this issue again. My flow is actually like:

```
$c->ua->get_p($url)->then(sub {
    my ($tx) = @_;

    # error checking
        
    return $tx;
})->then(sub {
    my ($tx) = @_;

    save_image($tx);
})
# then catch and finally
```

Is it possible that the `$tx` being passed to the `then` causes it to go out of scope and be destroyed and clean up the file? Do I need to handle this another way?

**Comment by srchulo** [comment]
Ah, my mistake again. The `$tx` is actually used in a subprocess to save the image, which is likely why it is going out of scope. Sorry! Your answer above explains it. I will just need to save the image before calling the subprocess.
