### ISSUE TITLE
Using non-blocking Mojo::UserAgent inside subprocesses not working (Mojo::IOLoop->reset not working)

### ISSUE THREAD

**Issue by renatocron** [mojolicious/mojo#1430]
* Mojolicious version: 8.15
* Perl version: 5.28.0
* Operating system: ubuntu:18.04

### Steps to reproduce the behavior
Using non-blocking Mojo::UserAgent (eg: get_p) inside a subprocess do not work.

You can test it running this code bellow:

    #!/usr/bin/env perl
    use strict;
    use Mojo::Promise;
    use Mojo::IOLoop::Subprocess;
    use Mojo::UserAgent;

    my $subprocess = Mojo::IOLoop::Subprocess->new;
    $subprocess->run(
        sub {
            my $subprocess = shift;

            my $ua = Mojo::UserAgent->new->inactivity_timeout(1)->connect_timeout(1);

            my @promises;

            for (1 .. 5) {

                my $request_p = $ua->get_p(('https://perlcon.eu/'));

                $request_p->then(
                    sub {
                        my ($tx) = @_;
                        print $tx->res->code . "\n";

                    }
                  )->catch(
                    sub {
                        print STDERR @_;

                    }
                  );

                push @promises, $request_p;

            }

            print gmtime . ": Before Mojo::Promise->all()->wait\n";

            Mojo::Promise->all(@promises)->wait();

            print gmtime . ": After Mojo::Promise->all()->wait\n";

            return 1;

        },
        sub {
            print "Done!!!\n\n\n";
        }
    );

    $subprocess->ioloop->start unless $subprocess->ioloop->is_running;

### Expected behavior
Inside a subprocess everything should work as "clean" fork, I suppose.

### Actual behavior
Subprocess thinks Mojo::IOLoop is already running, but cannot stop or reset it.

--

I don't actually think that this should be fixed if it's not easy, I think just a documentation is enough for now. to avoid other people trying to make it work when it's not possible.

**Comment by kraih** [comment]
If as you say a simple `get_p` is enough to trigger the problem why is your example so complex? Do multiple promises and `all` trigger another problem?

**Comment by renatocron** [comment]
Even with just one promise, it's the same result.

Given this:

    #!/usr/bin/env perl
    use strict;
    use Mojo::Promise;
    use Mojo::UserAgent;

    my $ua = Mojo::UserAgent->new;

    my $request_p = $ua->get_p(('https://perlcon.eu/'))->then(
        sub {
            print shift->res->code . "\n";
        }
    );

    Mojo::Promise->all($request_p)->wait();
    # STDOUT show 200 code

But when using subprocess:

    #!/usr/bin/env perl
    use strict;
    use Mojo::Promise;
    use Mojo::IOLoop::Subprocess;
    use Mojo::UserAgent;

    my $subprocess = Mojo::IOLoop::Subprocess->new;
    $subprocess->run(
        sub {
            my $subprocess = shift;

            my $ua = Mojo::UserAgent->new->inactivity_timeout(1)->connect_timeout(1);

            my $ua = Mojo::UserAgent->new;

            my $request_p = $ua->get_p(('https://perlcon.eu/'))->then(
                sub {
                    print shift->res->code . "\n";
                }
            );

            Mojo::Promise->all($request_p)->wait();

            # STDOUT show 200 code


            return 1;

        },
        sub {
            print "Done!\n";
        }
    );


    $subprocess->ioloop->start unless $subprocess->ioloop->is_running;
    # only Done! is printed out

**Comment by kraih** [comment]
This patch appears to resolve the problem with the `Poll` backend, but i can't seem to find a solution for the `EV` backend.
```diff
diff --git a/lib/Mojo/Reactor/Poll.pm b/lib/Mojo/Reactor/Poll.pm
index ee6e583e6..ef7cde53c 100644
--- a/lib/Mojo/Reactor/Poll.pm
+++ b/lib/Mojo/Reactor/Poll.pm
@@ -91,7 +91,11 @@ sub remove {
   return !!delete $self->{io}{fileno($remove) // croak 'Handle is closed'};
 }
 
-sub reset { delete @{shift()}{qw(events io next_tick next_timer timers)} }
+sub reset {
+  my $self = shift;
+  $self->stop;
+  delete @{$self}{qw(events io next_tick next_timer timers)};
+}
 
 sub start {
   my $self = shift;
```

**Comment by kraih** [comment]
This patch seems to make all cases work with `Poll` and `EV` backends, but is a hack at best.
```diff
diff --git a/lib/Mojo/IOLoop.pm b/lib/Mojo/IOLoop.pm
index f7b30b41c..da494883a 100644
--- a/lib/Mojo/IOLoop.pm
+++ b/lib/Mojo/IOLoop.pm
@@ -126,7 +126,18 @@ sub server {
   return $self->acceptor($server);
 }
 
-sub singleton { state $loop = shift->SUPER::new }
+sub singleton {
+  my $class = shift;
+
+  state $pid  = $$;
+  state $loop = $class->SUPER::new;
+  if ($pid != $$) {
+    $loop = $class->SUPER::new;
+    $pid  = $$;
+  }
+
+  return $loop;
+}
 
 sub start {
   my $self = _instance(shift);
```

**Comment by kraih** [comment]
Thsi change might resolve the problem. https://github.com/mojolicious/mojo/compare/a258f97417d2...818fccf2aa33

**Comment by renatocron** [comment]
> Thsi change might resolve the problem. [a258f97...818fccf](https://github.com/mojolicious/mojo/compare/a258f97417d2...818fccf2aa33)

Tested with this (https://gist.github.com/renatocron/098bb7f855bd7b049dc05c46062e9941) and it's working!
