### ISSUE TITLE
memory leak in callback arguments in promises

### ISSUE THREAD

**Issue by karenetheridge** [mojolicious/mojo#1432]
From https://github.com/mojolicious/mojo/pull/1403.

Arguments to promise callback subs should be weakened as they are copied, if the originals were weak.  Otherwise, memory leaks occur when defining callback subs that close over things like `$app`, `$ua` etc.

A branch demonstrating the issue, as well as an (incomplete) attempt to resolve it, can be found in https://github.com/karenetheridge/Mojolicious/tree/ether/weak_promise_args.  (My first attempt at a fix did not work -- there is more that needs to be done lower down. I have followed the code down into `$self->ioloop->next_tick(..)` and then more needs to be done in there as well.)

**Comment by kraih** [comment]
I believe this is not fixable.
