### ISSUE TITLE
Mojo::Reactor::EV: I/O watcher failed on hot-reload

### ISSUE THREAD

**Issue by ginesr** [mojolicious/mojo#1435]
* Mojolicious version: 8.26
* Perl version: 5.24.1
* Operating system: Debian Stretch

### Steps to reproduce the behavior

When running AnyEvent loop after hot-reload the following error is shown:

Mojo::Reactor::EV: I/O watcher failed: Can't locate object method "" via package "Mojo::Reactor::EV" at /usr/local/share/perl/5.24.1/Mojo/Reactor/Poll.pm line 143.
Use of uninitialized value $cb in method lookup at /usr/local/share/perl/5.24.1/Mojo/Reactor/Poll.pm line 143.

### Expected behavior
Just a hot-reload without errors in log file

### Actual behavior
Hot-reload finishes with errors in log file

**Comment by kraih** [comment]
We need a minimal test case to investigate.

**Comment by renatocron** [comment]
+1

I got some of these erros too, but IDK yet the side-effects besides the error msg or what causes it

**Comment by kraih** [comment]
Since there has been no new information we'll assume the problem resolved itself.

**Comment by ginesr** [comment]
It is NOT solved, I have no idea how to write a test to trigger the "hot reload" feature, it only happen when is reloading new code and replacing new workers

**Comment by boldra** [comment]
Just had this, it's my websocket library treating my socket as though it supports wss, which it doesn't.
