### ISSUE TITLE
Default "text/plain;charset=UTF-8" returned by Mojolicious::Types::content_type may be confusing

### ISSUE THREAD

**Issue by aitap** [mojolicious/mojo#1441]
* Mojolicious version: 8.26
* Perl version: 5.24.1
* Operating system: Debian GNU/Linux 9.11 (stretch)

### Steps to reproduce the behavior

Use the `reply->file` helper to serve a static binary file not known by `Mojolicious::Types`, such as a `.tar.xz` archive or a `.gpg` encrypted file and try to get the served content using a browser.

### Expected behavior

Browser offers to download the binary file.

### Actual behavior

Browser displays a screenful of [mojibake](https://en.wikipedia.org/wiki/Mojibake).
Browser assumes that the reply can be displayed as text because Mojolicious sends the `Content-Type: text/plain;charset=UTF-8` header:

```
$ perl -Mojo -E'a("/" => sub { shift->reply->file("test.tar.xz") })->start' get -M HEAD /
HEAD / HTTP/1.1
Host: 127.0.0.1:38719
User-Agent: Mojolicious (Perl)
Content-Length: 0
Accept-Encoding: gzip

HTTP/1.1 200 OK
Last-Modified: Sun, 24 Nov 2019 17:39:39 GMT
ETag: "a31a2393cc3244a02333b5515918bf9d"
Accept-Ranges: bytes
Content-Length: 6701144
Content-Type: text/plain;charset=UTF-8
Date: Sun, 24 Nov 2019 17:43:06 GMT
Server: Mojolicious (Perl)
```

The `reply->file` helper calls `Mojolicious::Static::serve_asset`, which uses `Mojolicious::Types::content_type` (currently marked as experimental) to determine the `Content-Type` to send back to the user. Before the introduction of `content_type`, `serve_asset` didn't send the `Content-Type` header at all.

`Mojolicious::Types::content_type` [defaults](/mojolicious/mojo/blob/243f705fc67c4bd4c1b2f4ad4f405cc49b4dabb2/lib/Mojolicious/Types.pm#L43) [to `text/plain;charset=UTF-8`](/mojolicious/mojo/blob/243f705fc67c4bd4c1b2f4ad4f405cc49b4dabb2/lib/Mojolicious/Types.pm#L27) for types it cannot classify otherwise. A default of [`application/octet-stream`](https://tools.ietf.org/html/rfc2046#section-4.5.1) might be a safer option. Alternatively, the default `Content-Type` could be made into a setting.

I can prepare a pull request for either option if you tell me which one is preferred more.

**Comment by kraih** [comment]
Like i said on IRC, i would probably vote in favour of changing the default to `application/octet-stream`.

**Comment by Sadrak** [comment]
Hi, we are using App::opan and with this change the .txt-Files are now available only via download, because the content-type changed from text/plain to application/octet-stream.

I guess this is the relevant part from App::opan:

```perl
get "/${pan}/modules/02packages.details.txt" => sub {
  $base_static->dispatch($_[0]->stash(path => "${pan}/index"));
};
```

i would like to create a patch for App::opan:

```perl
get "/${pan}/modules/02packages.details.txt" => sub {
  $_[0]->res->headers->content_type('text/plain;charset=UTF-8');
  $base_static->dispatch($_[0]->stash(path => "${pan}/index"));
};
```

Is this the best way?

**Comment by aitap** [comment]
On Mon, 15 Jun 2020 03:11:55 -0700
Felix Ostmann <notifications@github.com> wrote:

> get "/${pan}/modules/02packages.details.txt" => sub {
>   $_[0]->res->headers->content_type('text/plain;charset=UTF-8');
>   $base_static->dispatch($_[0]->stash(path => "${pan}/index"));
> };
 
> Is this the best way?

I think so. AFAIK, Mojolicious::Static::dispatch currently tries to
determine the Content-Type (via serve method) from the file name, but
since "${pan}/index" has no extension indicating that it's text/plain,
Mojolicious::Types falls back to the default value.

-- 
Best regards,
Ivan
