### ISSUE TITLE
Feature Request: Mojo::IOLoop->io() to accept a file descriptor

### ISSUE THREAD

**Issue by FGasper** [mojolicious/mojo#1445]
* Mojolicious version: 8.23
* Perl version: 5.26
* Operating system: macOS Mojave

I note that `io()` always expects a filehandle rather than a file descriptor. IO::Async and AnyEvent work with FDs as well as filehandles, and this is convenient for interfacing with, e.g., Net::Curl, which provides FDs rather than filehandles. So to work with Mojo I have to create a Perl filehandle but also ensure that Perl never garbage-collects that filehandle.

Since it appears that Mojo::Reactor::Poll uses FDs internally anyway, would it be sensible to accept the FD in lieu of a filehandle? Or is that something that each individual Reactor implementation would need to implement?

**Comment by kraih** [comment]
That part of the API is a relic from when the reactor used the object oriented APIs provided by some modules like `IO::Poll`. I wouldn't mind a reasonable proposal for deprecating the use of filehandles and replacing them with file descriptors.

**Comment by FGasper** [comment]
Is deprecation necessary? Could it be as simple as:
```
my $fd = ref($fd_or_fh) ? fileno($fd_or_fh) : $fd_or_fh;
```
?

**Comment by kraih** [comment]
Yes, deprecation is needed. At that layer we don't want overhead that is not absolutely necessary.

**Comment by FGasper** [comment]
I’m rather new to Mojo, so this may be totally off-base or just naïve, but maybe something like:

- Implement `iofd()` method in the baseline distribution. Make `io()` wrap that method.
- Eventually make `io()` warn; later still drop it altogether.

**Comment by kraih** [comment]
If you want to discuss implementation i strongly recommend joining the IRC channel.

**Comment by kraih** [comment]
Btw. We do have a process for deprecating a feature, there isn't really a difference if you change an argument or [remove a method](https://github.com/mojolicious/mojo/commit/fbcb9b81dc488690baa636a3e8e0e68ebe18299c).

**Comment by kraih** [comment]
Because of the significant performance cost i'm afraid this proposal is rejected.
