### ISSUE TITLE
Promise support in Mojo::IOLoop::Stream

### ISSUE THREAD

**Issue by declanmalone** [mojolicious/mojo#1446]
* Mojolicious version: ANY
* Perl version: ANY
* Operating system: ANY

### Steps to reproduce the behavior
Sip at the cup of Mojo::IOLoop::Stream

### Expected behavior
A cool, refreshing draught (or something more bitter; TBD)

### Actual behavior
My lips were ripped right off.

    A "properly" implemented version of Mojo::IOLoop::Stream would have
    additional method calls such as:

    read_p($opt_bytes)
        Takes an optional number of bytes (defaulting to "high water mark") to
        read from the Stream and returns a Mojo::Promise which returns up to
        that number of bytes of data upon fulfillment.

        In the time between creation of the promise and its fulfillment, the
        Mojo::IOLoop::Stream object will not emit any "read" events. Upon
        fulfillment, it will emit a "read" event to any subscribers with the
        data described above.

        No more than one call to "read_p()" on a given "Mojo::IOLoop::Stream"
        object can be active at any time.

    write_p($data)
        Like read_p, but for writing.

In practical terms, if you have:

   Mojo::IOLoop::Stream(reader) -> on(read ... -> Mojo::IOLoop::stream(writer)

this can run out of memory if the writer is slower than the reader. NG.

As an alternative to chaining on-read callbacks, we should have a promise-based interface that lets the downstream user of Mojo::IOLoop::Stream dictate the pace at which data is produced.

**Comment by declanmalone** [comment]
# Backpressure

In push based systems, when a producer produces data faster than the consumer can process, data will start backing up. Pending data is stored in memory. Unless the producer stops producing, the system will eventually run out of memory and crash. The ability for a consumer to inform the producer to slow down is backpressure.

**Comment by declanmalone** [comment]
I don't see why my initial issue only got a "thumbs down" with no actual words to rebut it.

Promise-based programming (along with async/await) definitely seems to be a much more user-friendly paradigm than one that is only based on responding to events.

Maybe you consider Mojolicious to be more important than Mojo? I disagree.

**Comment by amenonsen** [comment]
> I don't see why my initial issue only got a "thumbs down" with no actual words to rebut it.

I found all the contrived edginess and hyperbole ("My lips were ripped right off") annoying.

**Comment by declanmalone** [comment]
Before I came across the concept (and nomenclature) of "backpressure", I called this the "firehose problem".
Your problem with how I described this concept is not *my* problem.

**Comment by Grinnz** [comment]
If you want people to care about their problem, it is your problem to get them to care. You don't do that by telling them what they need, or unrelated allegory.

**Comment by declanmalone** [comment]
Not an allegory.
"You need this" is synonymous with "feature request"

**Comment by declanmalone** [comment]
And since when is adding colour not an attempt to engage with another person?

**Comment by Grinnz** [comment]
It is not synonymous but perhaps there is a language barrier.

You will not engage people in a technical issue tracker with "color". The issue template asks specifically for the difference between expected and actual behavior, and steps to reproduce. These are asking for technical details only, and specifically the use case where the problem occurs; this is the missing component so far.

**Comment by declanmalone** [comment]
Read back to where I copied and pasted an explanation of "backpressure"

If anyone had been interested in understanding what the issue was (which I did explain in my first post) it would be clear that the on-event model can lead to memory being consumed, and as a result the framework suffers from a denial of service attack.

**Comment by declanmalone** [comment]
(aside: "I expect", "you expect"... language barrier right there)

**Comment by Grinnz** [comment]
So far you have only explained a general problem that can occur, not shown how it is a problem in a real world application, like the issue template asks for. We do not make a practice of fixing theoretical problems.

**Comment by declanmalone** [comment]
Maybe you consider Mojolicious to be more important than Mojo? I disagree.

**Comment by declanmalone** [comment]
I'm not just doing this to be a pain or anything.

**Comment by declanmalone** [comment]
Do you understand, in theory at least, what the issue that I am raising it?
Do you understand how Mojo::IOLoop::Stream could be improved by also implementing a promise-based interface?

**Comment by Grinnz** [comment]
I understand generally what you're suggesting, but I do not know if it will improve any real world application or not (and I am not talking about just Mojolicious). The other reason people reacted strongly to your request is phrasing: "You need this", "properly". These imply you know better than those who have worked on the code, which appears impolite.

**Comment by declanmalone** [comment]
"I" "have" "been" "quite" "polite".

Actually, leaving aside the sarcasm, the quotes I put around "properly" were intended to show that I am not omniscient.  have not been overtly impolite to anyone working on the code, and I don't really appreciate the insinuation that you seem to be making. But let's leave impoliteness out of the equation completely. OK?

**Comment by Grinnz** [comment]
You don't get to decide what is polite to other people, that's not how interactions work. I am not insinuating anything, I am explaining how your words have been interpreted, at least by me.

**Comment by declanmalone** [comment]
I have two more general, background points to make

First, I more or less said that I consider Mojo to be at least as important as Mojolicious. By that (and I'm giving it a compliment here), I mean that I'm comparing it with other event frameworks like EV, AnyEvent, Coro and POE. Mojo is by far and away the easiest framework to use for general-purpose asynchronous coding. But the one thing that really bugs me about it is Mojo::IOLoop::Stream. This isn't a theoretical beef that I have with it. It is just so hard to reconcile all the really nice stuff about the event framework side of things with how it forces the on-event model on you.

The second point is about this "backpressure" thing. I have a bit of a story here. I got so annoyed about how the Stream object didn't seem to play nicely with promises that I decided that I'd go and do something else.... like learn a new language or something. I spent a couple of weeks learning Rust. After a bit of learning that, I started looking into frameworks, thinking that I would shift over to using Rust to code the Mojo project that I was working on. I found Tokio. At that point, I realised that the thing that had been bugging me (and that I had called the "firehose" problem) was understood there. They solved it in the same way that I had figured it should be solved: promise-based lazy evaluation instead of being at the mercy (oops... sorry.... colourful language) of the on-read/on-event model.

re "You don't get to decide what is polite to other people"...  seriously?

**Comment by Grinnz** [comment]
The background is helpful. I am just saying, it's going to be difficult to get someone interested to solve this problem without a real demonstration of it.

> re "You don't get to decide what is polite to other people"... seriously?

Yes. It does not mean you cannot attempt to correct a misinterpretation, but it does mean you shouldn't blame others for it occurring.

**Comment by declanmalone** [comment]
Let's just divide this up into two things.

I have a technical suggestion for how Mojo could be better. I may not have expressed it in a palatable way at the start, but hopefully I have made amends for that.

On the whole politeness thing, some of you thought that I was being impolite. I thought the emoji thing instead of an answer was impolite. Most likely, no offence was intended on either side. Either way, arguing about politeness per se is just a rabbit hole that doesn't profit anyone to go down. Agreed?

**Comment by kraih** [comment]
The `Mojo::IOLoop::*` modules tend to only contain features we actually need to implement the higher level modules (like `Mojo::UserAgent` and `Mojo::Server::Daemon`). Even with a less eye roll inducing feature request this would be a pretty hard sell. The performance cost of promises and `async`/`await` at such a low level would be immense, to the point where i can't imagine it ever to be worth using for any protocol.

**Comment by kraih** [comment]
This is not happening.
