### ISSUE TITLE
Feature Request: Mojo::File method to get/set file extension

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1448]
I think it would be useful to have an `ext` method on [Mojo::File](https://metacpan.org/pod/Mojo::File) that allows you to:

- Get an extension when you provide no arguments
  
```
# returns 'txt'
my $ext = path('file.txt')->ext;
```

- Set an extension and return a new `Mojo::File`

```
# returns Mojo::File with path 'file.csv'
path('file.txt')->ext('csv')

# returns Mojo::File with path 'file'
path('file.txt')->ext('')

# providing a leading . works too
path('file.txt')->ext('.csv')
```

Below is a quick implementation that I believe does what was described above:

```
sub ext {
  my $self = shift;
  return ($self =~ /\.([^.]*)/)[0] // '' unless @_;

  my $ext = shift // '';
  if ($ext ne '' and index($ext, '.') != 0 ) {
    $ext = ".$ext";
  }

  my $new_path = $$self;
  unless ($new_path =~ s/\.[^.]*/$ext/) {
    $new_path .= $ext;
  }

  return $self->new($new_path);
}
```

I'm curious if others think this would be useful, or if there are any issues/complications I'm not thinking of?

**Comment by Grinnz** [comment]
The difference in behavior between get and set while not being a real attribute leads me to think it's more confusing than it's worth.

**Comment by Grinnz** [comment]
Also, it needs to consider files with multiple extensions

**Comment by s1037989** [comment]
This would be extremely useful! I often find myself wishing that Mojo::File
had that built in. I always end up creating a quick Role package at the top
of my module to get it done, but it certainly gets repetitive. Also, I
never seem to be consistent about it from project to project. I haven't
released a CPAN module for such a role because I haven't stopped to think
about what a good implementation should look like.

Having it built in would be so, so great!!

**Comment by srchulo** [comment]
@Grinnz although it isn't a real attribute on the `Mojo::File` instance, an extension is a real attribute on files, so from the user's perspective I feel like it isn't any different from a real attribute. And really, the extension could be parsed as an attribute when creating a new object and then used appropriately everywhere else, but I think that may be more complicated.

The multiple extensions is a good point. I think that can be solved easily by just looking at the last part using `to_array`:

```
return (@{$self}[-1] =~ /\.(.*)/)[0] // '' unless @_;
```

And similar for setting the last part to replace the extension.

**Comment by srchulo** [comment]
Maybe something like:

```
sub ext {
  my $self = shift;

  my $parts = $self->to_array;
  return ($parts->[-1] =~ /\.(.*)/)[0] // '' unless @_;

  my $ext = shift // '';
  if ($ext ne '' and index($ext, '.') != 0 ) {
    $ext = ".$ext";
  }

  unless ($parts->[-1] =~ s/\..*/$ext/) {
    $parts->[-1] .= $ext;
  }

  return $self->new(@$parts);
}
```

Although that doesn't account for the case where it's a directory. Maybe it could just return at the top if it's a directory.

**Comment by Grinnz** [comment]
Directories have extensions too. (most commonly .d)

**Comment by srchulo** [comment]
Ah, right. Scratch that part then :)

**Comment by s1037989** [comment]
Could extensions be handled like files, where extensions have parents,
children, and siblings? The extension would always operate on the basename
of the Mojo::File instance.

**Comment by kiwiroy** [comment]
Likewise, I often need this functionality and hack around/copy-pasta solutions.

Any comments on this [role](https://gist.github.com/kiwiroy/1f07dfbc9d940b4da598135c87af7c36)?

**Comment by kraih** [comment]
If this is really such a popular feature i don't mind putting an implementation up for a vote. But so far i've not seen a proposal here where i liked the code.

**Comment by srchulo** [comment]
@kiwiroy I like the idea of the `moniker` method. I'm not a big fan of having two methods to get the and switch the extension, but maybe that is less confusing than having one. To me it feels more natural to have one method that does both, and more like what a user may expect from a file object.

**Comment by srchulo** [comment]
@kiwiroy I do like your implementation. Much cleaner than mine :)

**Comment by kiwiroy** [comment]
The gist above has been moved to [CPAN](https://metacpan.org/pod/Mojo::File::Role::Extension).

**Comment by kraih** [comment]
I'm not opposed to the feature, but implementations so far seem rather complex and interest fairly limited.

**Comment by kraih** [comment]
No new feedback, do we consider this resolved?

**Comment by srchulo** [comment]
I think so. With `extname` added by you and [Mojo::File::Role::Extension](https://metacpan.org/pod/Mojo::File::Role::Extension) by @kiwiroy , I think all of my use cases are covered.

**Comment by srchulo** [comment]
Thanks for those additons!
