### ISSUE TITLE
Hypnotoad / Prefork dump cores on small values of accepts and disabled keep-alive

### ISSUE THREAD

**Issue by melhesedek** [mojolicious/mojo#1449]
* Mojolicious version: 8.27
* Perl version: 5.30.1
* Operating system: Linux 5.3.13-arch1-1

### Steps to reproduce the behavior
*It's a TL;DR version, scroll down and see [attached archive](https://github.com/mojolicious/mojo/files/3951190/repro.tar.gz) for code and more details*
I run a simple synchronous server

    get '/' => sub {
        usleep 1_000_000 * rand;
        shift->render(text => "i'm ok");
    };

with a command

    ./server.pl prefork --listen 'http://*:3002' \
      --accepts 1 \
      --clients 1 \
      --requests 1 \
      --workers 10

and a client in a second terminal to generate some load.

    ./client.pl

### Expected behavior
I expect each worker process to exit normally after it served one request.

### Actual behavior
Eventually a core dump of a worker process is generated. `gdb` shows `Program terminated with signal SIGQUIT, Quit.`.

### Setting up a clean environment
I use a Linux box, [plenv](https://github.com/tokuhirom/plenv) to compile recent Perl version with debug symbols and [cpanm](https://metacpan.org/pod/distribution/App-cpanminus/bin/cpanm) to install Mojolicious locally.

    plenv install --as=5.30.1-debugging 5.30.1 -DDEBUGGING
    plenv local 5.30.1-debugging
    plenv install-cpanm
    cpanm -L local Mojolicious@8.27 --quiet

Then make sure core dumps will end up in a current working directory (you may want to back up previous value but it won't persist across system boots). It's not a necessary step but `client.pl` and `gdb` commands here assume it's done.

    echo 'core' | sudo tee /proc/sys/kernel/core_pattern

Start server

    PERL5LIB=local/lib/perl5 ./server.pl prefork --listen 'http://*:3002' \
      --accepts 1 \
      --clients 1 \
      --requests 1 \
      --workers 10

and client from another terminal.

    PERL5LIB=local/lib/perl5 ./client.pl

It usually takes up to 15 minutes to reproduce on my Intel i5-2500K box. After client terminates there should be 1 to 3 `core.<pid>` files in a current working directory.

If a core dump was generated by e.g. a process with pid 33156, it's backtrace can be inspected with the following command:

    gdb -ex bt ~/.plenv/versions/5.30.1-debugging/bin/perl core.33156

To observe signals-related behaviour I run server via [strace](https://strace.io/).
_It generates a lot of `traces/trace.<pid>` files which could take up some disk space._

    mkdir traces
    PERL5LIB=local/lib/perl5 strace -o traces/trace -ff -e signal,write -s 128 -tt -- ./server.pl prefork \
      --listen 'http://*:3002' \
      --accepts 1 \
      --clients 1 \
      --requests 1 \
      --workers 10

### Dumps and traces

According to backtraces it seems processes usually terminate inside `Perl_pp_exit` or `perl_destruct` functions. In a syscall traces of dumped processes `SIGQUIT` arrives some microseconds after `SIGQUIT` handler is restored to `SIG_DFL` (a default one).

I assume there's a race condition due to a time gap between signal handlers are reset by Perl and process terminates.

### Potential fix

See `server-fixed.pl` in [attached archive](https://github.com/mojolicious/mojo/files/3951190/repro.tar.gz). This seems to do the trick but race condition still remains (AFAIK a signal may arrive between `rt_sigaction` setting `SIGQUIT` handler to `SIG_DFL` and `rt_sigprocmask` blocking the process from recieving `SIGQUIT`).

	app->hook(before_server_start => sub {
		my ($server, $app) = @_;

		my $sigset = POSIX::SigSet->new(SIGQUIT);
		$server->ioloop->on(finish => sub {
			my $loop = shift;

			sigprocmask(SIG_BLOCK, $sigset) // die "Could not block SIGQUIT\n";
		});
	});

**Comment by jhthorsen** [comment]
When is this a problem in the real world?

**Comment by melhesedek** [comment]
When your app does something memory-intensive but not very often, so you lower `accepts` value to release memory back to the OS. AFAIK this (or memory leakage) is the primary use case for similar setting in other web servers, e. g. [httpd's MaxConnectionsPerChild](https://httpd.apache.org/docs/current/mod/mpm_common.html#maxconnectionsperchild).

In my case setting `accepts` to 10 resulted in several dozens core dumps a day on a modest 2 RPS.

**Comment by kraih** [comment]
The problem seems to obscure for us to fix in Mojolicious.

**Comment by oschwald** [comment]
We see 100s of similar core dumps a week in production with `accepts` set to 100 and `requests` set to 70. Although it isn't a significant issue, it does cause unnecessary many spurious logs that must be filtered through when monitoring for real issues.

**Comment by jixam** [comment]
@kraih Please consider reopening. We have `accepts` at 1000 but this issue actually caused an outage for us when Ubuntu started storing core dumps in an unexpected location after a routine `apt upgrade`.

Here is a maybe less obscure repro which dumps core for me about 50% of the time:

Server (using strace in case core dumps are disabled):
```
strace -e kill perl -Mojo -E 'get "/" => {inline => "%= sleep 5"}; app->start' prefork -a 1
```

Client:
```
while sleep 1; do curl http://127.0.0.1:3000/; done
```

The trick is doing enough work (`sleep 5`) that a heartbeat happens while the IO loop is shutting down after reaching its maximum number of requests (i.e. `max_accepts`). That can end up trying to signal `SIGQUIT` when the worker has unregistered its handler during `exit()`.

**Comment by jixam** [comment]
It turns out the Prefork signal handlers are `local` so an effective workaround is to globally ignore `SIGQUIT` before startup. As @ksmadsen has shown, this will also ignore the signals during `exit()`.

My test server then becomes:
```
strace -e kill perl -Mojo -E '$SIG{QUIT} = "IGNORE"; get "/" => {inline => "%= sleep 5"}; app->start' prefork -a 1
```
which never core dumps for me.

I still think a change is warranted so that all users do not have to know about such a workaround.

**Comment by mschout** [comment]
This bit us hard.  Eating up huge amounts of disk space once we lowered `accepts`.

**Comment by kraih** [comment]
There's a possible fix, unfortunately nobody has reviewed it yet.

**Comment by jixam** [comment]
FWIW, this simple workaround has completely solved the problem for us (this is also what I discussed above):

```
BEGIN {
    # Protect against stray signals from the process manager
    $SIG{QUIT} = 'IGNORE';
}
```

The PR #1883 ensures that the stray signals never happen and the workaround is no longer needed.
