### ISSUE TITLE
Test::Mojo->json_is(): misleading output on some test failures

### ISSUE THREAD

**Issue by DrHyde** [mojolicious/mojo#1456]
* Mojolicious version: 8.29
* Perl version: 5.26.1
* Operating system: High Sierra

When testing a JSON value like `{ "fruit": "lemon" }` with `...->json_is('/animal', 'bat')` we correctly get a failure, but the diagnostic message complains that `undef` doesn't equal `'bat'` which isn't quite right. The value isn't even undef, it *doesn't exist*. Same applies to `json_like`.

**Comment by jhthorsen** [comment]
How do you suggest this to be fixed @DrHyde?

**Comment by DrHyde** [comment]
My plan was to factor out the important bit of `json_has` and reuse that to decide whether to spit out an alternative message.

**Comment by DrHyde** [comment]
FYI ... [work in progress](https://github.com/DrHyde/mojo/commits/improve-error-output-from-json_is). Still need to muck about with `json_like`.

**Comment by jhthorsen** [comment]
The problem with https://github.com/DrHyde/mojo/commit/3417e72b8def8e3da5a0ee80fff83e751d323951#diff-a3cb567ecd4d756d754d1baee62ee931R215 is that it ignores `$desc`.

**Comment by DrHyde** [comment]
Hurrah for code review :-)

**Comment by DrHyde** [comment]
This is activity. The issue shouldn't be closed.

**Comment by kraih** [comment]
I do not appreciate attempts to cheat the system. So i'm closing this issue right away. If you're still working on a patch you should have said so.
