### ISSUE TITLE
Feature Request: add a way that the Mojo::Server being used can be identified

### ISSUE THREAD

**Issue by jlcooper** [mojolicious/mojo#1457]
It would be useful if there was an easy way to identify which Mojo::Server is actually running from within the app.

Ideally it would be nice to be able to use something like:

```perl
if ( $app->server_type =~ m/^(?:prefork|hypnotoad)$/ ) {
    # Do something here that we only want to do on a preforking server
}
```

Example use would be to trigger a graceful stop of a preforked worker process when certain conditions are met (e.g. a routes been used that we know that uses up a lot memory).

I'm happy to have a go at implementing this, but want to get feedback on the idea before starting.

**Comment by kraih** [comment]
The [before_server_start](https://mojolicious.org/perldoc/Mojolicious#before_server_start) hook already exists for this.

**Comment by jlcooper** [comment]
Thanks, I'll have a play with the before_server_start hook then.
