### ISSUE TITLE
Cannot write use Mojo::Base -async twice

### ISSUE THREAD

**Issue by skaji** [mojolicious/mojo#1461]
* Mojolicious version: 8.31
* Future::AsyncAwait version: 0.35
* Perl version: v5.30.1
* Operating system: macOS

### Steps to reproduce the behavior

I'm not trying to nitpick, but currently we cannot write `use Mojo::Base -async;` twice.

```perl
package Main::Package;
use Mojo::Base -base, -async;

package Sub::Package {
    use Mojo::Base -base, -async;
}
```
```
❯ perl -c lib/Main/Package.pm
Expected async to be followed by sub at lib/Main/Package.pm line 5.
```

### Expected behavior

Does not emit errors.

### Actual behavior

Emit a compile time error, and exit.

**Comment by kraih** [comment]
You'll have to report this as a bug for `Future::AsyncAwait`, we can't do anything here.

**Comment by skaji** [comment]
Okay.

**Comment by skaji** [comment]
https://rt.cpan.org/Ticket/Display.html?id=131493

**Comment by kraih** [comment]
Looks like `Future::AsyncAwait` is helpless in this situation, so we'll have to work around the problem. https://github.com/mojolicious/mojo/compare/4ea7dcc31556...54e3f4cbf635

**Comment by skaji** [comment]
@kraih Thank you.
