### ISSUE TITLE
Mojo::Util trim shows warnings with undefined parameter

### ISSUE THREAD

**Issue by niceperl** [mojolicious/mojo#1463]
* Mojolicious version: 8.32
* Perl version: 5.30.0
* Operating system: Windows

### Steps to reproduce the behavior
```perl
use Mojo::Util qw/trim/;

my $data_to_be_trimmed;
my $result = trim($data_to_be_trimmed);
print $result, "\n";
```

### Expected behavior
No warnings if the variable is not defined with a value

### Actual behavior
The previous code shows this message:
```
Use of uninitialized value $str in substitution (s///) at C:/Perl/perl/site/lib/Mojo/Util.pm line 322.
Use of uninitialized value $str in substitution (s///) at C:/Perl/perl/site/lib/Mojo/Util.pm line 323.
```

**Comment by jhthorsen** [comment]
Why do you expect no warnings? Also, what would the return value be?

**Comment by niceperl** [comment]
IMHO, warnings in this use case has no sense. I know it is easy to avoid them, but if the meaning of this function is cleaning blanks, the warnings are useless. 
I could understand better if there are only one warning message from the caller perspective, not the internals of this sub.

**Comment by Grinnz** [comment]
It is a string operation; passing an undefined value is not supported.

The `length` function returns undef when given undef, but this is because `length` is useful as a boolean whether or not the value is defined. I cannot think of any case where it is useful to call `trim` on an undefined value.

**Comment by niceperl** [comment]
I see your point, but from a programmer perspective who is using a third-party function with a concrete parameter (not defined in this case), an internal warning message like this is ugly.

**Comment by jhthorsen** [comment]
Sounds like you ned to reach out to the developer of the third-party function instead.

I'm 👎to handling undefined in `trim()`.

**Comment by kraih** [comment]
Looks like we don't want to handle `undef`.
