### ISSUE TITLE
Mojo::Asset::Memory: Unable to change tmpdir during upgrade

### ISSUE THREAD

**Issue by d912e3** [mojolicious/mojo#1464]
* Mojolicious version: 8.32
* Perl version: 5.30.1
* Operating system: Arch Linux (Linux 5.4.15-arch1-1)

### Steps to reproduce the behavior
The following script is based on the documentation for the [`Mojo::Asset::Memory::upgrade`](https://mojolicious.org/perldoc/Mojo/Asset/Memory#upgrade) event:
```perl
use Mojo::Base -strict;
use Mojo::Asset::Memory;
use Mojo::File qw(tempdir path);

my $tmpdir = tempdir;
my $file;
my $mem = Mojo::Asset::Memory->new(auto_upgrade => 1, max_memory_size => 10);
$mem->on(upgrade => sub {
    $file = $_[1];
    $file->tmpdir($tmpdir);
});
$mem->add_chunk('a' x 11);

die "not same directory\n" if path($file->path)->dirname ne $tmpdir;

```

### Expected behavior
Script should exit successfully.

### Actual behavior
Script dies with the upgraded `Mojo::Asset::File` not being located in `$tmpdir`.

**Comment by kraih** [comment]
The way the upgrade event is implemented currently this is impossible. But the example for the event actually shows that it's supposed to work. Guess we should call this a bug.
