### ISSUE TITLE
How to point to CA certs in version 8.32 with OpenSSL?

### ISSUE THREAD

**Issue by plk** [mojolicious/mojo#1465]
* Mojolicious version: 8.32
* Perl version: 5.24
* Operating system: SLES 11

### Steps to reproduce the behavior
Before version 8, the agent would honour `IO::Socket::SSL`'s search for CA certs in `/etc/ssl/certs`. This stopped working in version 8 and I switched to using `MOJO_CA_FILE`. This also seems to have stopped working in some recent version (haven't tried it recently). What is the recommended way now to point to custom (corporate mandated) CA certs when using OpenSSL?

### Expected behavior
CA certs are found

### Actual behavior
CA certs are not found

**Comment by Grinnz** [comment]
For Mojo::UserAgent, you can set the ca attribute: https://metacpan.org/pod/Mojo::UserAgent#ca

**Comment by Grinnz** [comment]
Note that both MOJO_CA_FILE and the IO::Socket::SSL defaults should still be honored; if you find they are not, this would be a bug.

**Comment by plk** [comment]
I also tried the 'ca' attribute - no luck. It used to with with IO::Socket:SSL defaults until I upgraded to Mojolicious 8.

**Comment by plk** [comment]
OpenSSL is 1.1.0e

I have tried the env variables `SSL_ca_path`, `SSL_ca_file` and `MOJO_CA_FILE` and none of them pick up the certs in `/etc/ssl/certs` or the file `/etc/ssl/ca-bundle.pem`

**Comment by kraih** [comment]
We rely entirely on `IO::Socket::IP` now, and merely pass a few config parameters along.

**Comment by Grinnz** [comment]
SSL_ca_path is not an environment variable it would recognize, see https://metacpan.org/pod/IO::Socket::SSL#IO::Socket::SSL::default_ca([-path|dir|-SSL_ca_file-=-...,-SSL_ca_path-=%3E-...-])%3E for how you could affect IO::Socket::SSL's defaults.

**Comment by plk** [comment]
Hmm, I tried this with path and file (pointing to a file which has worked for years) and also the two env vars mentioned there (`SSL_CERT_FILE` and `SSL_CERT_DIR`) but nothing seems to work. Can I assume that this really does work and there is a problem with my environment? We are using this internally and are using our own CAs and certs. This has worked fine for literally years (until version 8 when the I`O::Socket::SSL` autodetection seems to break) but now I can't seem to get anything to work.

**Comment by kraih** [comment]
We test TLS support in great detail. https://github.com/mojolicious/mojo/blob/master/t/mojo/ioloop_tls.t

**Comment by plk** [comment]
Apologies, this particular issue was due to an expired server cert. However, the issue with IO::Socket::SSL auto-detection persists - since version 8, I have to use `MOJO_CA_FILE` as the automatic use of `/etc/ssl/certs` on linux stopped working.

**Comment by kraih** [comment]
@plk We don't do any detection, that's entirely up to `IO::Socket::SSL`.
