### ISSUE TITLE
Mojo::Request::_parse_env should add the port from SERVER_PORT

### ISSUE THREAD

**Issue by EvanCarroll** [mojolicious/mojo#1466]
### Steps to reproduce the behavior

host mojo on non-port 80 in cgi mode.
calculate a url with url_for()->to_abs->to_string;
see the port is not there.

### Expected behavior
port should be listed.

### Actual behavior
port is not listed.

On current examination what we're doing is parsing `HTTP_HOST`

```
    # Extract headers
    my $headers = $self->headers;
    my $url     = $self->url;
    my $base    = $url->base;
    for my $name (keys %$env) {
      my $value = $env->{$name};
      next unless $name =~ s/^HTTP_//i;
      $name =~ y/_/-/;
      $headers->header($name => $value);

      # Host/Port
      $value =~ s/:(\d+)$// ? $base->host($value)->port($1) : 
  $base->host($value)
        if $name eq 'HOST';
    }
```

But we shouldn't be parsing that at all, because it's non-standard and not mentioned anywhere. What we're supposed to be parsing is `SERVER_PORT` which is actually in the spec, and it's in the tests.

I believe we created the implementation from dumps that offered more than the spec required. But in doing so we shouldn't ignore the spec which says where that information should be sourced.

----

Spec RFC 3875 https://tools.ietf.org/html/rfc3875

> 4.1.15.  SERVER_PORT
> 
>    The SERVER_PORT variable MUST be set to the TCP/IP port number on
>    which this request is received from the client.  This value is used
>    in the port part of the Script-URI.
> 
>       SERVER_PORT = server-port
>       server-port = 1*digit
> 
>    Note that this variable MUST be set, even if the port is the default
>    port for the scheme and could otherwise be omitted from a URI.

**Comment by kraih** [comment]
We need a reproducible test case to investigate. See [existing tests](https://github.com/mojolicious/mojo/blob/master/t/mojo/request_cgi.t) for examples.

**Comment by kraih** [comment]
And in cases where RFCs are involved references to the relevant spec sections. If that's not possible we need as much information as possible about the environment (all the server specific stuff).

**Comment by EvanCarroll** [comment]
@kraih I can provide a new test, but for the record this should be sufficient because it shows

* when there is a difference the one we want -- SERVER_PORT -- is taken.
* implementations that break the spec, we still function and parse the port from http_host.

**Comment by EvanCarroll** [comment]
What exactly is requested? A totally new test that doesn't use common code from the current tests?

**Comment by kraih** [comment]
I still can't say if this is a bug or not. And there have been no recent updates.

**Comment by EvanCarroll** [comment]
There are tests provided with the patch.

**Comment by EvanCarroll** [comment]
I've updated the OP here with bolded text for further clarification. @kraih If you don't want the patch feel free to keep the current behavior, it's just in violation of the spec.

**Comment by kraih** [comment]
The patch just modifies the behaviour of existing tests without explanation. Which pretty much forces me to reject your proposal.

**Comment by kraih** [comment]
Side note: Over the years we've probably lost all CGI know how we once had on the team as the technology vanished from the mainstream. Personally i've not deployed anything with CGI for maybe 10 years. So please keep that in mind for any patches you submit and make the explanations for why changes are needed after all those years with the appropriate level of verbosity.

**Comment by EvanCarroll** [comment]
> The patch just modifies the behaviour of existing tests without explanation. Which pretty much forces me to reject your proposal.All of your tests 

Just to be clear, I did update the ticket at the top and bolded the explanation. I'll try to make it even more clear though.

**Comment by kraih** [comment]
If changing existing tests is a hard requirement for your patch, then i have to reject the proposal. And we'll end the discussion here with that.

**Comment by EvanCarroll** [comment]
Nope, it's not. It's always easy to copy and paste. It's harder to write decent and efficient tests. I'll get right on it.

**Comment by EvanCarroll** [comment]
@kraih there ya go. how is that? I copied and pasted the test and issued another parse. only tests added now.

Sorry, I wouldn't prefer this if it was my own project, but it's easy enough. Any more clarification needed?
