### ISSUE TITLE
OS versions used in Travis CI is too old to see TLS 1.3 bug

### ISSUE THREAD

**Issue by marked** [mojolicious/mojo#1470]
* Mojolicious version: 8.32
* Perl version: 5.10, 5.12, 5.14, 5.16, 5.18, 5.20, 5.22, 5.24, 5.26, 5.28, 5.30
* Operating system: xenial and trusty

As seen in Issue #1431
 
### Steps to reproduce the behavior

Build on xenial or trusty
Build on Ubuntu bionic
Build on Travis CI

### Expected behavior

Build on xenial or trusty expected pass
Build on Ubuntu bionic expected fail
Travis CI build expected fail 
(old half should pass and new half should fail resulting in overall fail)

### Actual behavior

Build on xenial or trusty passes
Build on Ubuntu bionic fails
Travis CI build passes

**Comment by kraih** [comment]
Since this is related to #1431, i'll assume it is resolved now.
