### ISSUE TITLE
Automated tests are passing when test build env is broken

### ISSUE THREAD

**Issue by marked** [mojolicious/mojo#1473]
* Mojolicious version: 8.34
* Perl version: 5.28, 5.12, 5.10
* Operating system: Travis-CI bionic dist

### Steps to reproduce the behavior
Build logs are already viewable here:
https://travis-ci.com/marked/mojo/builds/149593882

Or trigger new test build using a yml file set to bionic:
https://github.com/marked/mojo/blob/aabea1637a0f8d7ba9618110af6905e14730e5ea/.travis.yml

### Expected behavior
Automated tests should fail when test build environment is broken.
That is the environments for 5.28, 5.12, 5.10 are currently broken when using bionic.

### Actual behavior
Tests passed 3 times by picking up system perl with wrong version number, and skipping tests with missing CPAN modules.

**Comment by marked** [comment]
Adding these lines to .travis.yml fixes it
```
before_install:
  - which perl | grep perlbrew
```

3x Builds now flagged as errored rather than passing:
https://travis-ci.com/marked/mojo/builds/150001306

Opening PR

**Comment by kraih** [comment]
This report seems obsolete.
