### ISSUE TITLE
possible Mojo::JSON::decode_json bug

### ISSUE THREAD

**Issue by pavelsr** [mojolicious/mojo#1476]
* Mojolicious version: 8.33, Supervillain
* Perl version: v5.28.2
* Operating system: Linux Mint 19.2 Tina

### Steps to reproduce the behavior

```
$ cat test.pl 
use Mojo::JSON 'decode_json';
warn decode_json(undef);
$ perl test.pl 
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/local/share/perl5/site_perl/Mojo/JSON.pm line 39
```

### Expected behavior

I think `decode_json` must return undef

### Actual behavior

`decode_json` dies

**Comment by pavelsr** [comment]
Same problem if `decode_json('')`

**Comment by haarg** [comment]
The current behavior seems correct to me.

**Comment by pink-mist** [comment]
```Mojo::JSON``` implements ```RFC-8259``` in which you can see the [JSON Grammar](https://tools.ietf.org/html/rfc8259#section-2) being defined as follows:
```
    JSON-text = ws value ws
    [...]
    ws = *(
              %x20 /              ; Space
              %x09 /              ; Horizontal tab
              %x0A /              ; Line feed or New line
              %x0D )              ; Carriage return
    [...]
    value = false / null / true / object / array / number / string
    [...]
    false = %x66.61.6c.73.65   ; false
    null  = %x6e.75.6c.6c      ; null
    [...]
    string = quotation-mark *char quotation-mark
```
This means that an empty string is not valid JSON, it needs at the very least some quotation marks inside

**Comment by Grinnz** [comment]
If you think you might have an empty value instead of valid JSON, you can easily check `length $json` before attempting to decode.

**Comment by karenetheridge** [comment]
If it's a bug, it would be with the backend that is being used (Cpanel::JSON::XS in most cases, unless you twiddled some environment variables -- see the Mojo::JSON source, as it's not long).
