### ISSUE TITLE
Convert imports to using lists

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1484]
Convert all cases of `use Foo 'bar';` imports in Mojolicious to `use Foo qw(bar)`. Since it makes modifying the import list much easier and there are no known disadvantages. Code as well as docs need to be checked.

**Comment by dvinciguerra** [comment]
A WIP branch, need to convert some other found cases.

https://github.com/mojolicious/mojo/compare/master...dvinciguerra:convert-imports-to-using-lists

What do you think!? Any advice?

**Comment by kraih** [comment]
This is not a particularly hard task, but labour intensive. Please leave a comment if you attempt preparing a patch, so there's no race for who can finish it first. And don't just do the conversion with a script, check every case manually as well and make sure the formatting is still compliant with our rules.

**Comment by kraih** [comment]
And one more thing. For now leave out all `use Mojo::Base ...;` cases. We'll have to decide later what to do about them. We'll probably just keep them as is.

**Comment by dvinciguerra** [comment]
Thanks for reply!
I'm preparing a patch to solve that issue.
