### ISSUE TITLE
Mojo::DOM sometimes includes tags in output of all_text()

### ISSUE THREAD

**Issue by oalders** [mojolicious/mojo#1491]
```
* Mojo version: 8.17
* Perl version:  v5.26.1
* $ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.4 (19E287)
      Kernel Version: Darwin 19.4.0
```

### Steps to reproduce the behavior
```perl
#!/usr/bin/env perl

use strict;
use warnings;
use feature qw( say );

use Mojo::DOM ();
use Mojo::Util qw( trim );

my $data = do { local $/; <DATA> };
print_text($data);

$data =~ s{.*xml.*}{};
print_text( $data );

sub print_text {
    $data = shift;
    say $data;
    say '#' x 10;
    say trim(Mojo::DOM->new($data)->all_text);
    say '#' x 10;
}

__DATA__
<!DOCTYPE html>
<html>
   <body>
      <span>
         <?xml version="1.0" encoding="utf-8"?>
         <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 41 41" class="search-svg" xml:space="preserve">
            <path d="M16,0C7.2,0,0.1,7.2,0,15.9c0,8.8,7.2,15.9,15.9,15.9c3.8,0,7.3-1.3,10.1-3.6L38.7,41l2.3-2.3L28.4,26
               c2.3-2.8,3.6-6.3,3.6-10.1C31.9,7.2,24.8,0,16,0L16,0z M16,3.2c7,0,12.7,5.7,12.7,12.7S23.1,28.7,16,28.7S3.3,23,3.3,15.9
               C3.3,8.9,9,3.2,16,3.2L16,3.2z"/>
         </svg>
      </span>
      <script id="foo" type="text/html">
         <div></div>
      </script>
   </body>
</html>
```
### Expected behavior
I expect the output in both cases to contain no text.

### Actual behavior
The first call to `print_text()` (which includes the XML declaration inside the `<span>` does what I would expect.  Once the XML declaration has been removed, the output includes `<div></div>`.

This is not what I would expect because if the `<script>` block defines a `type` and that `type` is not a Javacscript MIME type, then 
> The embedded content is treated as a data block which won't be processed by the browser. Developers must use a valid MIME type that is not a JavaScript MIME type to denote data blocks. The src attribute will be ignored.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

Full output of script:

```bash
<!DOCTYPE html>
<html>
   <body>
      <span>
         <?xml version="1.0" encoding="utf-8"?>
         <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 41 41" class="search-svg" xml:space="preserve">
            <path d="M16,0C7.2,0,0.1,7.2,0,15.9c0,8.8,7.2,15.9,15.9,15.9c3.8,0,7.3-1.3,10.1-3.6L38.7,41l2.3-2.3L28.4,26
               c2.3-2.8,3.6-6.3,3.6-10.1C31.9,7.2,24.8,0,16,0L16,0z M16,3.2c7,0,12.7,5.7,12.7,12.7S23.1,28.7,16,28.7S3.3,23,3.3,15.9
               C3.3,8.9,9,3.2,16,3.2L16,3.2z"/>
         </svg>
      </span>
      <script id="foo" type="text/html">
         <div></div>
      </script>
   </body>
</html>

##########

##########
<!DOCTYPE html>
<html>
   <body>
      <span>

         <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 41 41" class="search-svg" xml:space="preserve">
            <path d="M16,0C7.2,0,0.1,7.2,0,15.9c0,8.8,7.2,15.9,15.9,15.9c3.8,0,7.3-1.3,10.1-3.6L38.7,41l2.3-2.3L28.4,26
               c2.3-2.8,3.6-6.3,3.6-10.1C31.9,7.2,24.8,0,16,0L16,0z M16,3.2c7,0,12.7,5.7,12.7,12.7S23.1,28.7,16,28.7S3.3,23,3.3,15.9
               C3.3,8.9,9,3.2,16,3.2L16,3.2z"/>
         </svg>
      </span>
      <script id="foo" type="text/html">
         <div></div>
      </script>
   </body>
</html>

##########
<div></div>
##########
```

**Comment by Grinnz** [comment]
The contents of script tags are not HTML.

**Comment by Grinnz** [comment]
I would think the contents of script tags should be unconditionally left out of all_text but not sure.

**Comment by kraih** [comment]
That's not a bug, `script`, `style`, `title` and `textarea` are special cases.

**Comment by oalders** [comment]
This is some `knockout.js` embedded into HTML:

```html
<h2>Participants</h2>
Here are the participants:
<div data-bind="template: { name: 'person-template', foreach: people }"></div>
 
<script type="text/html" id="person-template">
    <h3 data-bind="text: name"></h3>
    <p>Credits: <span data-bind="text: credits"></span></p>
</script>
 
 function MyViewModel() {
     this.people = [
         { name: 'Franklin', credits: 250 },
         { name: 'Mario', credits: 5800 }
     ]
 }
 ko.applyBindings(new MyViewModel());
```

**Comment by oalders** [comment]
This is some `knockout.js` embedded into HTML:

```html
<h2>Participants</h2>
Here are the participants:
<div data-bind="template: { name: 'person-template', foreach: people }"></div>
 
<script type="text/html" id="person-template">
    <h3 data-bind="text: name"></h3>
    <p>Credits: <span data-bind="text: credits"></span></p>
</script>
 
 function MyViewModel() {
     this.people = [
         { name: 'Franklin', credits: 250 },
         { name: 'Mario', credits: 5800 }
     ]
 }
 ko.applyBindings(new MyViewModel());
```

**Comment by kraih** [comment]
Leaving them out of `all_text` output is arguable.

**Comment by oalders** [comment]
Sure, but why the change in behaviour with the XML declaration?

**Comment by Grinnz** [comment]
What I mean is, the contents of script tags are never rendered by the browser, and thus are not part of the DOM tree, even if they are declared to contain HTML.

**Comment by oalders** [comment]
The browser will ignore the data sections, so it won't treat the contents as text.  So, that seems like surprising behaviour to me that `Mojo::DOM` treats it as text.

**Comment by oalders** [comment]
> What I mean is, the contents of script tags are never rendered by the browser, and thus are not part of the DOM tree, even if they are declared to contain HTML.

We are on the same page then. :)

**Comment by kraih** [comment]
In XML the `script` tag is not special.

**Comment by oalders** [comment]
So, the XML declaration is not scoped to the `<span>` and it overrides the original `DOCTYPE` in this case?

**Comment by kraih** [comment]
A long time ago we actually discussed this and decided that the `text`/`all_text` methods are not meant to replicate any browser behaviour. It's just too hard.

**Comment by Grinnz** [comment]
Replicating browser behavior regarding layout and such is definitely too difficult, but I think it would be reasonable to exclude contents of <script> from all_text as a special case. On the other hand it may be better to just encourage people to customize their logic as they need because all_text is not gonna be smart enough for everything you need.

**Comment by Grinnz** [comment]
> So, the XML declaration is not scoped to the `<span>` and it overrides the original `DOCTYPE` in this case?

Correct, XML mode is a global property of the Mojo::DOM document.

**Comment by oalders** [comment]
> On the other hand it may be better to just encourage people to customize their logic as they need because all_text is not gonna be smart enough for everything you need.

So, a doc patch?

**Comment by kraih** [comment]
There seems to be quite a bit of support for excluding `<script>` and friends from `all_text` output on IRC. So perhaps we should consider a patch.

**Comment by kraih** [comment]
I think this might deserve to be added.

**Comment by kraih** [comment]
This is part of the 9.0 release.
