### ISSUE TITLE
Suggestion for documentation improvement: Mojolicious::Validator

### ISSUE THREAD

**Issue by daleif** [mojolicious/mojo#1495]
In `Mojolicious::Validator` the documentation mentions `checks` as an attribute. But it also implements `filters`. 

Might be an idea to mention `filters` as well, at least for symmetry. Might be useful to check if say `not_empty` is present or not.

BTW: in the documentation, what exactly is the intention of the line 

```
$validator = $validator->checks({size => sub {...}});
```

that replaces the checks with `size` and `size` is never sent through `DynamicMethods`

**Comment by kraih** [comment]
That was actually a bug. :)

**Comment by daleif** [comment]
I assume that the bug was that it was missing

Though I still do not understand what 

```
$validator = $validator->checks({size => sub {...}});
``` 
is good for? as it seems rather dangerous compared to adding it via `add_check`

**Comment by kraih** [comment]
It's just reference documentation, it doesn't say anything about behaviour.

**Comment by daleif** [comment]
Ok, that is not at all clear for a new user.
