### ISSUE TITLE
Declaring routes to non-controller methods can be a silent failure

### ISSUE THREAD

**Issue by Ovid** [mojolicious/mojo#1507]
* Mojolicious version: 8.12
* Perl version: 5.26.2
* Operating system: macOS Catalina 10.15.4

### Steps to reproduce the behavior

Declare a route to a method which is in a non-controller class. When trying to call that route, you get a 404, even though the Mojolicious 404 page shows that the route exists. It's quite mystifying (I've hit variants of this "404 on a defined route" several times).

As it turns out, `Mojolicious::Routes` issues a debug message when this occurs. Depending on your log level, this could be  a silent failure.

### Expected behavior

Trying to route to something we cannot route to means the app "can't continue." This should be a `fatal` or `error` log message. Preferably, it should throw an exception on route declaration, but I'm assuming it does not for either backwards-compatibility or some other behavior I'm unfamiliar with.

### Actual behavior

Mojolicious allows you to declare routes to methods, even if the class containing the method is not a controller. Thus, you wind up with a weird thing where you get a 404, but the Mojolicious 404 page shows the route is defined. I only discovered this because buried deep in the voluminous output, was a `debug` level message, not even `error`, which read:

      [2020-03-12 09:57:35.98665] [21018] [debug] [b80170ae] Class "SomeClass::Controller::Connection" is not a controller

Which I tracked down to [this code in lib/Mojolicious/Routes.pm](https://github.com/mojolicious/mojo/blob/master/lib/Mojolicious/Routes.pm#L128):

```perl
  # Try to load all classes
  my $log = $c->helpers->log;
  for my $class (@classes) {

    # Failed
    next unless defined(my $found = $self->_load($class));
    return !$log->debug(qq{Class "$class" is not a controller}) unless $found;

    # Success
    return $class->new(%$c);
  }
```

So we try to load the class, but if we can't, we get a debug level message. Depending on your log level, that could be a silent failure (it was for me at first).

It would be nice if known errors were trapped and reported on as soon as possible rather than at runtime.

We've solved this locally by making this a fatal error at load time.

**Comment by kraih** [comment]
Yes, that exists for backward compatibility and is not easily changed. Getting rid of dynamic routing with `/:controller/:action` would break many many old applications. Of course we don't encourage the practice anymore.

**Comment by Ovid** [comment]
Thanks for the clarification. Would upping the log level to `error` break things badly? Wouldn't that just be a log entry and not impact the running code?

**Comment by kraih** [comment]
Yes, that could result in logs getting flooded after a Mojolicious upgrade. We intentionally made `debug` level messages easy to ignore in production.

**Comment by kraih** [comment]
Just double checked, in the documentation there is only one case where we still mention the feature.
```
  # /           -> {controller => 'foo',   action => 'bar'}
  # /users      -> {controller => 'users', action => 'bar'}
  # /users/list -> {controller => 'users', action => 'list'}
  $r->get('/:controller/:action')->to('foo#bar');

Special stash values like C<controller> and C<action> can also be placeholders,
which is very convenient especially during development, but should only be used
very carefully, because every controller method becomes a potential route. 
```
So i'm not opposed to making more changes to discourage its use further. But there might be pushback from the community if it goes too far.

**Comment by kraih** [comment]
This is now an [official proposal](https://github.com/mojolicious/mojo/discussions/1663#discussioncomment-342395) for the 9.0 release. No matter the outcome, i'll consider this issue resolved, one way or the other.

**Comment by kraih** [comment]
Actually, while we can get rid of `:controller` and `:action` routing in 9.0, i was outvoted on getting rid of automatic rendering. Which still requires us to consider cases like the one described here as a 404 case. Since there can be templates without controllers/actions. So i'm afraid this is a WONTFIX after all. Sorry.

**Comment by kraih** [comment]
Actually, your specific case is now considered an exception after all. :grin: https://github.com/mojolicious/mojo/commit/bed61754461e19dc4724738389880ac0237ca89c It's just actions that still need to be optional, but declared controllers are always required to exist.
