### ISSUE TITLE
Fix GitHub Actions to work with Perl 5.16 and 5.18

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1508]
For [some reason](https://github.com/mojolicious/mojo/runs/650564585) our GitHub Actions do not install `Sub::Util` on Perl 5.16 and 5.18. So we had to [disable](https://github.com/mojolicious/mojo/commit/face9a1f2bde963cfb7ede31002c3d10c8988b1e) those versions for now. But they are rather important and we'd like to get them back. So this needs to be investigated!

**Comment by tianon** [comment]
This was fixed somewhere in/before 0dabab8888c952e0ae17c698057c7c1c67b14c88 and c570eafdcbeed7f0f2e6b4d72876fe4305296ea3, right?

(5.16 and 5.18 are enabled and green on master :sweat_smile:)

**Comment by Grinnz** [comment]
It was worked around by manually listing the deps that need to be installed. It still won't do it automatically for some reason and only on these versions.

**Comment by tianon** [comment]
Ah right, sorry I missed that @Grinnz. :facepalm: 

Did some testing locally on 5.18 locally vs 5.20; in both cases, I started with `cpanm -n --self-upgrade` to help rule out `cpanm` version inconsistencies (and used the same Docker images the CI is using, FWIW):

```console
$ perl --version | grep 'This is perl' 
This is perl 5, version 18, subversion 4 (v5.18.4) built for x86_64-linux
$ cpanm --version | head -2
cpanm (App::cpanminus) version 1.7044 (/usr/local/bin/cpanm)
perl version 5.018004 (/usr/local/bin/perl)
$ cpanm --showdeps .
--> Working on .
Configuring /cwd ... OK
perl~5.016
```

vs:

```console
$ perl --version | grep 'This is perl' 
This is perl 5, version 20, subversion 3 (v5.20.3) built for x86_64-linux
$ cpanm --version | head -2
cpanm (App::cpanminus) version 1.7044 (/usr/local/bin/cpanm)
perl version 5.020003 (/usr/local/bin/perl)
$ cpanm --showdeps .
--> Working on .
Configuring /cwd ... OK
perl~5.016
ExtUtils::MakeMaker
IO::Socket::IP~0.37
Sub::Util~1.41
```

In both cases, I get the same `PREREQ_PM` output in the `Makefile`, but the generated `MYMETA.yml` contents are consistent with the incorrect list we're getting from `cpanm --showdeps`.  To that end, I removed the manual installation of both `Sub::Util` and `IO::Socket::IP` and instead added a manual upgrade of both `App::cpanminus` and `ExtUtils::MakeMaker` and got the correct result: https://github.com/tianon/mojo/actions/runs/116098123

I'll be opening a PR shortly! :+1:

**Comment by karenetheridge** [comment]
I'm bothered by unexplained "for some reason" statements :)  Something is seriously wrong in the toolchain setup if prereqs are not being detected.

**Comment by tianon** [comment]
Totally agreed!  As I noted in https://github.com/mojolicious/mojo/pull/1525#issuecomment-634258918, I did a little testing and found that EUMM version 6.68 is enough to fix it (up from 6.66 included in Perl 5.18).  However, when adding `CONFIGURE_REQUIRES => {'ExtUtils::MakeMaker' => '6.68'}` to our `Makefile.PL`, it doesn't work, and I'm fairly sure it's falling prey to the same EUMM bug that's affecting our `PREREQ_PM`. :face_with_head_bandage:

**Comment by Grinnz** [comment]
Note that configure requires are not relevant to MYMETA.json, they would be picked up from META.json before Makefile.PL is even run (so while it may not fix the CI it would be sufficient to fix users running into this case).

**Comment by karenetheridge** [comment]
the presence of `CONFIGURE_REQUIRES => {'ExtUtils::MakeMaker' => '6.68'}` in Makefile.PL should put the appropriate entry into META.json, and CI should pick it up from there.  (If the CI tools are *not* reading configure-requires out of META.json before running Makefile.PL, then there are going to be more issues not just with this distribution, but in any dist that does anything "interesting" in their Makefile.PL, for example using Devel::AssertOS or ExtUtils::CheckCompiler.)

**Comment by Grinnz** [comment]
In this case there is no META.json stored in the repository because tooling isn't in use that makes that easy and the only use of META.json in the repository is to support configure_requires for CI, which hasn't been needed yet.

**Comment by karenetheridge** [comment]
ah okay, thanks for the clarification. I thought CI was testing the result of 'make dist', which *would* have a META.json properly generated, not the bare repository.

**Comment by Grinnz** [comment]
Only if it was using a new enough EUMM to run make dist :neutral_face:
