### ISSUE TITLE
Mojo::URL->new as an alias in ojo

### ISSUE THREAD

**Issue by dex4er** [mojolicious/mojo#1514]
* Mojolicious version: 8.43
* Perl version: 5.30.0
* Operating system: linux

I love `perl -Mojo` and it is awesome for simple oneliners. Would be possible to add `Mojo::URL->new()` to `ojo` module? Ie. as `l` function maybe.

Sometimes I would like to parse URL addresses and then I would find `perl -Mojo` extremely helpful:

ie.

`perl -Mojo -E 'say l("index.html")->to_abs(l("http://example.com"))`

rather than

`perl -Mojo -E 'say Mojo::URL->new("index.html")->to_abs(Mojo::URL->new("https://example.com"))'`

**Comment by kiwiroy** [comment]
Would [this](https://github.com/mojolicious/mojo/compare/master...kiwiroy:ojo-l) make it?

**Comment by dex4er** [comment]
@kiwiroy looks great!

**Comment by dex4er** [comment]
@kiwiroy could you ping your PR? I provided maybe a little better example of usage. Maybe it will be accepted by Kraith
