### ISSUE TITLE
Mojo::Promise objects sometimes produce side-effects the 2nd time resolve is called on them

### ISSUE THREAD

**Issue by akarelas** [mojolicious/mojo#1515]
* Mojolicious version: current `unhandled_promises` branch (`3d91e75`)
* Perl version: 5.30.2
* Operating system: Linux 5.3.0-51

### Steps to reproduce the behavior
```perl
say '--- output section 1';
my $p1 = Mojo::Promise->new;
my $p2 = Mojo::Promise->new;
$p2->then(sub {say 'hi 2'});
$p2->resolve($p1);

Mojo::IOLoop->one_tick;

say '--- output section 2';
$p2->resolve(10);

Mojo::IOLoop->one_tick;
```

The above outputs:

```
--- output section 1
--- output section 2
hi 2
```

### Expected behavior

While I'm not sure about section 1 of the output, section 2 should be empty, since the second call to resolve should be a no-op, according to https://tc39.es/ecma262/#sec-promise-resolve-functions bullet points 5 and 6

### Actual behavior

Section 2 of the output was not empty

**Comment by abbottmg** [comment]
I think the example script leaves `$p2` unresolved until the `$p2->resolve(10)` call in the second section; if I'm reading `_settle` correctly, the first call is the equivalent of `$p1->then(sub { $p2->resolve(@__)  }, sub { $p2->reject(@_) }`. This is basically steps 12-14 of your ECMA reference.

The end result is that we're telling `$p2` to depend on `$p1` for resolution but never resolving `$p1`. The second call passes a non-promise value, `$p2` sees it's not resolved (and doesn't know it's already agreed to depend on `$p1`) and so resolves.

Adding `$p1->resolve()` a tick prior to our `resolve(10)` shows behavior we'd expect:

```perl
# example 1
say '--- output section 1';
my $p1 = Mojo::Promise->new;
my $p2 = Mojo::Promise->new;
$p2->then(sub {say 'hi 2'});
$p2->resolve($p1);
$p1->resolve(); # resolve p1 in same time slot as p2
Mojo::IOLoop->one_tick;

say '--- output section 2';
$p2->resolve(10);

Mojo::IOLoop->one_tick;
```

```perl
# example 2
say '--- output section 1';
my $p1 = Mojo::Promise->new;
my $p2 = Mojo::Promise->new;
$p2->then(sub {say 'hi 2'});
$p2->resolve($p1);
Mojo::IOLoop->one_tick; # tick 1

$p1->resolve(); # resolve p1 later, but still a tick before we retry p2
Mojo::IOLoop->one_tick; # tick 2

say '--- output section 2';
$p2->resolve(10);

Mojo::IOLoop->one_tick; # tick 3
```

In both cases, I get the following output:
```
--- output section 1
hi 2
--- output section 2
```

Resolving `$p1` a tick before we retry is important; its resolution will defer its *thenCallbacks* to the next tick, so in the latter example, `$p1` resolves between ticks 1 and 2, but `$p2` only gets the memo *during* tick 2, and can be pre-empted if we try our second resolve call before then. Note that even

```perl
# example 3
$p1->resolve();
Mojo::IOLoop->next_tick(sub { $p2->resolve(10) });
Mojo::IOLoop->one_tick; # tick 2
```
should work, as the first line will enqueue its work into the tick "body" before the second line does.

**Comment by kraih** [comment]
I believe we already considered this a WONTFIX.
