### ISSUE TITLE
$promise1->resolve($promise1) should reject an exception

### ISSUE THREAD

**Issue by akarelas** [mojolicious/mojo#1517]
* Mojolicious version: current `unhandled_promises` branch (`3d91e75`)
* Perl version: 5.30.2
* Operating system: Linux 5.3.0-51

### Steps to reproduce the behavior

```perl
my $p1 = Mojo::Promise->new;
$p1->then(sub {say "p1 resolved: @_"}, sub {say "p1 rejected: @_"});

$p1->resolve($p1);

Mojo::IOLoop->one_tick;
```

The above does not output an exception (or something resembling it), while it should.

### Expected behavior
According to https://tc39.es/ecma262/#sec-promise-resolve-functions (point 7), `$p1` should reject with a result of `selfResolutionError` which is a `TypeError` object.

The script should output something, perhaps something like this:

`p1 rejected: ... at line ...`

### Actual behavior

The above script didn't produce any output.

**Comment by kraih** [comment]
Patch did not pass the vote.
