### ISSUE TITLE
Helper "name.subname" not available as name->subname in template

### ISSUE THREAD

**Issue by mohawk2** [mojolicious/mojo#1524]
* Mojolicious version: 8.50
* Perl version: 5.26.1
* Operating system: Ubuntu 18.04

### Steps to reproduce the behavior
```perl
use Mojolicious::Lite;
use Test::Mojo;
use Test::More;

helper 'top.bottom' => sub { "middle" };
helper 'middle' => sub { "side" };

get '/1' => 'template1';
get '/2' => 'template2';
get '/3' => 'template3';

my $t = Test::Mojo->new;
$t->get_ok('/1')->content_is("side\n");
$t->get_ok('/2')->content_is("middle\n");
$t->get_ok('/3')->content_is("middle\n");

done_testing;

__DATA__

@@ template1.html.ep
%= middle

@@ template2.html.ep
%= app->top->bottom

@@ template3.html.ep
%= top()->bottom
```

### Expected behavior
Should not fail test.

### Actual behavior
Fails test.

The second template shows a workaround, which is to use the `app` helper to access the desired helper. This should either be documented or fixed.

**Comment by kraih** [comment]
That's a documented and tested feature.

**Comment by mohawk2** [comment]
Fair enough! I did spend quite a while looking, as well as quite a while crafting the above test case. Can you at least point me to where in the docs it's documented that the "x.y" format can't be used in a template?

**Comment by kiwiroy** [comment]
This has caught me out, too, but in a slightly different way.

https://mojolicious.org/perldoc/Mojolicious/Guides/Rendering#Adding-helpers

> Similar to stash values, you can use a prefix like myapp.* to keep helpers from getting exposed in templates as functions, and to organize them into namespaces as your application grows. Every prefix automatically becomes a helper that returns a proxy object containing the current controller object and on which you can call the nested helpers.

**Comment by mohawk2** [comment]
Right, that bit is not very visible. It seems to me that organising helpers into a namespace (my intent) doesn't necessarily mean I wanted to hide them from templates (I didn't). At least the doc should suggest the workaround of using `app` as in my case 2.

@kiwiroy What do you think?

**Comment by mohawk2** [comment]
A way to achieve namespacing, while overcoming the hiding aspect, but preserving back-compatibility, might be to prefix the given helper name with an otherwise invalid character such as `*`.

**Comment by Grinnz** [comment]
Any non-word character causes its exclusion from templates. See https://metacpan.org/release/Mojolicious/source/lib/Mojolicious/Plugin/EPRenderer.pm#L49

**Comment by mohawk2** [comment]
@Grinnz Thanks. Is it unreasonable to wish that to be spelled out a bit more in the Rendering guide, and possibly specify the idea of using `app->` to achieve namespacing? I copied the idea of using a namespace from working on Yancy, and it seems to me a really good practice even for things that want using in templates.
