### ISSUE TITLE
Docs: Mojolicious::Renderer->render example is misleading

### ISSUE THREAD

**Issue by mbudde** [mojolicious/mojo#1527]
* Mojolicious version: 8.51

The current example snippet in the [documentation of `Mojolicious::Renderer->render`](https://mojolicious.org/perldoc/Mojolicious/Renderer#render) is:
```perl
my ($output, $format) = $renderer->render(Mojolicious::Controller->new, {
  template => 'foo/bar',
  foo      => 'bar'
});
```
This lead me to believe that `render` takes the template name from the hash-ref argument, but the code reveals that it takes it from the stash:
https://github.com/mojolicious/mojo/blob/86083bc9b8fee95b87fbe4d44876013c1290a6db/lib/Mojolicious/Renderer.pm#L85
It looks like the documentation got out of sync with this change: https://github.com/mojolicious/mojo/commit/e7f6bef1b46b181ab85cf4c45d57991ad072a085#diff-ccf996555125c90064b288a0e4c139c5

**Comment by kraih** [comment]
Thanks, you are correct.
