### ISSUE TITLE
Mojo::Promise Synopsis code not running due to small typo

### ISSUE THREAD

**Issue by dmanto** [mojolicious/mojo#1535]
https://github.com/mojolicious/mojo/blob/4e99cb1b885b1caaf62174a9a51e1a8f80704136/lib/Mojo/Promise.pm#L272

Complains that &main::get is undefined. I guess it shoud return the "get_p" promise, like:

```perl
return get_p('https://metacpan.org');
```

With this fix code runs ok

**Comment by CandyAngel** [comment]
Thanks for reporting, will have it fixed today.
