### ISSUE TITLE
Mojo::UserAgent proxy problem

### ISSUE THREAD

**Issue by pavelsr** [mojolicious/mojo#1539]
@kraih, Mojo::UserAgent may have problem with using proxies.
Please have a look.
https://stackoverflow.com/questions/62952724/change-public-ip-using-mojouseragent

* Mojolicious version: 8.42, Supervillain
* Perl version: v5.26.1, linux
* Operating system: Linux Mint 19.2 Tina (Linux 4.15.0-54-generic)

**Comment by kraih** [comment]
Please do not notification spam me, or i'm forced to block you.
