### ISSUE TITLE
'test' command dies without arguments

### ISSUE THREAD

**Issue by frag** [mojolicious/mojo#1542]
* Mojolicious version: 8.57
* Perl version: 5.18.2
* Operating system: Linux Mint 17.1 

### Steps to reproduce the behavior
$ mojo generate app myapp
$ cd myapp
$ ./script/myapp test 
Can't locate object method "rel_dir" via package "Mojo::Home" at /home/frag/perl5/lib/perl5/Mojolicious/Command/test.pm line 15.
$ ./script/myapp test -h
Usage: APPLICATION test [OPTIONS] [TESTS]

  ./myapp.pl test
  ./myapp.pl test t/foo.t
  ./myapp.pl test -v t/foo/*.t

### Expected behavior
According to the output of './script/myapp test -h', you should be able to use the 'test' command without having to pass it any scripts as arguments; it will find the ./t/ directory and run the tests in there.

### Actual behavior
Instead, Mojolicious::Command::test dies, in run(), when it attempts to call rel_dir() on a Mojo::Home object. Mojo::Home does not have any rel_dir() method, just rel_file(). It appears that rel_dir() was removed in v 7.31. I am not familiar enough with Mojolicous to suggest how to fix this.

Also, please note that test.pm line 16 also calls '$home->list_files()', which also does not exist in either Home.pm or File.pm.

**Comment by kraih** [comment]
The test command doesn't actually exist anymore.

**Comment by Grinnz** [comment]
This command was removed in 8.0. Unfortunately with the way CPAN installations work, you probably still have the old file.

**Comment by frag** [comment]
Well, that would explain it. I assume good old "prove -l t/" from the myapp directory is the appropriate way to run tests?

**Comment by Grinnz** [comment]
Sure. https://github.com/mojolicious/mojo/wiki/Upgrading#test-command-removed
