### ISSUE TITLE
Replace prettify.js with something maintained

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1544]
<img width="991" alt="pretty" src="https://user-images.githubusercontent.com/30094/89101775-83d53580-d403-11ea-84ed-ea37eea05318.png">

For syntax highlighting on the exception page we still use [prettify.js](https://github.com/googlearchive/code-prettify), which like most Google projects has been abandoned. So we should really replace it with something better, like [highlight.js](https://highlightjs.org).

There was actually [an attempt](https://github.com/mojolicious/mojo/pull/737) before, but it failed because of interdependencies with [mojolicious.org](https://mojolicious.org). That is no longer a problem, because assets are not shared anymore.

For testing you can use the included example app `examples/responses.pl` (`perl -Ilib examples/responses.pl daemon`). The screenshot above was taken of a request for `http://127.0.0.1:3000/res5`.

**Comment by zakame** [comment]
Let me try working on this :muscle: Is highlight.js still preferred, or should we be also looking for other libraries?

**Comment by kraih** [comment]
No preference really, it just should be maintained and work well.

**Comment by zakame** [comment]
Cool, I just pulled in @dotandimet's old PR, pruning out the old PODRenderer-related changes and updated with `master`, and it seems ok:

![image](https://user-images.githubusercontent.com/110625/96346888-cdfbb800-10d0-11eb-8660-ad0c89badea2.png)

Since its a 5-year-old PR though I'll check on the highlight.js itself for library upgrades and other changes...

**Comment by kraih** [comment]
Don't forget to check template/HTML highlighting too.

**Comment by zakame** [comment]
Yep, was just about to check in on that:

![image](https://user-images.githubusercontent.com/110625/96348290-2d11fa80-10da-11eb-9453-5e7b2942228e.png)

This is on latest highlight.js 10.2.1 a bit of tweaking on the CSS and `debug.html.ep` to follow the bare minimum instruction in https://highlightjs.org/usage . It seems smart enough to handle both template HTML and raw Perl code now without explicitly stating class in `<pre><code>` tags:

![image](https://user-images.githubusercontent.com/110625/96348349-ac073300-10da-11eb-9de3-14f49182ab36.png)

**Comment by kraih** [comment]
Would be nice to get [mojolicious.org](https://github.com/mojolicious/mojolicious.org) updated too.

**Comment by zakame** [comment]
Got around to trying this with mojolicious.org now, unforuntately it looks like the similar situation (or worse) in https://github.com/mojolicious/mojo/pull/737#issuecomment-72332396:

![image](https://user-images.githubusercontent.com/110625/97082901-8381ba80-163f-11eb-8516-de0187689402.png)

Types/package names and `<script>stuff in</script>` no longer highlight right, as compared to the original:

![image](https://user-images.githubusercontent.com/110625/97082970-de1b1680-163f-11eb-9e91-e1fe1f73de64.png)

Has to do with the engine itself, not recognizing the right tokens:

![image](https://user-images.githubusercontent.com/110625/97083085-87620c80-1640-11eb-8c98-3fbc6353343f.png)

vs

![image](https://user-images.githubusercontent.com/110625/97083095-93e66500-1640-11eb-9fda-fce442036e80.png)

Guess I'll block #1578 for now and look at the other aforementioned alternative (prism.js) to check...

**Comment by kraih** [comment]
That does look quite a bit better than https://github.com/mojolicious/mojo/pull/737#issuecomment-72332396 at least.

**Comment by zakame** [comment]
Yeah, on second thought... checking on mojodocs now, it does seem that highlightjs is more consistent for the embedded templates, e.g. for https://docs.mojolicious.org/Mojolicious/Guides/Rendering#Template-inheritance:

![image](https://user-images.githubusercontent.com/110625/97086591-c1d6a400-1656-11eb-8408-00508acab462.png)

vs

![image](https://user-images.githubusercontent.com/110625/97086597-cac77580-1656-11eb-8450-1591746e7169.png)

Even with the lack of highlights for types, for highlightjs at least it looks a lot less Angry Fruit Salad.

Let me post my current mojolicious.org changes now for further discussion :+1:
