### ISSUE TITLE
Mojo::DOM not properly handling HTML entities?

### ISSUE THREAD

**Issue by sdondley** [mojolicious/mojo#1545]
* Mojolicious version: 8.57
* Perl version: 5.24.4
* Operating system: macOS 10.15.5

### Steps to reproduce the behavior
create a new dom with html containing html entities
```
  my $blah = Mojo::DOM->new('<p>&nbsp;</p>');
  print $blah->content;
```

### Expected behavior
HTML entity should not be encoded

### Actual behavior
HTML entity is encoded with `\240`.

Workaround is here: https://stackoverflow.com/a/55604005/1641112

**Comment by Grinnz** [comment]
It is perfectly valid to include unicode characters such as U+00A0 directly in HTML. `&nbsp;` is usually used for convenience. Mojo::DOM makes no effort to preserve input exactly, only that the result will render the same.

**Comment by sdondley** [comment]
This utf8 stuff always makes my head spin. Can you please let me know if the link I put to the stackoverflow workaround is a good solution?

**Comment by sdondley** [comment]
Seems like there should be some acknowledgement of this issue somewhere in the docs. I'd be happy to do it but I don't understand he problem, exactly.

**Comment by Grinnz** [comment]
This has nothing to do with UTF-8. `&nbsp;` is an [HTML entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity). It is separately true that text usually must be encoded to UTF-8 to be saved to a file or transmitted across a socket. If you are outputting this HTML via a Mojolicious API, there is likely a way to handle this automatically.

**Comment by sdondley** [comment]
I'm not using the API. That probably accounts for my problems. I'm saving scraped HTML to a local file and then opening it up locally.

**Comment by Grinnz** [comment]
Then you should be encoding the text to UTF-8 as you save to the file, either by opening the file with something like `open my $fh, '>:encoding(UTF-8)', $path` or writing it with [write_text](https://metacpan.org/pod/File::Slurper#write_text($filename,-$content,-$encoding,-$crlf)) or [spew_utf8](https://metacpan.org/pod/Path::Tiny#spew,-spew_raw,-spew_utf8), or by encoding it manually to UTF-8 then writing those bytes.

**Comment by sdondley** [comment]
When I save the file locally using any of those methods you've mentioned (I've been down that road), the HTML gets double encoded.

**Comment by genio** [comment]
@sdondley That sounds as if you're conflating two things. UTF-8 encoding and HTML encoding are not the same thing. Encoding the text to UTF-8 will not alter the markup in any way at all. Maybe this would be best discussed in IRC: https://webchat.freenode.net/#mojo rather than on an issue. Once we discuss it out there and everyone is on the same page about the problem, we can handle this issue accordingly.

**Comment by Grinnz** [comment]
Please use the [support channels](https://docs.mojolicious.org/#SUPPORT) if you need further debugging assistance.
