### ISSUE TITLE
namespace method not returning expected value (Mojo::Dom)

### ISSUE THREAD

**Issue by sdondley** [mojolicious/mojo#1548]
* Mojolicious version: 8.57
* Perl version: 5.24.4
* Operating system: macOS 10.15.6

```
### Steps to reproduce the behavior
use Test::Most;
use Mojo::DOM;
use strict;
use warnings;

plan tests => 1;

my $html = '<html><head></head><body><booboo:p class="first">A paragraph.</p></body></html>';
my $ex = Mojo::DOM->new($html);
is $ex->at('booboo\:p')->namespace, 'booboo:p', 'fails'
```

### Expected behavior
test should pass

### Actual behavior
test fails with 

```
not ok 1 - fails

#   Failed test 'fails'
#   at t/02-namespace.t line 13.
#          got: undef
#     expected: 'booboo:p'
# Looks like you failed 1 test of 1.

```

**Comment by MartinMcGrath** [comment]
Are you confusing a namespace with a tag?

```
# displays booboo:p
say $ex->at('booboo\:p')->tag;
```

See also [namespace](https://github.com/mojolicious/mojo/blob/master/lib/Mojo/DOM.pm#L80), [ namespace tests](https://github.com/mojolicious/mojo/blob/master/t/mojo/dom.t#L590).

**Comment by sdondley** [comment]
I don't believe so, unless I'm badly misinterpreting/misreading the docs: https://docs.mojolicious.org/Mojo/DOM#namespace

**Comment by kraih** [comment]
A namespace prefix is not the same as a namespace.

**Comment by sdondley** [comment]
Might be helpful to show an example in the documentation of how to properly use it because I can't see to get the namespace method to return anything useful, even with this simple example:

```
my $html = '<html><head></head><body><svg:circle></svg:circle></svg></body></html>';
my $dom = Mojo::DOM->new($html);
my $namespace = $dom->at('svg\:circle')->namespace;
# $namespace is undef
```

**Comment by sdondley** [comment]
OK, got this example working:

my $html = '<svg xmlns:svg="www.example.com/svg"><svg:circle>3.14</svg:circle></svg>';
my $dom = Mojo::DOM->new($html);
my $namespace = $dom->at('svg > svg\:circle')->namespace;

# returns  'www.example.com/svg'

Just let me know if you want me to submit a patch for the docs with this example, please. Thanks.

**Comment by jberger** [comment]
There are examples of using namespace aliases in selectors in other methods. Yes perhaps the namespace method could have a working example as those do. If you do submit a patch use the actual svg namespace which you can grab from the other examples.

**Comment by kraih** [comment]
I consider this resolved.
