### ISSUE TITLE
Exposing socket options in Mojo::UserAgent?

### ISSUE THREAD

**Issue by melak** [mojolicious/mojo#1558]
This is more a question/RFE than an issue. Would there be a clean way to expose setting socket options (specifically, SO_KEEPALIVE and then (some of) TCP_KEEPCNT/TCP_KEEPIDLE/TCP_KEEPINTVL (I realise these are more icky than not as at least some of these tend not to be very portable)?

Basically, I have a situation where UserAgent has long-running connections that are mostly idle in the middle. When some firewall or something like that cuts the connection (reboots, whatnot) while it is idle and keepalive is not enabled on the socket, UserAgent will not recognize this until its final timeout. I have done some testing hacking Mojolicious to enable keepalive on the socket (I don't even remember anymore which part was it though), and it did solve the problem cleanly.

**Comment by kraih** [comment]
There is not, and i feel like it would be a bad idea if we ever hope to support HTTP/2 or 3.

**Comment by melak** [comment]
Fair enough, thanks for looking. Out of curiosity, why would this break HTTP/2? (A pointer is fine.)

**Comment by kraih** [comment]
Because HTTP/2 is multiplexed.

**Comment by kraih** [comment]
We are exposing all `IO::Socket::IP` options, but we won't go beyond that.
