### ISSUE TITLE
Some of the app names lead to the generation of broken code

### ISSUE THREAD

**Issue by Greenfactory** [mojolicious/mojo#1567]
* Mojolicious version: 8.60
* Perl version: 5.28.1
* Operating system: Debian GNU/Linux 10 (buster)

Some of the app names lead to the generation of broken code. So that this does not happen, it is worth checking the app name.

```
$ mojo generate app app-api
```

```
$ ./app-api/script/app-api
Can't find application class "app-api" in @INC.  (/home/gr...
```

```
$ perl -wc app-api/lib/app-api.pm 
Invalid version format (negative version number) at app-api/lib/app-api.pm line 1, near "package app"
syntax error at app-api/lib/app-api.pm line 1, near "package app-"
BEGIN not safe after errors--compilation aborted at app-api/lib/app-api.pm line 2.
```

In app-api.pm bad package name

```
$ head -1 app-api/lib/app-api.pm
package app-api;
```
Some code for this bug is here:
https://github.com/mojolicious/mojo/pull/1559

**Comment by kraih** [comment]
That's ok, we don't validate all input.
