### ISSUE TITLE
Remove extra whitespace from method/function signatures in docs

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1606]
It appears we might have made a small mistake with the change to subroutine signatures for the documentation. While closures are fine, for methods and functions we've used whitespace between the name and the signature. Which is very uncommon and should be changed.
```perl
sub startup ($self) {
```
should become become
```perl
sub startup($self) {
```

**Edit:** This is a more controversial topic than i thought, so we'll first discuss which option has more advantages for us and then decide.

**Comment by daleif** [comment]
Just wondering here. Is is just a formatting issue or is there an actual different between the two? (I find the first more readable, but I also tend to add spaces to `->`)

**Comment by kraih** [comment]
Just formatting. And it's the standard in style guides for most languages. So we'll do the same to make it easier to get started with Mojolicious.

**Comment by hyunjiLeeTech** [comment]
Hi, I would like to work on this task. Can you please assign me to this and clarify what document you want to remove extra whitespace (all source code files or an exact file)?

**Comment by kraih** [comment]
Actually, better wait with working on it. There are discussions ongoing currently on IRC which style we should promote with good arguments on both sides.

**Comment by kraih** [comment]
Allright, the **pro** argument i have is that style guides and books for most other languages that have has signatures for a long time tend to use no whitespace between name and signature. Examples are [JavaScript](https://google.github.io/styleguide/jsguide.html#features-functions), [Python](python.org/dev/peps/pep-0008), [Go](https://golang.org/doc/effective_go.html) and [Raku](https://docs.raku.org/language/functions). This is still new for Perl, so we should discuss this before jumping to action.

**Comment by Grinnz** [comment]
I prefer the current form with a space after the function name for a few reasons: it is the common style used in Perl code on CPAN, it is more consistent with anonymous subroutines which don't have a name and subroutines with attributes (which must have whitespace between the attribute and signature), and stylistically the whitespace distinguishes it from looking like a function call (though that is more important for anonymous subroutines in the middle of other statements).

**Comment by shadowcat-mst** [comment]
perl style wise,

    sub foo (&;$) {

was always the style for prototypes, plus it's consistent with

    sub ($x, $y) {

plus

    sub foo ($x, $y) {

feels more symmetrical with

    foo $x, $y;

although it's less symmetricl with

    foo($x, $y);

and

    $obj->foo($x, $y);

Honestly, my main opinion is "the version with the space is much more how existing perl code looks and I much prefer it for consistency with that and this seems to me to be a style difference in the same way foo_bar versus fooBar for local variable names is a style difference".

Also the first example with a signature in that raku link starts

    sub exclaim ($phrase) {

and reading through it, it seems like the examples in that doc use three or four different styles, probably depending on who wrote the patch, so I'm not sure that's evidence of it making sense for perlish languages.

Also having a space fits with

    proc foo {arg1 arg2} {

and

    (define foo (arg1 arg2) (

which are Tcl and scheme respectively, so opinions do appear to vary between languages in general.

**Comment by kraih** [comment]
One more data point, the [Mojolicious Web Clients](https://leanpub.com/mojo_web_clients/) book uses extra much whitespace.
```perl
sub get_mtime ( $url ) {
```

**Comment by christopherraa** [comment]
For me most definitly a space after the method name. Helps a lot with readability. Falls in the same category as camelCase / PascalCase VS snake_case / kebab-case. The space (or other word-separator) let me quicker separate the atoms of a statement and thus spend less time visually parsing the contents.

**Comment by kraih** [comment]
If i'm not mistaken the current version
```perl
sub startup ($self) {
```
is actually the most popular choice?

**Comment by kraih** [comment]
Well then.
