### ISSUE TITLE
Simplify logging behaviour

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1608]
When a `log` directory exists in the project root, `Mojolicious` defaults to loggin to `log/$mode.log`. That behaviour is a bit outdated now that we have systemd and containers everywhere. So i propose we simply default to logging to `STDERR` all the time.

**Comment by preaction** [comment]
👍 I continually wind up with logs going to files unexpectedly because something created a `log` folder, and then I spend 15 minutes trying to figure out where my logs are while debugging a problem...

**Comment by kraih** [comment]
We've recently had multiple instances of that happening at work too. I think the feature causes more confusion now than it is useful.

**Comment by Grinnz** [comment]
I tend to agree, but two things I would mention are that STDERR logging isn't usable with self-daemonization, and I think if this functionality were changed it should occur with a major version as anyone currently relying on it would suddenly stop having persistent logging.

**Comment by kraih** [comment]
That kind of setup is mostly legacy at this point though, and the service would still run just fine. It wouldn't really be a breaking change.
