### ISSUE TITLE
Inconsistency with commands that use dash.

### ISSUE THREAD

**Issue by kiwiroy** [mojolicious/mojo#1610]
The default [hint](https://github.com/mojolicious/mojo/blob/0a8e6f2a989903a4143a7c5e302c18798499703c/lib/Mojolicious/Commands.pm#L10) `APPLICATION help COMMAND` does not find the underscore named module, since the switch to using a dash rather than an underscore in 863f97b. I feel the following line should be after the `help` detection, rather than before.

https://github.com/mojolicious/mojo/blob/0a8e6f2a989903a4143a7c5e302c18798499703c/lib/Mojolicious/Commands.pm#L38

## Expected

Help is displayed in the terminal for the command.

## Actual

```
./script/myapp help kebab-time
Unknown command "kebab-time", maybe you need to install it?
```
Also, why is the issue template not applied here?

**Comment by kraih** [comment]
This is actually much easier demonstrated with
```
$ mojo generate help lite-app
Unknown command "lite-app", maybe you need to install it?
```
