### ISSUE TITLE
Exceeding the max_request_size has no consequences 

### ISSUE THREAD

**Issue by pileswasp** [mojolicious/mojo#1620]
* Mojolicious version: 8.63 and 8.66
* Perl version: v5.30.0
* Operating system: Ubuntu Server 20.04 LTS (Focal Fossa)

### Steps to reproduce the behavior
```perl
#!/usr/bin/env perl
use Mojolicious::Lite -signatures;
app->max_request_size(100);
post '/' => sub ($c) {
    $c->log->warn( 'Still processing....' );
  $c->render(text => 'Still processing');
};
app->start;
```
$ `./request_limit get -v -mode development --method post --form long=111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 /`
[2020-12-01 21:00:34.68342] [39407] [debug] **Maximum message size exceeded**
[2020-12-01 21:00:34.68556] [39407] [debug] [30DScmhj] POST "/"
[2020-12-01 21:00:34.68640] [39407] [debug] [30DScmhj] Routing to a callback
[2020-12-01 21:00:34.68678] [39407] [warn] [30DScmhj] **Still processing....**
[2020-12-01 21:00:34.68761] [39407] [debug] [30DScmhj] 200 OK (0.002009s, 497.760/s)
POST / HTTP/1.1
Accept-Encoding: gzip
Host: 127.0.0.1:36349
User-Agent: Mojolicious (Perl)
Content-Type: application/x-www-form-urlencoded
Content-Length: 107

HTTP/1.1 200 OK
Server: Mojolicious (Perl)
Content-Length: 16
Content-Type: text/html;charset=UTF-8
Connection: close
Date: Tue, 01 Dec 2020 21:00:34 GMT

Still processing

### Expected behavior
Explosions and fire.
The [main docs](https://docs.mojolicious.org/Mojolicious#max_request_size) don't actually say what's supposed to happen.
The FAQ suggests it should ["automatically stop accepting new data, and in most cases force the connection to be closed"](https://docs.mojolicious.org/Mojolicious/Guides/FAQ#What-does-the-error-Maximum-message-size-exceeded-mean).
Something along the lines of the FAQ and a non-200 HTTP response is what I expected would happen.

### Actual behavior
All I get is a debug-level message in the log (so not even that in production mode) and the code runs as though nothing is amiss.

A quick poke in [Mojo::Message](https://github.com/mojolicious/mojo/blob/master/lib/Mojo/Message.pm#L161) suggests the other max_* limits are similarly forgiving.

I'll have a more thorough poke around and see if I can come up with a patch to make it spit 413, 414, 431, etc with appropriate provocation.  Thoughts welcome.

**Comment by jhthorsen** [comment]
I don't think "Explosions and fire." is a good way to deal with this. I think it should rather be up to the action to deal with the invalid request. You can check for errors by looking at `$c->req->error`, the same way as you would check Mojo::UserAgent request errors:

```
$ perl -Mojo -e'post "/" => sub{$_[0]->render(json => $_[0]->req->error)}; app->max_request_size(1)->start' get -M POST -c 42 /
{"message":"Maximum message size exceeded"}
```

**Comment by Grinnz** [comment]
Actually you are supposed to check https://metacpan.org/pod/Mojo::Message#is_limit_exceeded to find out if this limit has occurred, similar to the example shown in [the tutorial](https://metacpan.org/pod/Mojolicious::Guides::Tutorial#File-uploads). There are probably documentation improvements needed here.

**Comment by pileswasp** [comment]
I considered the possibility that I was supposed to manually check something and started off coming here to ask what the expected behaviour/usage was, but finding the FAQ lead me to double down on my original expectation.

Also, in a real example, isn't your action going to be tied up reading in and parsing the large request for a while (unless it's expressly multipart/form-data, which looks like it ought to cut off part way)? Easy DoS? I have to eat the whole turd before I burp! :)

Happy to submit a doc patch if the consensus is that's all that's necessary.

**Comment by pileswasp** [comment]
I'm inclined to think perhaps the log level should be higher so that something shows up in a production log if you hit this unexpectedly.

**Comment by pileswasp** [comment]
So it seems that what y'all are witnessing is the overturning of my 20-odd year assumption that all the various MAX settings (`Apache::Request->new(POST_MAX=> ...)`, `$CGI::POST_MAX`, `$app->max_request_size`, etc) pretty much worked the same way
as setting `LimitRequestBody` in your Apache config, i.e. a hard 413 and no service. This is of course perl, so in hindsight my error is glaring.

A brief survey of "the documentation" (various perl modules, blog posts, SO questions and a couple of mod_perl books) and a few tests reveals silence, vagueness, conflicting answers and just plain errors about how they are each handled. Maybe I'll write it all up sometime.

Thankfully I don't recall that I've ever tried to rely on any of them for anything other than a vague nod at DoS protection (for which my assumption was "right enough") and this time "Test First" saves the day.

Every day's a schoolday.

So now I think the documentation needs a tweak, but this has changed my perspective on it slightly, so I'll re-visit my pull request.

Meanwhile, back to what I was supposed to be doing....

**Comment by pileswasp** [comment]
Meanwhile, additionally: https://github.com/mojolicious/mojo/pull/1623#discussion_r536895351

Maybe when you change it someone might consider explicitly describing the behaviour/usage?

Thanks for all your efforts; I'm (mostly) loving it.
