### ISSUE TITLE
Document how to add optional HTTP code code to exception

### ISSUE THREAD

**Issue by robrwo** [mojolicious/mojo#1622]
* Mojolicious version: 8.66
* Perl version: N/A
* Operating system: N/A

### Steps to reproduce the behavior

It's desirable to throw an exception in code for bad input and return a custom error code, e.g. HTTP 400 for bad parameters.

This also helps to identify the error when looking at HTTP logs, without having to look at an application log (which can be noisier).

### Expected behavior

It would be helpful to use something like
```perl
return $c->reply->exception('Division by zero!', 400)
   if $divisor == 0;
```

### Actual behavior

The only option is to return HTTP 404 (Not Found) or HTTP 500 (Server Error).

**Comment by robrwo** [comment]
See https://groups.google.com/g/mojolicious/c/4TFT7WP7bGI?pli=1

**Comment by jhthorsen** [comment]
I'm not sure if I think this is a good API. I would rather suggest that you add your own helper, like: `$app->helper('reply.bad_request' => sub { shift->render(..., status => 400) })`

**Comment by kraih** [comment]
I think `$c->reply->exception('Division by zero!')->rendered(400)` works too.

**Comment by jberger** [comment]
> I think `$c->reply->exception('Division by zero!')->rendered(400)` works too.

That looks very idiomatic mojo style. Is there a place we could put that into the guides?

**Comment by robrwo** [comment]
It should probably be added to the Rendering guide https://docs.mojolicious.org/Mojolicious/Guides/Rendering#Rendering-exception-and-not_found-pages
