### ISSUE TITLE
Unable to correctly load HeaderCondition

### ISSUE THREAD

**Issue by camstuart** [mojolicious/mojo#1636]
* Mojolicious version: 8.63
* Perl version: 5.32
* Operating system: Linux Ubuntu 20.04.1

### Steps to reproduce the behavior
I don't seem to be able to correctly use the builtin Plugin: `HeaderCondion` after following the docs here: https://docs.mojolicious.org/Mojolicious/Plugin/HeaderCondition

```perl
  $self->plugin('HeaderCondition');
  my $r = $self->routes;

  my $api = $r->under('/api')->requires(headers => { 'X-API-Key' => 'MY_KEY' });
  $api->post('/transaction/create')->name('api-transaction-create')->to('Transaction#api_create');
```

### Expected behavior
I expected the plugin to be loaded and the route to always require the `X-API-Key` or return a 404 or something in the 400 range

### Actual behavior
Can't locate object method "requires" via package "Mojolicious::Routes::Route" at .....pm line 17

**Comment by kraih** [comment]
Upgrade your version of Mojolicious.

**Comment by camstuart** [comment]
That did the trick, thanks @kraih!
Excellent framework too by the way, well done.
