### ISSUE TITLE
Change Mojo::Log message joining

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1660]
Multiple messages (`$log->debug('foo', 'bar')`) are currently joined with newline characters. But now that we have contextual logging that's not a good default anymore. Since the context needs to be prepended to the first message (`$log->debug('[12345] foo')`). Instead we should just join multiple messages with a whitespace character. That would allow for the context to be a separate message (`$log->debug('[12345]', 'foo')`).

So i propose that we do this as a breaking change with the 9.0 release.

**Comment by kraih** [comment]
Of course that leaves the case where messages are actually intended to be joined with a newline. For that we could have special treatment of messages beginning or ending in a newline character. Will probably depend on the performance impact though.

**Comment by jhthorsen** [comment]
I've found the newline joining rather unexpected so I welcome this change.

**Comment by kraih** [comment]
Done, as part of the 9.0 branch.
