### ISSUE TITLE
Hang/no HTTP response if wide character in response

### ISSUE THREAD

**Issue by horgh** [mojolicious/mojo#1686]
* Mojolicious version: 8.72
* Perl version: 5.32.1
* Operating system: Ubuntu Bionic

### Steps to reproduce the behavior
I have an endpoint that returns JSON. It incorrectly outputs a Unicode string with wide characters. When that happens, I see:

```
Mojo::Reactor::Poll: I/O watcher failed: Wide character in subroutine entry at /opt/perl5.32.1/lib/site_perl/5.32.1/Mojo/IOLoop/Stream.pm line 93.
```

And there is no HTTP response. After 30 seconds, curl exits like so:

```
* Connected to 0 (127.0.0.1) port 3000 (#0)
> GET /foo HTTP/1.1
> Host: 0:3000
> User-Agent: curl/7.58.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 0 left intact
curl: (52) Empty reply from server
```

Code:

```perl
sub startup ($self) {
  [snip]                                                                                                                                       
  my $r = $self->routes;                                                                                                                              
  $r->get('/foo')->to('example#foo');                                                                                                                                   
}
```

```perl
sub foo ($self) {
    $self->render(
        data => '{"foo":"☃️":}',
        format => 'json',
    );
} 
```

### Expected behavior
I'd expect an HTTP 500 or something similar.

### Actual behavior
There is no HTTP response at all. The client appears hung.

As the error shows, I believe it's because of this call - https://github.com/mojolicious/mojo/blob/v8.72/lib/Mojo/IOLoop/Stream.pm#L93

Perhaps this is expected given this is an error on my part, but I thought I'd open an issue to see what you think.

Thank you!

**Comment by kraih** [comment]
That is expected behaviour.

**Comment by Grinnz** [comment]
The `data` stash value accepts bytes; you've passed it characters, and also manually written JSON which is a bad idea.

The proper way to do this is with the JSON generator which will encode both to JSON and bytes as appropriate:

    $self->render(json => {foo => '☃️'});

**Comment by horgh** [comment]
Okay, thank you! Yeah, in my real app there isn't hand written JSON actually, though we did end up with it as characters.

**Comment by Grinnz** [comment]
If you have already encoded JSON to send as a response, you would either encode it to UTF-8 yourself (such as with Mojo::Util::encode) or use the `text` stash key.
