### ISSUE TITLE
Perl Tidy Github action broken.

### ISSUE THREAD

**Issue by EvanCarroll** [mojolicious/mojo#1702]
I believe the github action for perltidy is broken,

I'm looking at this PR's action results https://github.com/EvanCarroll/mojo/runs/1896016424?check_suite_focus=true

Yet when I run on the files I get 0.

```
$ perltidy --pro=.perltidyrc -b -bext='/' t/mojo/request_cgi.t lib/Mojo/Message/Request.pm && git diff --exit-code; echo $?
0
```

**Comment by kraih** [comment]
It's not.

**Comment by jberger** [comment]
Be sure to use the more recent Perl::Tidy. We've made use of recent additions to it in several of its latest releases

**Comment by EvanCarroll** [comment]
@jberger that was the problem, would you accept a patch to better document the perltidy stuff and clean up the action?

**Comment by jberger** [comment]
I suppose we could add "most recent" the line in [Rules](https://docs.mojolicious.org/Mojolicious/Guides/Contributing#Rules) about perltidy. What do you think needs cleaning in the action?

**Comment by EvanCarroll** [comment]
I would definitely provide the actual line that can be run in the docs for new users,

    git diff --name-status upstream/master..HEAD | xargs perltidy --pro=.perltidyrc -b -bext='/'

And in the action, I would provide some information about the likely cause of failure,

```
&& git diff --exit-code || echo -e "\n\nTIDY FAILURE: This PR is not tidy. Please ensure your version of Perl::Tidy is up to date with this report and that you've tidied your commit. You can find your version of perltidy with [perltidy --version]. For more information about perltidy see our wiki doc here <URL>."
 ```

**Comment by kraih** [comment]
The perltidy version is already shown, i do not believe any changes are necessary.
