### ISSUE TITLE
Align version scheme with perl expectations

### ISSUE THREAD

**Issue by D1CED** [mojolicious/mojo#1704]
* Mojolicious version: 8.66
* Perl version: v5.32.0
* Operating system: Linux

### Steps to reproduce the behavior

    use Mojolicious; say version->parse(Mojolicious->VERSION)->normal

### Expected behavior

    v8.66.0

### Actual behavior

    v8.660.0

Version 9 of Mojolicious is the chance to correct this. 

    our $VERSION  = 'v9.01'; # with dotted-decimal versions scheme
    our $VERSION  = '9.001'; # or use decimal versions

https://perldoc.pl/version::Internals

**Comment by kraih** [comment]
No, we are happy with the versioning scheme we have.

**Comment by Grinnz** [comment]
Decimal versions are expected in Perl. See http://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html for more info.
