### ISSUE TITLE
Rejected promise returned in finally() callback doesn’t cause promise to reject

### ISSUE THREAD

**Issue by FGasper** [mojolicious/mojo#1708]
* Mojolicious version: 9.01
* Perl version: 5.26
* Operating system: macOS 10.14

### Steps to reproduce the behavior
```
> perl -MMojo::Promise -e'Mojo::Promise->resolve(123)->finally( sub { Mojo::Promise->reject(666) } )->then( sub { print "yes @_" }, sub { print "no @_" } )->wait()'
Unhandled rejected promise: 666 at -e line 1.
yes 123
```

### Expected behavior
It should say `no 666`, as per JS’s behavior:
```
> Promise.resolve(123).finally( () => Promise.reject(666) ).then( v => console.info("yes", v), v => console.error("no", v) )
Promise { <pending> }
> no 666
```

As of now there’s a blue callout that explains this behavior on MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
![image](https://user-images.githubusercontent.com/844867/108296366-65e4dd80-7167-11eb-8eeb-0d234b1eee7b.png)

**Comment by FGasper** [comment]
@kraih The following reimplementation of `finally()` fixes the problem:
```
sub finally {
    my $class = ref $_[0];
    my $cb = $_[1];

    my $big_cb = sub {
        my @vals = @_;

        $class->resolve($cb->())->then(sub { @vals } );
    };

    return $_[0]->then( $big_cb, $big_cb );
}
```
… however, it breaks this test in t/mojo/promise.t:
```
# Resolved nested with finally
$promise  = Mojo::Promise->new;
$promise2 = Mojo::Promise->new;
@results  = ();
$promise->finally(sub {$promise2})->finally(sub { @results = ('finally') });
$promise->resolve('pass');
Mojo::IOLoop->one_tick;
is_deeply \@results, ['finally'], 'promise already resolved';
```
This test, though, is invalid if the aim is to mimic ES6 promises, because `finally(sub {$promise2})` can’t settle until $promise2 does.

What’s your thought here? Leave the current behaviour, or reconcile it with ES6?

(There’s another test that fails for a different reason; I’m still looking there.)

**Comment by kraih** [comment]
We follow ES6, any differences in behaviour that are not JavaScript specific are considered a bug in `Mojo::Promise`.
