### ISSUE TITLE
:action cannot be used as placeholder anymore :(

### ISSUE THREAD

**Issue by ginesr** [mojolicious/mojo#1710]
* Mojolicious version: Mojolicious (9.01, Waffle)
* Perl version: Perl (v5.26.1, linux)
* Operating system: Ubuntu 18

### Steps to reproduce the behavior
$r->get('/:action')->to(controller=>'controller-whatever'); worked if 'action' is a method in the class controller before

### Expected behavior
To work like it was in mojo 8.x

### Actual behavior
It dies with an error that action cannot be used as placeholder

**Comment by kraih** [comment]
That is very much intentional, and a new security feature.

**Comment by ginesr** [comment]
:( so I need to dispatch all by myself now? What is the recommended option here? I have to change a lot of routes now ...

**Comment by kraih** [comment]
Loop over a list of actions to generate routes.

**Comment by shadowcat-mst** [comment]
Writing a 'foreach' route is better than being a giant security risk.

Using :action was always on the same level as "not using placeholders in your SQL" in terms of being unwise.

It's been deprecated and recommended against for years.

I'm sorry this is going to be inconvenient but it really will make your code better as a result.

**Comment by kraih** [comment]
The feature discussion btw., nobody brought up objections. https://github.com/mojolicious/mojo/discussions/1663#discussioncomment-342395

**Comment by ginesr** [comment]
Ok thanks for the response
