### ISSUE TITLE
How to pass tls options (force TLS 1.2) to Mojo::UserAgent?

### ISSUE THREAD

**Issue by knutov** [mojolicious/mojo#1733]
What is the correct way to pass tls options to Mojo::UserAgent now?

I want to force use only TLS 1.2.

`IO::Socket::SSL::set_client_defaults(SSL_version => 'TLSv12:!SSLv2:!SSLv3:!TLSv1:!TLSv11');` works for me, but this setting works only as global option.

Perl        (v5.18.2, linux)
Mojolicious (9.03, Waffle)

**Comment by Grinnz** [comment]
Please use the [support channels](https://docs.mojolicious.org/#SUPPORT) for discussion and questions.

Mojo::UserAgent only has passthrough for the `ca`, `cert`, `key`, and `insecure` TLS options currently - setting global defaults is an alternative.

**Comment by jberger** [comment]
Can't you use https://docs.mojolicious.org/Mojo/UserAgent#socket_options ?

**Comment by Grinnz** [comment]
That accepts IO::Socket::IP options not TLS options.

**Comment by kraih** [comment]
As a feature request this would have been reasonable.
