### ISSUE TITLE
Mojolicious 9.07 breaks downstream tests

### ISSUE THREAD

**Issue by jberger** [mojolicious/mojo#1735]
I'm getting [failing tests on GuacLite](http://www.cpantesters.org/cpan/report/48ae3b46-82d6-11eb-84bc-edd243e66a77) and @yuki-kimoto is [seeing something similar](https://github.com/mojolicious/mojo/commit/f1af6acd74291a95599a30daffbe545d9681c33b#commitcomment-48165500). Not sure exactly what the problem is yet but I'm opening a ticket to track.

**Comment by kraih** [comment]
Looks like a bug.

**Comment by kraih** [comment]
We'll need a test though.

**Comment by jberger** [comment]
This appears to be sufficient:

```bash
perl -MTest::More -MTest::Mojo -MMojolicious -E 'my $app = Mojolicious->new; my $t = Test::Mojo->new($app); ok $t; done_testing'
```
