### ISSUE TITLE
Removal of Content-Length: 0 header breaks empty POST requests to Cloudflare endpoints

### ISSUE THREAD

**Issue by incognico** [mojolicious/mojo#1738]
Mojo::UserAgent 9.07 introduced the following: 4693a9cfed545f9e144d3341fd35d63279589f5b Improve Mojo::UserAgent performance slightly (closes #1479)

While this might be correct behaviour per RFC (???), it breaks communication with Cloudflare endpoints (at least in `POST` requests). See https://github.com/vsTerminus/Mojo-Discord/issues/37

The current implementation removes the `Content-Length` header when it is `0` in a way which makes it impossible to keep it, even if it was explicitly set.

**Comment by kraih** [comment]
That is unfortunate, is it only only for non-`GET` requests?

**Comment by incognico** [comment]
> That is unfortunate, is it only only for non-`GET` requests?

From what I understand, yes.

https://tools.ietf.org/html/rfc7230#section-3.3.2 states:
> A user agent **SHOULD send a Content-Length** in a request message when
   no Transfer-Encoding is sent and **the request method defines a meaning
   for an enclosed payload body.**  For example, **a Content-Length header
   field is normally sent in a POST request even when the value is 0**
   (indicating an empty payload body).  A user agent SHOULD NOT send a
   Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a
   body.

**Comment by kraih** [comment]
Thanks, fix will be in the next release.
