### ISSUE TITLE
Please add support for JSON::XS, or just replace CPanel::JSON:XS with JSON::XS

### ISSUE THREAD

**Issue by KalessinD** [mojolicious/mojo#1742]
Hi!

I found with Benchmark module that CPanel::JSON:XS performance is lower than JSON::XS in all cases (i didn't find any opposite case in our traffic). I tried different amount of JSON strings with different size. And in most cases the difference of performance lays between 15% and 25%.
I think it can be a good reason to get rid of CPanel::JSON:XS library in favor of JSON::XS.

If it's required i can provide the benchmark code and obfuscated examples of JSON strings.

Thanks in advance!

With best regards, Chernenko Dmitiry.

**Comment by Grinnz** [comment]
It is known that JSON::XS is faster as a result of being buggy. https://metacpan.org/pod/Cpanel::JSON::XS#cPanel-fork

**Comment by karenetheridge** [comment]
The author of Cpanel::JSON::XS is very receptive to feedback; if you have some samples that demonstrate a difference in efficiency, I'm sure he'd love to take a look at them and see if there's anything he can to to improve performance.

https://github.com/rurban/Cpanel-JSON-XS/issues

**Comment by jberger** [comment]
Also, with the exception of session data, you can use any JSON renderer you want by simply encoding your data manually and rendering it as data (if it has already been utf8 encoded) or text (if it hasn't).

**Comment by KalessinD** [comment]
> Also, with the exception of session data, you can use any JSON renderer you want by simply encoding your data manually and rendering it as data (if it has already been utf8 encoded) or text (if it hasn't).

It's a bit difficult. We have a huge project and there are multiple places where we need to do this work by ourselves.

Currently Mojo:;JSON is being used in multiple places such as Mojo::Renderer, OpenApi plugin, JSON::Validator, etc...
I can replace Mojo::Renderer with my own class, but it's not easy operation due to some calls of dashed-prefixed methods.
It's not obvious how to treat them: as protected methods or as private. And there is no guarantee that the logic will be always the same there. And it's a bit incovinient that sometimes Mojo shows OOP aproach, but sometimes it doesn't use it (for example in case with previously mentioned dashed-prefixed methods in Mojo::JSON). In this case i need to redeclare a lot of "internal" functions too.

And it's required from me to do the same trick with other modules.. It's a very inconvinient that library doesn't provide a proper and chip way to replace any components without doing a huge work and without guarantee that newly applied chnages will have the same behaviour in future.

**Comment by KalessinD** [comment]
> It is known that JSON::XS is faster as a result of being buggy. https://metacpan.org/pod/Cpanel::JSON::XS#cPanel-fork

Cpanel::JSON::XS appeared in 2007, may be in that period there were a lot of critical bugs in JSON::XS.. Who knows.
Butt currently is 2021. And there were a lot fixes in JSON::XS since 2007.

If we compare thre issues list of these two libraries, then it will be obviously that JSON::Xs has less isuues than Cpanel::JSON::XS.
And most of them a minor: issues with old versions of perl, old versions of JSON::XS, some misstypes in POD.

https://rt.cpan.org/Public/Dist/Display.html?Name=JSON-XS
https://github.com/rurban/Cpanel-JSON-XS/issues

**Comment by karenetheridge** [comment]
You can simply swap out the JSON backend in Mojo::JSON by overriding its public methods (encode_json, decode_json, to_json, from_json). You don't need to touch any of the internal methods.

> If we compare the issue lists of these two libraries, then it will be obviously that JSON::Xs has less isuues than Cpanel::JSON::XS.

That's a false comparison because the author of the former module is openly hostile to bug reports and will routinely close and delete reports made in public queues.

**Comment by Grinnz** [comment]
Yes; see for example the implementation of [Mojo::JSON::MaybeXS](https://metacpan.org/source/Mojo::JSON::MaybeXS) (which is now obsolete since Cpanel::JSON::XS is used by Mojo::JSON by default).

**Comment by kraih** [comment]
I'm afraid the votes are pretty clear, this proposal has been rejected.
