### ISSUE TITLE
Switch away from HMAC SHA1 for signed cookies

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1790]
It appears brute forcing HMAC SHA1 has become way too easy. So it is time for us to switch to something more expensive. HMAC SHA256 would seem reasonable. Thoughts?

**Comment by kraih** [comment]
The SHA1 functions and methods should be deprecated too.

**Comment by Grinnz** [comment]
+1 to both. Deprecating the sha1 functions will be a little disruptive, but those functions are literally just Digest::SHA wrappers, people can switch to those if it's not security-sensitive.

**Comment by Grinnz** [comment]
I'll note that Mojo::Util still has md5 wrappers too though.

**Comment by kraih** [comment]
Ok, i'll leave the deprecation out for now. But we still have an issue with session logouts sometimes being too short. Which makes brute force attacks too easy.

**Comment by kraih** [comment]
The change to SHA256 is merged. https://github.com/mojolicious/mojo/compare/f577670a1e4c...3f10b6af0271
