### ISSUE TITLE
eats Getopt::Long command-line options in surprising ways

### ISSUE THREAD

**Issue by stuart-little** [mojolicious/mojo#1794]
* Mojolicious version: `9.19`
* Perl version: `5.32.1`
* Operating system: `Android 10` (`aarch64`), running the [Termux](https://termux.com/) terminal emulator, and `Linux` kernel `4.9`

### Steps to reproduce the behavior
Consider this script:
```
#!/usr/bin/env perl
use warnings;
use v5.12;

use Mojo::UserAgent;
use Getopt::Long;

my($help);

GetOptions (
    "h|help" => \$help,
    );

if ($help) {
    my $CMD=qq{less $0};
    system $CMD;
    exit;
}
```

### Expected behavior
When run as 
```
<path-to-script> -h
```
it should display its own source in `less` (my pager). It does so *without* the `use Mojo::UserAgent` line.

### Actual behavior
Nothing is displayed.

**Comment by kraih** [comment]
Yes, we should not modify `@ARGV`.

**Comment by stuart-little** [comment]
Actually, no, the plot thickens!

I apologize: I was `ssh`-d into my `Linux` laptop through my `Android 10` phone. The latter runs the [Termux](https://termux.com/) terminal emulator with perl `v5.32.1`.

The problem reported above does *not* occur on the `x86_64` laptop, but rather on the `Android` phone. The same script behaves as expected on `x86_64`.

But this makes it all that more mysterious.. To summarize:
- the script I provided works fine on `x86_64` systems, respecting the `-h` option;
- it exhibits the buggy option-eating behavior only on `Android`
- even though `Mojolicious` in general works fine there; for instance, 
```
#!/usr/bin/env perl
use warnings;
use v5.12;

use Data::Dump qw(dump);
use Mojo::UserAgent;

my $ua  = Mojo::UserAgent->new;

# https://stackoverflow.com/questions/5725430/http-test-server-accepting-get-post-requests
my $tx = $ua->post('https://httpbin.org/post' =>
		   json => {
		       top => 'secret',
		       ha => 'boo',
		       # number => 1,
		   });
dump $tx->result->json;
```
displays, on my phone, exactly what it does on my other machines.
---
I'll edit the initial report to reflect accurate OS info, but why would there be this difference in behavior?

**Comment by Grinnz** [comment]
Hard to say. Can you add error handling when GetOptions returns false, and verify whether passing an option it doesn't recognize causes it to die? And also add an "else" condition at the end to verify it is being reached.

**Comment by stuart-little** [comment]
Sure thing. Here are a few variations. 

First
```
#!/usr/bin/env perl
use warnings;
use v5.12;

use Mojo::UserAgent;
use Getopt::Long;

my($help);

GetOptions (
    "h|help" => \$help,
    );

if ($help) {
    system qq{ls};
} else {
    say "made it!";
}
```
- does choke on unknown options:
```
$ <script> --boo
Unknown option: boo
made it!
```
- and makes it to the end with no options:
```
$ <script>
made it!
```
On the other hand `<script> -h` still displays nothing if I `use Mojo::UserAgent`, while performing the requested `ls` without `Mojo`.

However:
```
#!/usr/bin/env perl
use warnings;
use v5.12;

use Mojo::UserAgent;
use Getopt::Long;

my($help);

GetOptions (
    "h|help" => \$help,
    );

if ($help) {
    say "help";
} else {
    say "made it!";
}
```
*does* say `help` when run as `<script> -h`, even *with* `Mojo`.

So it seems to be some sort of bizarre 3-way mishap between
- `Mojo`
- `Getopt::Long`
- and a call to `system`

**Comment by stuart-little** [comment]
Hang on a minute!

```
#!/usr/bin/env perl
use warnings;
use v5.12;

use Mojo::UserAgent;

system "ls";
```
shows nothing, while performing as expected w/o `Mojo`.

So this has nothing to do with `Getopt`: there must be some shell magic happening on this platform that `Mojo` doesn't like.

**Comment by Grinnz** [comment]
Afraid it's going to be difficult for us to help debug as I don't know of anyone else running mojo (or even perl) on android. There are only two potentially troublesome effects of loading Mojo::UserAgent - loading reactor classes (incl EV if available) and loading optional modules like Net::DNS::Native and IO::Socket::Socks. You could try disabling loading of these optional modules with env vars as described in https://metacpan.org/pod/Mojo::UserAgent#DESCRIPTION and https://metacpan.org/pod/Mojo::IOLoop#DESCRIPTION.

**Comment by stuart-little** [comment]
> Afraid it's going to be difficult for us to help debug as I don't know of anyone else running mojo (or even perl)

Yeah, it's a bit niche :).. We're getting somewhere with your suggestion though:

> loading reactor classes (incl EV if available)

On this gadget:
```
$ perl -MEV

EV: cannot initialise libev backend. bad $ENV{LIBEV_FLAGS}? at /data/data/com.termux/files/usr/lib/perl5/site_perl/5.32.1/aarch64-android/EV.pm line 1245.
Compilation failed in require.
BEGIN failed--compilation aborted.
```
I actually knew about this, but never got to the bottom of it. I have asked for help on the `libev` [mailing list](http://lists.schmorp.de/mailman/listinfo/libev), but a mailing list is by nature harder to reach than a `github` org. So nothing doing there yet..

If I uninstall `EV` though (with `cpanm -U EV`, say), then `Mojo` functionality is restored! 

So that's where it was at: the buck (for now) stops, I believe, at `EV`. How / why this is happening is still a mystery to me (I have `libev` and can compile and run `c` programs using `ev.h`).

As far as this issue goes I'd say it's more than fair to close it (it's already badly mis-titled anyway), but any advice on how to pursue the root cause?

**Comment by Grinnz** [comment]
You can set `MOJO_REACTOR=Mojo::Reactor::Poll` in env to avoid loading EV.
