### ISSUE TITLE
mojo version uses wrong perl version

### ISSUE THREAD

**Issue by rico666** [mojolicious/mojo#1796]
Using Perl 5.32.1 under perlbrew. I believe to have read perlbrew being preferred/encouraged. The current shell sees that

```
$ perlbrew list
* perl-5.32.1 
$ perl --version
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux
```

However, "mojo version" sees the system perl:

```
$ mojo version
CORE
  Perl        (v5.34.0, linux)
  Mojolicious (9.19, Waffle)

OPTIONAL
  Cpanel::JSON::XS 4.09+   (n/a)
  EV 4.32+                 (n/a)
  IO::Socket::Socks 0.64+  (0.74)
  IO::Socket::SSL 2.009+   (2.071)
  Net::DNS::Native 0.15+   (n/a)
  Role::Tiny 2.000001+     (2.002004)
  Future::AsyncAwait 0.36+ (n/a)
```

And therefore doesn't see the installed optional modules:

```
$ cpan install  Cpanel::JSON::XS
Cpanel::JSON::XS is up to date (4.26).
$ cpan install EV
EV is up to date (4.33).
$ cpan install Net::DNS::Native
Net::DNS::Native is up to date (0.22).
$ cpan install Future::AsyncAwait
Future::AsyncAwait is up to date (0.51).
```
It's a pretty new installation and experiencing some weird problems like
`Can't locate object method "app" via package "MojoReactApp::Model::Data" ...`
so I wanted to make sure this is not the root cause of it all.

**Comment by rico666** [comment]
```
$ which perl
/opt/perlbrew/perls/perl-5.32.1/bin/perl
```
```
$ which mojo
/home/user/perl5/bin/mojo
```
/home/user/perl5/bin/mojo has ofc the `#!/usr/bin/perl` shebang and that points to 5.34

**Comment by rico666** [comment]
changing that shebang to `#!/usr/bin/env perl` fixes things magically:

```
$ mojo version
CORE
  Perl        (v5.32.1, linux)
  Mojolicious (9.19, Waffle)

OPTIONAL
  Cpanel::JSON::XS 4.09+   (4.26)
  EV 4.32+                 (4.33)
  IO::Socket::Socks 0.64+  (0.74)
  IO::Socket::SSL 2.009+   (2.071)
  Net::DNS::Native 0.15+   (0.22)
  Role::Tiny 2.000001+     (2.002004)
  Future::AsyncAwait 0.36+ (0.51)
```

resolved for me, but you might want to fix that in the code too.

**Comment by kraih** [comment]
The `mojo` script uses a `#!perl` shebang line, which gets rewritten during installation. That is the standard i'm afraid, and we won't change it again.

**Comment by Grinnz** [comment]
> ```
> $ which perl
> /opt/perlbrew/perls/perl-5.32.1/bin/perl
> ```
> 
> ```
> $ which mojo
> /home/user/perl5/bin/mojo
> ```
> 
> /home/user/perl5/bin/mojo has ofc the `#!/usr/bin/perl` shebang and that points to 5.34

This is the problem. You have a local::lib active, which is not compatible with perlbrew.

**Comment by rico666** [comment]
I think if that `#!perl` would get rewritten with `#!/usr/bin/env perl` things would remain more DWIM flexible.

> The `mojo` script uses a `#!perl` shebang line, which gets rewritten during installation. That is the standard i'm afraid, and we won't change it again.

Ofc I do not know the long and tedious history of changes, but I do not see how a rewrite to the "env form" would do anything else but improve the situation.

**Comment by kraih** [comment]
> Ofc I do not know the long and tedious history of changes, but I do not see how a rewrite to the "env form" would do anything else but improve the situation.

This is really not the right place to argue about Perl standards. That's toolchain business, please take it there. https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker
