### ISSUE TITLE
Backport security fixes from 9.19 to 8.x

### ISSUE THREAD

**Issue by AdamWill** [mojolicious/mojo#1807]
I believe it would be a good idea to backport the security fixes from 9.19 to a new 8.x branch and cut an 8.74 release. There was no real transition period from 8.x to 9.x, and downstream distributions have current stable releases including 8.x. With a major security issue disclosed in 9.19, they now have the choice of doing a major, non-backwards-compatible upgrade and trying to patch all dependencies, leaving known-insecure 8.73 in their repositories, or backporting the fixes themselves. A new upstream release seems a preferable alternative.

Both patches cherry-pick cleanly on top of 8.73, except for the `Changes` file, which is trivial to adjust.

**Comment by jberger** [comment]
Without commenting on backporting, the changes are able to be made trivially in-place. Simply set `$app->session->serialize` and `$app->session->deserialize` to the new values seen in c99dee43f62ac5d552208ebf494f11474709efda. This could easily be made into a plugin on CPAN which could be loaded at startup.

**Comment by AdamWill** [comment]
Sure, that's not of any practical use to distributors though.
I've already backported the fixes and sent out an update for Fedora 33 and 34, but Debian for e.g. has 8.12 in stable and 8.71 in unstable and testing, Ubuntu has various versions from 7.59 through 8.71 in universe repos for different releases, Gentoo has an 8.x release too...

Releasing an 8.74 - and, ideally, filing a CVE, there does not appear to be one? - would give those distributions an opportunity to update to a compatible, secure version.

**Comment by kraih** [comment]
As is customary for Perl modules, we only support one major version. And that's not gonna change, even if someone was offering to pay for it.

**Comment by kraih** [comment]
If Linux distributions decide to support older versions, then they have to cover the costs of doing so themselves.
