### ISSUE TITLE
Mojo::Template - documentation on adding subs to templates 

### ISSUE THREAD

**Issue by guest20** [mojolicious/mojo#1819]
* Mojolicious version: v9.20

In a mojolicious app I can expose named subs to my templates by defining helpers:
```perl
use Mojolicious::Lite -signatures;
helper nice => sub { "we did it" };
get '/' => sub ($c) { $c->render }, 'index';
app->start;
__DATA__ 
@@ index.html.ep  
%= nice() 
```
```
$ perl ./above get /
we did it   
```

I's like to use the template outside of app context, and if I visit the `Mojo::Template` docs I find this:
```perl
# Render with named variables
say $mt->vars(1)->render(<<'EOF', {title => 'Hello World!'});
<div>
  <h1><%= $title %></h1>
  %= 5 + 5
</div>
EOF
```

This gives me options for variables, but not for named subs. 

Some of the choices I see are:
- I can add code-refs into `\%vars` and call them with `<%= $var->() %>`
- I can `use` an `Exporter` in my template?
- `->prepend()` a big ball of code to be eval'ed?
- a trick with putting subs into `->namespace`?

I'm aware that I have access to perl in the template, but I think it would be nice if there were some guidance on a nice way to achieve this in a way that other mojo users wouldn't find offensive.

**Comment by Grinnz** [comment]
This might be better suited to a discussion. EPRenderer adds helpers to templates via the [namespace](https://metacpan.org/pod/Mojo::Template#namespace) attribute. The template will be compiled in the specified package namespace and thus have access to any subroutines defined in it.

**Comment by guest20** [comment]
To me it feels like a docbug, but I don't mind this issue being closed if there's nothing to fix

**Comment by kraih** [comment]
This is not a bug. Helpers are not part of `Mojo::Template`.
