### ISSUE TITLE
Does the expires key need to be updated or every request?

### ISSUE THREAD

**Issue by robrwo** [mojolicious/mojo#1834]
Mojolicious::Sessions updates the `expires` session key for every request. This means that every session cookie is different. This makes it impossible to use the `Cache-Control` response header with a `Vary: Cookie` header.

A workaround is to specify a consistent `expires` key with every request (based on when one first connects to the site).

But is the `expires` key really necessary? 

This question is inspired by https://github.com/mojolicious/mojo/discussions/1833

**Comment by Grinnz** [comment]
Yes; session expiration is refreshed on each access of the session

**Comment by kraih** [comment]
Why move the question from discussion to issue?

**Comment by robrwo** [comment]
It seems like a flaw in the code that unnecessarily limits how sessions are handled.

I don't see a reason for explicitly including the expiration time in the session data when the cookie already has an expiration time.

Does anything else rely on that expiration time?

**Comment by kraih** [comment]
Please have a discussion about this first before assuming there's a bug.
