### ISSUE TITLE
render() willing to render invalid HTTP

### ISSUE THREAD

**Issue by melak** [mojolicious/mojo#1850]
* Mojolicious version: 9.21
* Perl version: 5.34
* Operating system: FreeBSD 13

This is admittedly a long shot since at the end of the day it is a user error, but here it goes.

### Steps to reproduce the behavior
```
$ perl -Mojo -E 'get "/" => sub { shift->render(text => "asdf", status => 1); }; app->start' daemon -l http://localhost:12345
```
(note invalid *status => 1*), then
```
$ perl -Mojo -e 'say g("http://localhost:12345")->code'
Bad response start-line at /usr/local/lib/perl5/site_perl/ojo.pm line 35.
```
(which is obviously perfectly justified.)

### Expected behavior
I suspect it would be nice for `render()` to not even start rendering a response that ultimately ends up being not-quite-HTTP, but throw an exception instead (or peruse some other mechanism signalling error).

### Actual behavior
`render()` happily renders a response that ends up being invalid HTTP.

**Comment by kraih** [comment]
Not a bug, we allow many many ways to generate bad HTTP responses. And that's often a feature for testing.
