### ISSUE TITLE
Mojo get fails to get content when 'Connection: Upgrade, close' header is set

### ISSUE THREAD

**Issue by maros** [mojolicious/mojo#1855]
* Mojolicious version: 9.21
* Perl version: 5.32.1
* Operating system: Debian 10.8

### Steps to reproduce the behavior
When downloading a resource (either via 'mojo get' cli or via Mojo::UserAgent) the content is empty when the response has a) no Content-Length header and b) has a 'Connection: Upgrade, close' header. 

### Expected behavior
Download resource

### Actual behavior
Only the headers are fetched, and $tx->res->content->asset->size == 0 

### Possible cause
Mojo::Content has this piece of code that checks for Connection == 'close' and thus missing 'Upgrade, close'

```
  my $len     = $headers->content_length // '';
  if ($self->auto_relax && !length $len) {
    my $connection = lc($headers->connection // '');
    $self->relaxed(1) if $connection eq 'close' || !$connection;
  }
```

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection the connection header may contain a comma-separated list of directives.

**Comment by kraih** [comment]
How would `Upgrade` make sense in this context?

**Comment by jberger** [comment]
I disagree with your reading of the MDN article, specifically when there is a list of values for Connection it states that that indicates that it wants to keep the connection open and that those values are then headers to be removed by proxies. Further if you read into the [linked spec](https://httpwg.org/specs/rfc7230.html#header.connection) it explicitly says:

> In order to avoid confusing downstream recipients, a proxy or gateway MUST remove or replace any received connection options before forwarding the message.

I've never seen this usage of the Connection header and I must say I'm rather dubious of its utility generally, that said, the header that you specify would seem to be invalid if sent to a non-proxy (e.g. endpoint) server. As such I'm going to close this issue, if you feel that is in error, please link to any relevant documentation or major server implementations that admit such a header.
