### ISSUE TITLE
Documentation diagrams

### ISSUE THREAD

**Issue by ghenry** [mojolicious/mojo#1869]
Hi all,

How did the team do the diagrams for https://docs.mojolicious.org/Mojolicious/Guides/Cookbook#Reverse-proxy 

I'm looking to add some docs to my project which I'm using Mojo for too - https://github.com/SentryPeer/SentryPeer/tree/main/prototype

Thanks and really, really good docs.

Gavin.

**Comment by Grinnz** [comment]
This is just a [verbatim paragraph](https://perldoc.perl.org/perlpod#Verbatim-Paragraph) as you can see in the [source](https://docs.mojolicious.org/Mojolicious/Guides/Cookbook.txt).

Please use the [support channels](https://docs.mojolicious.org/#SUPPORT) for questions which are not a bug report or feature request.

**Comment by kraih** [comment]
And i made all diagrams manually by hand.

**Comment by ghenry** [comment]
> And i made all diagrams manually by hand.

Cool. Thanks for the info.

**Comment by ghenry** [comment]
> This is just a [verbatim paragraph](https://perldoc.perl.org/perlpod#Verbatim-Paragraph) as you can see in the [source](https://docs.mojolicious.org/Mojolicious/Guides/Cookbook.txt).
> 
> Please use the [support channels](https://docs.mojolicious.org/#SUPPORT) for questions which are not a bug report or feature request.

I did in irc. I think you are there too :-)
