### ISSUE TITLE
Mojo::Promise->all() with no arguments fails

### ISSUE THREAD

**Issue by akarelas** [mojolicious/mojo#1874]
* Mojolicious version: 9.22
* Perl version: v5.34
* Operating system: Ubuntu 20.04

### Steps to reproduce the behavior
When calling `Mojo::Promise->all()` with no arguments, instead of getting a promise that immediately resolves, I get an exception.

```bash
> perl -MMojo::Promise -E 'my $p = Mojo::Promise->all();'
Can't call method "clone" on an undefined value at /home/karjala/test/local/lib/perl5/Mojo/Promise.pm line 126.
```

### Expected behavior
When arguments are present, the `all` method succeeds when all promises succeed. Therefore I would expect `all()` (without arguments) to succeed when all promises succeed, i.e. immediately.  This would help me avoid placing an `if` in my code to take care of the special case when there are no promises in my array.

### Actual behavior
An exception was thrown, disrupting the continuum.

**Comment by Grinnz** [comment]
Previously discussed in https://github.com/mojolicious/mojo/issues/1275 and https://github.com/mojolicious/mojo/issues/1505. Without any promises to resolve, it does not know what event loop will be run to resolve the empty `all` promise.

**Comment by akarelas** [comment]
Understood, sorry.
