### ISSUE TITLE
Getting a size difference in content length. from $asset->size vs actual file size.

### ISSUE THREAD

**Issue by spajai** [mojolicious/mojo#1940]
* Mojolicious version: 9.23
* Perl version: (v5.26.1) 
* Operating system:  Ubuntu 18.04.6 LTS

### Steps to reproduce the behavior
Trying to render file using 
[RenderFile Plugin ](https://metacpan.org/pod/Mojolicious::Plugin::RenderFile)
```
        $self->render_file(
            'filepath'            => $csv_file,
            'content_disposition' =>'attachment;filename='.$dataset_name.'.csv',
            'cleanup'             => 1,                     # delete file after completed
        );

original bytes 4633400 (file produce on source by linux)
bytes sent 4628480  <= (verified with (Mojo::Asset::File->new( path => $filepath );  print  $asset->size;)

original wc -l 50001
received file wc -l 49949

```

### Expected behavior
Should Have sent the actual content of file.

### Actual behavior
The file content of CSV is getting truncated automatically.

* When checking the source file size using Perl its the same as the bytes sent.
but on receiving end the file content is getting truncated when compared the source file and destination file,
I am missing something? 

the linux has returned me the file size on disk where as perl has return me the file size of the actual content.

**Comment by kraih** [comment]
What makes you believe this is a Mojolicious bug?

**Comment by kraih** [comment]
We use issues for concrete bugs, discussions about possible issues are better kept on our support channels. https://docs.mojolicious.org/#SUPPORT

**Comment by spajai** [comment]
Thanks, @kraih  Noted.
