### ISSUE TITLE
Update to Bootstrap 5

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1975]
The [built-in templates](https://github.com/mojolicious/mojo/tree/main/lib/Mojolicious/resources/templates/mojo) still use [Bootstrap 4 and jQuery](https://github.com/mojolicious/mojo/tree/main/lib/Mojolicious/resources/public/mojo). In mojo.js we are already using Bootstrap 5 and have removed jQuery. The same should happen for Mojolicious. Slight complication is that the interactive UI elements have no test coverage yet, otherwise this should be very straight forward.

**Comment by dvinciguerra** [comment]
Can I help with this issue!?

**Comment by kraih** [comment]
> Can I help with this issue!?

Of course!

**Comment by dvinciguerra** [comment]
Almost done!

![image](https://user-images.githubusercontent.com/114177/195601374-0f12b80e-64f8-4dba-9065-02a4d62419e4.png)
**bootstrap current version**

![image](https://user-images.githubusercontent.com/114177/195601268-55e64d5d-253f-45b2-9cf2-87a1161723d4.png)
**bootstrap 5.2.2**

Need some more time to finish the `tap for more` slider (accordion) and ensure component behaviours are the same on this two versions. =)

**Comment by sergiotarxz** [comment]
Can I take this issue? And if so should I copy what mojo.js does? Am I supposed to create the missing unit tests? And if I should create the unit test to which extent? Should I do something like this https://github.com/mojolicious/mojo.js/blob/main/test/exception-app.js?

**Comment by kraih** [comment]
After two years the issue is definitely up for grabs. No, i don't think you need to add new tests. But you'll have to confirm with screenshots that everything works.

**Comment by kraih** [comment]
Done.
