### ISSUE TITLE
[BUG] Mojo::DOM returns corrupt HTML

### ISSUE THREAD

**Issue by NightMachinery** [mojolicious/mojo#1999]
* Mojolicious version: I don't know how to get this.
`perl -le 'eval "require $ARGV[0]" and print $ARGV[0]->VERSION' Mojo::DOM` returns empty. But I installed it today, so probably the latest version.
* Perl version: 5.34
* Operating system: macOS 12.2.1

### Steps to reproduce the behavior
Provided at https://github.com/NightMachinery/tmp_mojo_bug .

**Comment by MartinMcGrath** [comment]
Opening gen.htm from your repo in Firefox or Chrome also returns a blank page, your script tag is malformed. it should be:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML" ></script>
</head>
```
Print module version:

`perl -MMojolicious -e 'print $Mojolicious::VERSION';`

**Comment by MartinMcGrath** [comment]
![image](https://user-images.githubusercontent.com/1374568/198988276-f41aaa55-0802-4650-b7ab-c079c38d6335.png)
Here in the developer console you can see you 'as is' input html, the unclosed script tag followed by the remainder of the page content. Fixing this results in proper rendering:

![image](https://user-images.githubusercontent.com/1374568/198988659-a2ff6a4f-1958-497f-acee-e819dfb50115.png)

**Comment by daleif** [comment]
Here is a good summary about why `<script />` is not allowed

https://stackoverflow.com/a/28719226/1195114

**Comment by NightMachinery** [comment]
`perl -MMojolicious -e 'print $Mojolicious::VERSION';`
9.28

@MartinMcGrath Can you try it again? `gen.html` was the wrong file, I fixed it.

The script tag is okay in both files if you open them with a text editor:

- gen.html
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML"></script>
```
- out.html
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML" />
```

The problem happens because Mojo::DOM is encoding and decoding HTML entities incorrectly.

**Comment by daleif** [comment]
I'd say I agree with @NightMachinery, `Mojo::DOM` will convert say `<div></div>` into `<div />` but this is not always correct. One example is exactly the `<script>` tag.

Anyone know why `Mojo::DOM` even converts an empty tag pair into `<tag />` in the first place.

(note that perl 5.34 and `vlb` is probably not really relevant in this case). A simpler example might be

```
<?xml version="1.0" encoding="utf-8"?>
<html>
<script src="https://example.com"></script>
</head>
<body>
  test
  <div></div>  
  <p></p>  
</body>
</html>
```

which with `9.28` is converted into 

```
<?xml version="1.0" encoding="utf-8"?>
<html>
<script src="https://example.com" />

<body>
  test
  <div />  
  <p />  
</body>
</html>
```

**Comment by kraih** [comment]
So you're forcing XML parsing rules, and then complain when it uses XML parsing rules?

**Comment by NightMachinery** [comment]
> So you're forcing XML parsing rules, and then complain when it uses XML parsing rules? Of course it doesn't apply the special `<div>` rules for XML. 🤷

So how do I make it use HTML parsing rules? And why isn’t that the default?

**Comment by kraih** [comment]
> > So you're forcing XML parsing rules, and then complain when it uses XML parsing rules? Of course it doesn't apply the special `<div>` rules for XML. 🤷
> 
> So how do I make it use HTML parsing rules? And why isn’t that the default?

Just don't include an XML declaration like `<?xml version="1.0" encoding="utf-8"?>`.

**Comment by NightMachinery** [comment]
[**@kraih**](https://github.com/kraih) commented on [Oct 31, 2022, 4:38 PM GMT+3:30](https://github.com/mojolicious/mojo/issues/1999#issuecomment-1297063930 "2022-10-31T13:08:38Z - Replied by Github Reply Comments"):
> > > So you're forcing XML parsing rules, and then complain when it uses XML parsing rules? Of course it doesn't apply the special `<div>` rules for XML. 🤷
> > 
> > So how do I make it use HTML parsing rules? And why isn’t that the default?
> 
> Just don't include an XML declaration like `<?xml  version="1.0"  encoding="utf-8"?>`.

I did not produce this file. It is what it is. Is there a way to make it work?

**Comment by MartinMcGrath** [comment]
@NightMachinery force HTML semantics:

`my $dom = Mojo::DOM->new->xml(0)->parse($input);`

From [the documentation](https://metacpan.org/pod/Mojo::DOM#CASE-SENSITIVITY)
