### ISSUE TITLE
Promise from Mojo::UserAgent can't be ran in Mojolicious controller

### ISSUE THREAD

**Issue by darrenli912** [mojolicious/mojo#2033]
* Mojolicious version: 9.31
* Perl version: v5.30.0
* Operating system: UBUNTU 20.    on  5.15.79.1-microsoft-standard-WSL2

### Steps to reproduce the behavior
My code in controller:

sub test {
    my $self    = shift;
        my $ua = Mojo::UserAgent->new;
        $ua->get_p(
            "https://www.cpan.org" 
        )->then(
            sub {
                my ($tx) = @_;
                $self->render( 
                    text => $tx->result->body);
            }
        )->catch(
            sub {
                my ($err) = @_;
                return $self->reply->exception($err);
            }
        )->wait;
        $self->render_later;

}

### Expected behavior
Promise can be ran correctly in Mojolicious controller. 
### Actual behavior
Get the error:
Premature connection close. The fetch url code can't be ran.

**Comment by kraih** [comment]
User agent goes out of scope.

**Comment by kraih** [comment]
https://docs.mojolicious.org/Mojolicious/Guides/FAQ#What-does-Premature-connection-close-mean
