### ISSUE TITLE
Exceptions are not available in the after_dispatch hook when exception_format is set to json

### ISSUE THREAD

**Issue by evoyy** [mojolicious/mojo#2048]
* Mojolicious version: 9.31
* Perl version: 5.36.0
* Operating system: Ubuntu 22.04

### Steps to reproduce the behavior

According to the Routing guide, the recommended way to forward exceptions to a web service is in the ````after_dispatch```` hook:

````perl
# Forward exceptions to a web service
$app->hook(after_dispatch => sub ($c) {
  return unless my $e = $c->stash('exception');
  $c->ua->post('https://example.com/bugs' => form => {exception => $e});
});
````

https://docs.mojolicious.org/Mojolicious/Guides/Routing#Hooks

However, when the `exception_format` is set to `json`, the exception is not available in the stash, so it is not possible to forward exceptions to a web service using the same technique. I'm not sure if this would be considered a bug or just a limitation of using json format exceptions.

**Comment by rawleyfowler** [comment]
Working on a fix for this.

**Comment by evoyy** [comment]
Confirmed working, thanks!
