### ISSUE TITLE
Consider becoming a Brave verified creator

### ISSUE THREAD

**Issue by evoyy** [mojolicious/mojo#2066]
It's very simple, you just sign up via the link below and then add a TXT record to the DNS of mojolicious.org (and mojojs.org) and it will mean people who use Brave and have opted into Brave Rewards can contribute to the project using the BAT tokens they have earned. I for one have earned quite a few BAT tokens that I'd be happy to donate (or tip, as Brave calls it).

https://creators.brave.com/

**Comment by kraih** [comment]
No, dealing with taxes for this kinda stuff is a nightmare.

**Comment by ralyodio** [comment]
who pays TaXeS in CrYpTo?!

**Comment by evoyy** [comment]
That's understandable. I haven't considered the tax implications.
