### ISSUE TITLE
Wrong explanation in sample what escapes XML and what is not (<%= vs <%==)

### ISSUE THREAD

**Issue by nugged** [mojolicious/mojo#2095]
https://github.com/mojolicious/mojo/blob/058216dd0aafa0d5888edf5e53412f043487a914/lib/Mojo/Template.pm#L330-L331

is opposite to

https://github.com/mojolicious/mojo/blob/058216dd0aafa0d5888edf5e53412f043487a914/lib/Mojo/Template.pm#L343-L344

**Comment by jberger** [comment]
If you read the line above it, you'll see why: https://github.com/mojolicious/mojo/blob/058216dd0aafa0d5888edf5e53412f043487a914/lib/Mojo/Template.pm#L340-L344
