### ISSUE TITLE
Mojolicious::Lite silently ignores controller configurations due to missing default namespaces

### ISSUE THREAD

**Issue by XSven** [mojolicious/mojo#2108]
* Mojolicious version: 9.34
* Perl version: 5.38.0
* Operating system: AIX 7.3
### Steps to reproduce the behavior
I have used the `mojo` tool to create a `Mojolicious::Lite` application. I have enabled the `OpenAPI` plugin. I have used
```
$route->to(ucfirst "$op_spec->{operationId}#handle_request");
```
suggested in the  [op_spec_to_route](https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI#op_spec_to_route) experimental feature to configure controller based request dispatching.
### Expected behavior
I would like to get a warning that an existing controller configuration is dropped due to missing namespace configuration

```
<Mojolicious::Lite application> eval -V 'app->routes->namespaces'
[]
```
### Actual behavior
No information about my incomplete setup was provided. As a Mojolicious newbie this was an annoying experience.

**Comment by kraih** [comment]
I'm afraid the Mojolicious project does not maintain the OpenAPI plugin.

**Comment by XSven** [comment]
copy paste transfer to [#246](https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/246)
