### ISSUE TITLE
running mojo files

### ISSUE THREAD

**Issue by BlackHo0d** [mojolicious/mojo#2120]
I've installed mojo and now can use it in the REPL. But I can't run mojo files. I've read that I should add the following lines to your configuration file (.bash_profile, .bashrc, or .zshrc) but I don't understand how to do it. Can anyone help me with that ?

I'm using Mac OS(Intel)

My issue was closed but I got no help

**Comment by kraih** [comment]
Please stop opening new issues.

**Comment by BlackHo0d** [comment]
Ok, but help me I still didn't get any help. Why are closing issues and don't help ?
