### ISSUE TITLE
Minion UI broken by jQuery removal in latest Mojolicious update

### ISSUE THREAD

**Issue by robhammond** [mojolicious/mojo#2167]
* Mojolicious version: 9.36
* Perl version: 5.30
* Operating system: Ubuntu 20.04

### Steps to reproduce the behavior
Log into the `/minion` UI on a server.

The upgrade to Bootstrap 5 and more specifically the removal of jQuery has broken the Minion UI. 

### Expected behavior
Menu should show counts of jobs in queue. Job table should show user-friendly runtime and time created.

### Actual behavior
The Minion UI now does not show the count of tasks, workers, locks etc in the menu, and all of the created dates and runtimes are not shown correctly.

Screengrab below:

<img width="566" alt="Minion_-_Jobs" src="https://github.com/mojolicious/mojo/assets/1587084/e20de709-d2b0-4f47-9235-1830d06e9004">

**Comment by kraih** [comment]
And resolved: https://github.com/mojolicious/minion/commit/23bea5ad2249bf7a45148deb7c7731e7cc124855
