### ISSUE TITLE
After version 9.32 hypnotoad server works incorrectly with workers and prodices message: "Worker X has no heartbeat (Y seconds), restarting"

### ISSUE THREAD

**Issue by krsvital** [mojolicious/mojo#2190]
* Mojolicious version: > 9.32
* Perl version: 5.32
* Operating system: CentOS Stream 9

### Steps to reproduce the behavior

use Mojolicious::Lite -signatures;
app->config(hypnotoad => {
    listen      => ['http://'.$ENV{IP_ADDR}.':3000'],
    workers     => 10
});

get '/' => sub {
    return shift->render(json => { result => "OK" });
};

app->start;

### Expected behavior
10 workers run and works infinitely

### Actual behavior
manager produces messages like this: "Worker X has no heartbeat (Y seconds), restarting"

**Comment by kraih** [comment]
The diff in question: https://github.com/mojolicious/mojo/compare/v9.32...v9.33

**Comment by krsvital** [comment]
sorry, i found the problem

**Comment by kraih** [comment]
So, what was the problem? And why did upgrading to 9.32 make a difference?
