### ISSUE TITLE
Mojo::JSON, without Cpanel::JSON::XS, doesn't encode booleans correctly in Perl v5.40

### ISSUE THREAD

**Issue by akarelas** [mojolicious/mojo#2191]
* Mojolicious version: 9.37
* Perl version: v5.40.0
* Operating system: Debian Linux 12.6

When `use v5.40;` exists, Perl's builtin core booleans are used instead of Mojo::JSON's. And when Cpanel::JSON::XS is not installed, Mojo::JSON is incapable of dealing with the core booleans in the expected way, leading to mistakes in the output of encode_json.

### Steps to reproduce the behavior

This simple program produces unexpected output:

```perl
#!/usr/bin/env perl

use v5.40;
use FindBin '$RealBin';
use lib "$RealBin/local/lib/perl5";

use Mojo::JSON qw/ true false encode_json /;

say encode_json({a => true, b => false});
```

### Expected behavior

Output should be:

```
{"a":true,"b":false}
```

### Actual behavior

Output is:

```
{"a":1,"b":""}
```

**Comment by karenetheridge** [comment]
Mojo::JSON is a thin wrapper around JSON::PP and Cpanel::JSON::XS. What version of JSON::PP do you have installed? To handle core booleans, you need JSON::PP 4.11 (or when installed, Cpanel::JSON::XS 4.38).

**Comment by akarelas** [comment]
4.16:

```bash
appuser@modules-d:~/work/temp/mojo-json$ carton exec -- perl -M JSON::PP -E 'say $JSON::PP::VERSION;'
4.16
```

This Perl is as fresh as can be, and this is my cpanfile I used with `carton`:

```perl
requires 'perl', '5.040';

requires 'Mojolicious';
```

**Comment by karenetheridge** [comment]
Ah, I see the problem - Mojo::JSON::_encode_value has some custom code, and it doesn't understand the new bools.

I think we could probably remove this implementation and simply defer to JSON::PP, when Cpanel::JSON::XS is not available.

**Comment by akarelas** [comment]
I think your proposed change would break some existing code of Mojo users, because \2 encodes to true in Mojo::JSON, but throws an exception in JSON::PP.

**Comment by Grinnz** [comment]
JSON::PP is not used by Mojo::JSON, and it would not be a good idea because it is slow to the point where it could cause denial of service to users.

**Comment by Grinnz** [comment]
I'm not sure if it would be compatible with existing code which would expect !!1 to encode to the number 1, but since JSON::PP and Cpanel::JSON::XS apparently have made this breaking change, Mojo::JSON should also recognize core booleans in encode_json.

**Comment by kraih** [comment]
If both JSON::PP and Cpanel::JSON::XS have made the breaking change we should follow.
